# Prelude {#prelude .unnumbered}

> There is a magic in graphs. The profile of a curve reveals in a flash a whole situation---the life history of an epidemic, a panic, or an era of prosperity. The curve informs the mind, awakens the imagination, convinces.
--- Henry D. Hubbard, Foreword to @Brinton1939, _Graphic Presentation_

> The graphic art depicts magnitudes to the eye. It does more. It compels the seeing of relations. We may portray by simple
graphic methods whole masses of intricate routine, the organization of an enterprise, or the plan of a campaign. Graphs
serve as storm signals for the manager, statesman, engineer; as potent narratives for the actuary, statist, naturalist; and
as forceful engines of research for science, technology and industry. They display results. They disclose new facts and
laws. They reveal discoveries as the bud unfolds the flower. --- Henry David Hubbard, Foreword to @Brinton1939, _Graphic Presentation_

These inspiring words were written by Henry David Hubbard, the first Secretary of the US National Bureau of Standards,
(also known for modernizing the Mendeleev's periodic table). They reflect the time in the early 1900s
when appreciation for, and applications of graphical methods in science and popular writings had become mainstream, with textbooks
(e.g., @Peddle:1910; @Haskell:1919) and college courses (@Costelloe:1915).

In this period graphical methods were used, perhaps for the first time, to provide new insights, discoveries, and theories in astronomy, physics, biology, and other sciences. For example, 

* Edward W. Maunder [-@Maunder:1904] plotted the occurrence of sunspots by their latitude over time and observed a pattern like the wings of a butterfies, with sunspots drifting toward the equator
in 11 year cycles. This pattern proved crucial for understanding the properties Sun's magnetic field.

* Ejnar Hertzsprung [-@Hertzsprung:1911] and Henry Norris Russell () constructed plots of the luminosity of stars in relation to their color temperature
and discovered an intriguing coherent pattern, with a cluster of stars ("Red Giants") detached from that main sequence.
They used this to explain the changes as a star evolves. It provided an entirely new way to look at stars, and laid the groundwork for modern stellar physics and evolution [@SpenceGarrison:1993].

-> Atomic number 