# R Code for Figures and Analyses {#sec-Rcode}

This online appendix lists the R source files used to produce some of the figures and analyses in each chapter, with links to the source code on GitHub.

This is included here because it may be useful to readers to see the complete context in which many examples were developed, beyond the code displayed in the text. And also because you may want to use or adapt the code for your own work or to develop related examples using the same ideas with different datasets.

It is incomplete because it was constructed by scanning the chapter source files for special comments,
of the form `<!-- fig.code: R/Davis-reg.R -->` that were manually embedded in the chapter `.qmd` files as I wrote this, but not always.
Making this less incomplete proved to be a challenge because it involved scanning the text to find the corresponding R code files that had been included that had been included in chunks.

Files marked &#9888; (if any) do not yet have a descriptive title in their header.

## Chapter 1: Warm-up Exercises {.unnumbered}

- [pollen-animation.R](https://github.com/friendly/vis-MLM-book/blob/master/R/pollen-animation.R) &mdash; pollen data-- zooming in

## Chapter 3: Getting Started {.unnumbered}

- [Davis-reg.R](https://github.com/friendly/vis-MLM-book/blob/master/R/Davis-reg.R) &mdash; Davis data-- Models and plots
- [draft1970.R](https://github.com/friendly/vis-MLM-book/blob/master/R/draft1970.R) &mdash; 1970 Draft Lottery

## Chapter 4: Plots of Multivariate Data {.unnumbered}

- [Salaries-scatterplots.R](https://github.com/friendly/vis-MLM-book/blob/master/R/Salaries-scatterplots.R) &mdash; Salaries data: scatterplots
- [ellipses-coverage.R](https://github.com/friendly/vis-MLM-book/blob/master/R/ellipses-coverage.R) &mdash; demo ellipses of varying coverage
- [prestige.R](https://github.com/friendly/vis-MLM-book/blob/master/R/prestige/prestige.R) &mdash; Prestige data plots
- [peng-ggplot.R](https://github.com/friendly/vis-MLM-book/blob/master/R/penguin/peng-ggplot.R) &mdash; Penguins data, scatterplot matrix, data ellipses and 2D density plots
- [geom-bagplot.R](https://github.com/friendly/vis-MLM-book/blob/master/R/geom-bagplot.R) &mdash; geom_bagplot-- penguin data
- [peng-ggally.R](https://github.com/friendly/vis-MLM-book/blob/master/R/penguin/peng-ggally.R) &mdash; Penguin data, GGally ggpairs
- [peng-ggpcp.R](https://github.com/friendly/vis-MLM-book/blob/master/R/penguin/peng-ggpcp.R) &mdash; Penguin data, parallel coordinate plots
- [projections.R](https://github.com/friendly/vis-MLM-book/blob/master/R/projections.R) &mdash; projections
- &#9888; [peng-tourr.R](https://github.com/friendly/vis-MLM-book/blob/master/R/penguin/peng-tourr.R) &mdash; *no title*
- [crime-network.R](https://github.com/friendly/vis-MLM-book/blob/master/R/crime/crime-network.R) &mdash; network diagram of correlations & partial correlations

## Chapter 5: Dimension Reduction {.unnumbered}

- [workers-pca.R](https://github.com/friendly/vis-MLM-book/blob/master/R/workers-pca.R) &mdash; Workers data - pca
- [crime-ggbiplot.R](https://github.com/friendly/vis-MLM-book/blob/master/R/crime/crime-ggbiplot.R) &mdash; crime data - ggbiplot
- &#9888; `R/crime/factominer.R` &mdash; *file not found*
- [diabetes-3d.R](https://github.com/friendly/vis-MLM-book/blob/master/R/diabetes/diabetes-3d.R) &mdash; Diabetes data, 3D plots
- &#9888; [diabetes-ggbiplot.R](https://github.com/friendly/vis-MLM-book/blob/master/R/diabetes/diabetes-ggbiplot.R) &mdash; *no title*
- [diabetes-mds.R](https://github.com/friendly/vis-MLM-book/blob/master/R/diabetes/diabetes-mds.R) &mdash; Diabetes data, multidimensional scaling (MDS)
- [diabetes-pca-tsne.R](https://github.com/friendly/vis-MLM-book/blob/master/R/diabetes/diabetes-pca-tsne.R) &mdash; Animate transition from PCA <--> tsne
- [mtcars-corrplot.R](https://github.com/friendly/vis-MLM-book/blob/master/R/mtcars-corrplot.R) &mdash; Variable ordering based on PCA & corrplot
- [outlier-demo.R](https://github.com/friendly/vis-MLM-book/blob/master/R/outlier-demo.R) &mdash; Demonstrate correlated data with 2 outliers

## Chapter 6: Overview of Linear models {.unnumbered}

- [workers-reg.R](https://github.com/friendly/vis-MLM-book/blob/master/R/workers-reg.R) &mdash; Workers data - regression models

## Chapter 7: Plots for Univariate Response Models {.unnumbered}

- [dunc-conf-ellipse.R](https://github.com/friendly/vis-MLM-book/blob/master/R/Duncan/dunc-conf-ellipse.R) &mdash; Duncan data Confidence ellipse
- [levdemo.R](https://github.com/friendly/vis-MLM-book/blob/master/R/levdemo.R) &mdash; Leverage and influence demo
- [hatvalues-demo.R](https://github.com/friendly/vis-MLM-book/blob/master/R/hatvalues-demo.R) &mdash; Leverage and the data ellipse
- [duncan-av-influence.R](https://github.com/friendly/vis-MLM-book/blob/master/R/Duncan/duncan-av-influence.R) &mdash; "Duncan data: annotated added-variable plots (Figure 7.27)"

## Chapter 8: Topics in Linear Models {.unnumbered}

- [dual-points-lines.R](https://github.com/friendly/vis-MLM-book/blob/master/R/dual-points-lines.R) &mdash; Illustrate dual points & lines
- [measerr-demo.R](https://github.com/friendly/vis-MLM-book/blob/master/R/measerr-demo.R) &mdash; Simulation for measurement error

## Chapter 9: Collinearity & Ridge Regression {.unnumbered}

- [collin-data-beta.R](https://github.com/friendly/vis-MLM-book/blob/master/R/collin-data-beta.R) &mdash; collinearity in data and beta space
- [cars-colldiag.R](https://github.com/friendly/vis-MLM-book/blob/master/R/cars-colldiag.R) &mdash; cars data - collinearity diagnostics examples
- [collin-centering.R](https://github.com/friendly/vis-MLM-book/blob/master/R/collin-centering.R) &mdash; demonstrate effect of centering
- [acetylene-colldiag.R](https://github.com/friendly/vis-MLM-book/blob/master/R/acetylene-colldiag.R) &mdash; Acetylene data
- [genridge-longley-figs1.R](https://github.com/friendly/vis-MLM-book/blob/master/R/genridge-longley-figs1.R) &mdash; Longley data-- generalized ridge trace plots
- [genridge-longley-figs2.R](https://github.com/friendly/vis-MLM-book/blob/master/R/genridge-longley-figs2.R) &mdash; Longley data-- generalized ridge trace plots

## Chapter 10: Hotelling's $T^2$ {.unnumbered}

- [mathscore-figs.R](https://github.com/friendly/vis-MLM-book/blob/master/R/mathscore/mathscore-figs.R) &mdash; mathscore data
- [banknote.R](https://github.com/friendly/vis-MLM-book/blob/master/R/banknote.R) &mdash; banknote data

## Chapter 11: Multivariate Linear Models {.unnumbered}

- &#9888; [dogfood-ex.R](https://github.com/friendly/vis-MLM-book/blob/master/R/dogfood/dogfood-ex.R) &mdash; *no title*
- [parenting.R](https://github.com/friendly/vis-MLM-book/blob/master/R/parenting.R) &mdash; Analyses and plots for the `heplots::Parenting` dataset
- &#9888; `R/AddHealth.R` &mdash; *file not found*
- &#9888; [NLSY-ex.R](https://github.com/friendly/vis-MLM-book/blob/master/R/NLSY-ex.R) &mdash; *no title*
- [schooldata-ex.R](https://github.com/friendly/vis-MLM-book/blob/master/R/schooldata-ex.R) &mdash; Models and plots for the schooldata dataset
- [Rohwer-scat.R](https://github.com/friendly/vis-MLM-book/blob/master/R/Rohwer-scat.R) &mdash; Rohwer plots

## Chapter 12: Visualizing Multivariate Models {.unnumbered}

- [dogfood-quartet.R](https://github.com/friendly/vis-MLM-book/blob/master/R/dogfood/dogfood-quartet.R) &mdash; dogfood quartet

## Chapter 14: Multivariate Influence and Robust Estimation {.unnumbered}

- [mvinfluence-Toy.R](https://github.com/friendly/vis-MLM-book/blob/master/R/mvinfluence-Toy.R) &mdash; toy example for multivariate influence
- [peng-manova.R](https://github.com/friendly/vis-MLM-book/blob/master/R/penguin/peng-manova.R) &mdash; Penguins MANOVA

## Chapter 15: Discriminant analysis {.unnumbered}

- [peng-lda-pred-new.R](https://github.com/friendly/vis-MLM-book/blob/master/R/penguin/peng-lda-pred-new.R) &mdash; Penguin prediction plots
- [iris-lda-ggplot.R](https://github.com/friendly/vis-MLM-book/blob/master/R/iris/iris-lda-ggplot.R) &mdash; plot LDA boundaries with ggplot
- [peng.lda.R](https://github.com/friendly/vis-MLM-book/blob/master/R/penguin/peng.lda.R) &mdash; Penguin data-- lda plots
- [peng-lda-ggplot3.R](https://github.com/friendly/vis-MLM-book/blob/master/R/penguin/peng-lda-ggplot3.R) &mdash; Penguin data discriminant boundaries using candisc

## Appendix: R Code for Figures and Analyses {.unnumbered}

- [Davis-reg.R](https://github.com/friendly/vis-MLM-book/blob/master/R/Davis-reg.R) &mdash; Davis data-- Models and plots

## Utilities {.unnumbered}

These R files are `source()`d by one or more of the scripts above or used directly in a chapter.
They define custom functions and helpers, some used across multiple chapters.

- [penguin-colors.R](https://github.com/friendly/vis-MLM-book/blob/master/R/penguin/penguin-colors.R) &mdash; Define penguin colors and themes
- [matrix2latex.R](https://github.com/friendly/vis-MLM-book/blob/master/R/matrix2latex.R) &mdash; convert matrix to latex
- [ggvectors.R](https://github.com/friendly/vis-MLM-book/blob/master/R/ggvectors.R) &mdash; Draw labeled vectors in a ggplot scene
- [text.usr.R](https://github.com/friendly/vis-MLM-book/blob/master/R/util/text.usr.R) &mdash; Add text to a plot at normalized device coordinates
- [text_usr.R](https://github.com/friendly/vis-MLM-book/blob/master/R/util/text_usr.R) &mdash; Add text to a plot at normalized device coordinates
- [pvPlot.R](https://github.com/friendly/vis-MLM-book/blob/master/R/pvPlot.R) &mdash; Partial variables plots to visualize partial correlation

