project:
  type: book
  output-dir: docs

book:
  title: "Visualizing Multivariate Data and Models in R"
  author:
    - name: Michael Friendly
      url: https://datavis.ca
      # affiliation: Department of Psychology<br>York University
  date: today
  cover-image: images/cover-ellipse.jpg
  favicon: images/favicon/favicon.ico
  # description: |
  #   Learn how to visualize multivariate data and models in R.

  repo-url: https://github.com/friendly/vis-MLM-book
  repo-branch: master
  repo-actions: [issue]
  # repo-actions: [edit, issue, source]
  # repo-subdir: book
  # comments:
  #   hypothesis: true
  # downloads: [pdf]

  # sidebar:
  #   style: "floating"
  #   collapse-level: 1
  #   border: true
  #   search: true

  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-getting_started.qmd
    - 03-multivariate_plots.qmd
    - 04-pca-biplot.qmd
    - linear_models.qmd
    - linear_models-plots.qmd
    - collinearity-ridge.qmd
    - hotelling.qmd
    - mlm-viz.qmd
    - mlm-review.qmd
    - case-studies.qmd
    - eqcov.qmd
    - summary.qmd
    - 90-references.qmd

#bibliography: references.bib
bibliography:
  - bib/references.bib
  - bib/R-refs.bib         # is this still needed? merge with references.bib
  - bib/pkgs.bib           # maintained via code in each chapter
  - bib/packages.bib       # not maintained -- still needed?
  #  - "C:/Dropbox/localtexmf/bibtex/bib/graphics.bib"
  #  - "C:/Dropbox/localtexmf/bibtex/bib/statistics.bib"
  #  - "C:/Dropbox/localtexmf/bibtex/bib/timeref.bib"
csl: bib/apa.csl
#biblio-style: apalike
link-citations: true
keep-md: false

crossref:
  chapters: true

page-footer: "Copyright 2022, Michael Friendly" 

knitr:
  opts_chunk:
    fig.path: figs/
#    screenshot.force: true    # for webshot
    
format:
  html:
    html-math-method: mathjax
    theme: cosmo
    code-link: true
    filters:
      - quarto
      - line-highlight
    mainfont: "Roboto"
    # monofont: "Fira mono"
    # monofont: "JetBrains Mono"
  # include-before-body: latex-commands.qmd
  #   linkcolor: "#03638E"
  #   fontsize: "15px"
  #   linestretch: 1.6
  #   smooth-scroll: true
  #   code-link: true
  #   code-tools:
  #     toggle: true
  #     code-fold: false
  #   highlight-style: printing
  #   code-block-bg: true
  # # see https://pandoc.org/MANUAL.html for all options

  docx:
    toc: true
    toc-depth: 2
    number-sections: true
    highlight-style: github
    code-link: true
  
  pdf:
    documentclass: scrreprt
    include-in-header: latex/latex-commands.tex
    pdf-engine: pdflatex


  # pdf:
  #   documentclass: book
  #   lof: true
  #   lot: true
  #   toc: true
  #   # classoption: [onecolumn]
  #   geometry:
  #     - top=30mm
  #     - left=20mm
  #     - heightrounded
  #   hyperrefoptions:
  #     - linktoc=all
  #   colorlinks: true
  #   linkcolor: "blue"
  #   biblio-style: apalike
  #   keep-tex: true
  # pdf:
  #   documentclass: scrreprt
  #   include-in-header: 
  #     text: |
  #       \usepackage{makeidx}
  #       \makeindex
  #   include-after-body: 
  #     text: |
  #       \printindex

#editor: visual

