profile:
  group:
    - [online, print]

project:
  type: book
  output-dir: docs

book:
  title: "Visualizing Multivariate Data and Models in R"
  subtitle: "A Romance in Many Dimensions"
  output-file: "Vis-MLM"
  author:
    - name: Michael Friendly
      url: https://datavis.ca
  date: today
  cover-image: images/cover/cover-peng.jpg
  favicon: images/favicon/favicon.ico
  repo-url: https://github.com/friendly/vis-MLM-book
  site-url: https://friendly.github.io/Vis-MLM-book
  repo-branch: master
  repo-actions: [issue]

bibliography:
  - bib/references.bib
  - bib/R-refs.bib
  - bib/pkgs.bib
  - bib/packages.bib
  - bib/Rpackages-4.5.1.bib
csl: bib/apa.csl
link-citations: true
keep-md: false

crossref:
  chapters: true

page-footer: "Copyright 2024, Michael Friendly"

knitr:
  opts_chunk:
    fig.path: figs/
    crop: null      # disable pdfcrop; MikTeX's pdfcrop.exe is on R's PATH before TinyTeX's and fails
