# Online profile — HTML output, includes online-only chapters/appendices
# Usage: quarto render --profile online --no-clean

book:
  chapters:
    - index.qmd
    - 00-Author.qmd
    - part: "Orienting Ideas"
      chapters:
        - 01-Prelude.qmd
        - 02-intro.qmd
        - 03-getting_started.qmd
    - part: "Exploratory Methods"
      chapters:
        - 04-multivariate_plots.qmd
        - 05-pca-biplot.qmd
    - part: "Univariate Linear Models"
      chapters:
        - 06-linear_models.qmd
        - 07-linear_models-plots.qmd
        - 08-lin-mod-topics.qmd
        - 09-collinearity-ridge.qmd
    - part: "Multivariate Linear Models"
      chapters:
        - 10-hotelling.qmd
        - 11-mlm-review.qmd
        - 12-mlm-viz.qmd
        - 13-eqcov.qmd
        - 14-infl-robust.qmd
        - 15-case-studies.qmd
    - part: "End Matter"
      chapters:
        - 91-colophon.qmd
        - 95-references.qmd
  appendices:
    # - 15-case-studies.qmd   # move here if/when excluded from print
    - 21-discrim.qmd

format:
  html:
    number-sections: true
    html-math-method: mathjax
    theme:
      - styles.scss
    code-link: true
    filters:
      - quarto
      - line-highlight
      - parse-latex
    mainfont: "Roboto"
    monofont: "Fira mono"
    title-block-style: default
    title-block-banner: true
    code-block-bg: 'E8FFFF'
    code-overflow: wrap
    tab-stop: 2
