project:
  type: book
  output-dir: docs

book:
  title: "Visualizing Multivariate Data and Models in R"
  subtitle: "A Romance in Many Dimensions"
  # output-file: "Vis-MLM"
  author:
    - name: Michael Friendly
      url: https://datavis.ca
      # affiliation: Department of Psychology<br>York University
  date: today
  cover-image: images/cover/cover-peng.jpg
  favicon: images/favicon/favicon.ico
  # description: |
  #   Learn how to visualize multivariate data and models in R.

  repo-url: https://github.com/friendly/vis-MLM-book
  site-url: https://friendly.github.io/Vis-MLM-book
  repo-branch: master
  repo-actions: [issue]
  # repo-actions: [edit, issue, source]
  # repo-subdir: book
  # comments:
  #   hypothesis: true
  # downloads: [pdf]
#
  # sidebar:
  #   style: "floating"
  #   collapse-level: 1
  #   border: true
  #   search: true
#

# 
# Add parts.  These could be a part page: I-orienting.qmd
# This didn't work, so commented out

  # chapters:
  #   - index.qmd
  #   - part: "Orienting Ideas"
  #     chapters:
  #       - 01-intro.qmd
  #       - 02-getting_started.qmd
  chapters:
    - index.qmd
    - 00-Author.qmd
    # - 00-Prelude.qmd
    - part: "Orienting Ideas"
    # Use a part page:
    # - part: I-OrientingIdeas.qmd
      chapters:
        - 01-Prelude.qmd
        - 02-intro.qmd
        - 03-getting_started.qmd
    - part: "Exploratory Methods"
      chapters:
        - 04-multivariate_plots.qmd
        - 05-pca-biplot.qmd
    - part: "Univariate Linear Models"
      chapters:
        - 06-linear_models.qmd
        - 07-linear_models-plots.qmd
        - 08-lin-mod-topics.qmd
        - 09-collinearity-ridge.qmd
    - part: "Multivariate Linear Models"
      chapters:
        - 10-hotelling.qmd
        - 11-mlm-review.qmd
        - 12-mlm-viz.qmd
        - 13-eqcov.qmd
        - 14-infl-robust.qmd
        - 15-case-studies.qmd
    # - summary.qmd
    # these should not be in a Part
    - part: "End Matter"
      chapters:
        - 91-colophon.qmd
        - 95-references.qmd
    # appendices:

bibliography:
  - bib/references.bib
  - bib/R-refs.bib         # is this still needed? merge with references.bib
  - bib/pkgs.bib           # maintained via code in each chapter
  - bib/packages.bib       # extra pkgs
  - bib/Rpackages-4.5.1.bib    
  #  - "C:/Dropbox/localtexmf/bibtex/bib/graphics.bib"
  #  - "C:/Dropbox/localtexmf/bibtex/bib/statistics.bib"
  #  - "C:/Dropbox/localtexmf/bibtex/bib/timeref.bib"
csl: bib/apa.csl
#biblio-style: apalike
link-citations: true
keep-md: false

crossref:
  chapters: true

page-footer: "Copyright 2024, Michael Friendly" 

# use {=latex} in a chunk
# from: https://github.com/tarleb/parse-latex#readme

filters:
  - parse-latex

knitr:
  opts_chunk:
    fig.path: figs/

format:
  html:
    html-math-method: mathjax
    theme:
      # - light: "cosmo"
      # - dark: "darkly"
      - styles.scss
    code-link: true
    filters:
      - quarto
      - line-highlight
      - parse-latex
    mainfont: "Roboto"
    monofont: "Fira mono"
    # monofont: "JetBrains Mono"
    # monofont: "Fira code"    # -- give ligatures for |> etc
    title-block-style: default
    title-block-banner: true
    code-block-bg: 'E8FFFF'  # very pale cyan '#f1f1f1'
    code-overflow: wrap
    tab-stop: 2
  # include-before-body: latex-commands.qmd
  #   linkcolor: "#03638E"
  #   fontsize: "15px"
  #   linestretch: 1.6
  #   smooth-scroll: true
  #   code-link: true
  #   code-tools:
  #     toggle: true
  #     code-fold: false
  #   highlight-style: printing
  #   code-block-bg: true
  # # see https://pandoc.org/MANUAL.html for all options

  # docx:
  #   toc: true
  #   toc-depth: 2
  #   number-sections: true
  #   highlight-style: github
  #   code-link: true
  
  # see: https://github.com/bgreenwell/quarto-crc for quarto and CRC press
  #      https://github.com/yihui/bookdown-crc        bookdown, CRC Press
  pdf:
    documentclass: krantz
    classoption: [10pt, krantz2, titlepage, letterpaper]
    include-in-header: latex/preamble.tex
    include-before-body: latex/before-body.tex
    include-after-body: latex/after-body.tex
    # latex-output-dir: pdf
    output-file: Vis-MLM
    keep-tex: true
    latex-tinytex: true
    # can also use pdf-engine: LatexMk / pdflatex ...
    pdf-engine: xelatex
    pdf-engine-opts:
      - '-interaction=nonstopmode'
    latex-makeindex: makeindex
    # latex-makeindex-opts: ["-s", "latex/book.ist"]
    # latex-makeindex-opts:
    #   - "-s latex/book.ist"
    latex-clean: false
    # geometry:
    #   - top=20mm
    #   - left=25mm
    code-block-bg: "e4f0ef" # or #e6f2ee, not 'E8FFFF'  #'#f1f1f1'
    interaction: nonstopmode
    # figure placement
    fig-pos: "htb!"
    # cover image. Will this work? See: https://github.com/quarto-dev/quarto-cli/discussions/1941
    # header-includes: |
    #   \titlehead{\includegraphics[width=6in]{images/cover-ellipses.png}}


  # pdf:
  #   documentclass: scrreprt
  #   include-in-header: latex/latex-commands.tex
  #   pdf-engine: pdflatex


  # pdf:
  #   documentclass: book
  #   lof: true
  #   lot: true
  #   toc: true
  #   # classoption: [onecolumn]
  #   geometry:
  #     - top=30mm
  #     - left=20mm
  #     - heightrounded
  #   hyperrefoptions:
  #     - linktoc=all
  #   colorlinks: true
  #   linkcolor: "blue"
  #   biblio-style: apalike
  #   keep-tex: true
  # pdf:
  #   documentclass: scrreprt
  #   include-in-header: 
  #     text: |
  #       \usepackage{makeidx}
  #       \makeindex
  #   include-after-body: 
  #     text: |
  #       \printindex

#editor: visual

