```{r include=FALSE}
source("R/common.R")
```

# Getting Started {#sec-getting_started}

## Why plot your data? {#sec-why_plot}

## Plots for data analysis


Visualization methods take an enormous variety of forms,  but it is useful to distinguish several broad categories according to their use in data analysis:

* __data plots__ : primarily plot the raw data, often with annotations to aid interpretation (regression lines and smooths, data ellipses, marginal distributions)

* __model plots__ : primarily plot the results of a fitted model, considering that
the fitted model may involve more variables than can be shown in a static 2D plot.
Some examples are: Added variable plots, effect plots, coefficient plots, ...

* __diagnostic plots__ : indicating potential problems with the fitted model. These include residual plots, influence plots, plots for testing homogeneity of variance and so forth.

* __dimension reduction plots__ : plot representations of the data into a space of fewer dimensions than the number of variables in the data set. Simple examples include principal components analysis (PCA) and the related biplots, and multidimensional scaling (MDS) methods.


## data plots

## model plots

## diagnostic plots

