# Preface {.unnumbered}

## ONE, TWO, MANY

There is an old and helpful idea I learned from John Hartigan in my graduate days at Princeton:

> In statistics and data visualization *all* methods can be classified by the number of dimensions contemplated, on a scale of **ONE**, **TWO**, **MANY**.

By this, he meant that, at a global level, all data, statistical summaries, and graphical displays could be classified as:

-   **univariate**: a single variable, considered in isolation (age, COVID cases, pizzas ordered). Univariate numerical summaries are means, medians, measures of variablilty, and so forth. Univariate displays include dot plots, boxplots, histograms and density estimates.
-   **bivariate**: two variables, considered jointly. Numerical summaries include correlations, covariances and two-way tables of frequencies or measures of association for categorical variables. Bivariate displays include scatterplots and mosaic plots.
-   **multivariate**: three or more variables, considered jointly. Numerical summaries include correlation and covariance matrices, consisting of all pairwise values, but also derived measures from the analysis of these matrices (eigenvalues, eigenvectors). Graphical displays of multivariate data can sometimes be shown in
3D, but often involve multiple views of the data projected into 2D plots.

As a quasi-numerical scale, I refer to these as **1D**, **2D** and **nD**. This admits the possibility of half-integer cases, such as 1.5D, where the main focus is on a single variable, but it is classified by a simple factor (gender). His point in this classification was that once you reached three variables, all higher dimensions involved similar summaries and data displays.

Univariate and bivariate methods and displays are well-known.  This book is about how these ideas can
be extended to an $n$-dimensional world. Three-dimensional data displays are now fairly easy to produce,
even if they are sometimes difficult to understand. But how can we even think about four or more dimensions?
The difficulty can be appreciated by considering the tale of _Flatland_.

```{r child="flatland.qmd"}
```

## EUREKA!

## What I assume

I assume the reader to have at least a basic familiarity with R.
While R fundamentals are outside the scope of the current paper, I believe that this language provides a rich set of resources, far beyond that offered by other statistical software packages, and is well worth learning. 

For those not familiar with R, I recommend @Matloff2011, @Wickham2014, and @Cotton2013 for introductions to programming in the language, and @FoxWeisberg:2018 and @Teetor2011 for learning about how to conduct basic statistical analyses. 



## Conventions

# References {.unnumbered}
