---
title: "Topics in linear models"
---

## Measurement error


### OLS is BLUE
In classical linear models, the predictors are often considered to be fixed
variables, or, if random, to be measured without error and independent of the regression errors.
Either condition, along with the assumption of linearity, guarantees
that the standard OLS estimators are unbiased. That is, in a simple linear regression,
$y = \beta_0 + \beta_1 x + \epsilon$, the estimated slope $\hat{\beta}_1$
wiil have an average, expected value $\mathcal{E} (\hat{\beta}_1)$ equal to the true
population value $\beta_1$ over repeated samples.
Not only this, but the Gauss-Markov theorem guarrantees that the OLS estimator is
also 

In practice, of course, predictor variables are often also observed
indicators, subject to error, a fact that is recognized in errors-in-variables
regression models and in more general structural equation models
but often ignored otherwise.  Ellipsoids in data space and $\beta$ space
are well suited to showing the effect of measurement error in predictors on OLS estimates.

