```{r include=FALSE}
source("R/common.R")
```

# Brief review of the multivariate linear model {#sec-mlm-review}

The general multivariate linear model (MLM) can be understood as an extension of the univariate linear model, with the main difference being that there are multiple response variables instead of just one.

In this context, there are multiple techniques that can be applied depending on the structure of the variables at hand. For instance, with one or more continuous predictors and multiple response variables, one could use multivariate regression to obtain estimates useful for prediction. Instead, if the predictors are categorical, multivariate analysis of variance (MANOVA) can be applied to test for differences between groups. Again, this is akin to multiple regression and ANOVA in the univariate context -- the same underlying model is utilized, but the tests for terms in the model are multivariate ones for the collection of all response variables, rather than univariate ones for a single response.


In each of these cases, the underlying MLM is given most compactly using the matrix equation, <!-- $$ --> 
<!-- \newcommand{\sizedmat}[2]{\mathord{\mathop{\mathbf{#1}\limits_{(#2)}}} --> 
<!-- $$ -->

$$
\mathbf{Y}_{n \times p} = 
\mathbf{X}_{n \times q} \, \mathbf{B}_{q \times p} + \mathbf{U}_{n \times p} \:\: ,
$$

where

-   $\mathbf{Y} = (\mathbf{y}_1 , \mathbf{y}_2, \dots , \mathbf{y}_p )$ is the matrix of $n$ observations on $p$ responses;
-   $\mathbf{X}$ is the model matrix with columns for $q$ regressors, which typically includes an initial column of 1s for the intercept;
-   $\mathbf{B}$ is a matrix of regression coefficients, one column for each response variable; and $\mathbf{U}$ is a matrix of errors.

The structure of the model matrix $\mathbf{X}$ is the same as the univariate linear model, and may contain, therefore, 

* quantitative predictors, such as `age`, `income`, years of `education`
* transformed predictors like $\sqrt{\text{age}}$ or $\log{\text{income}}$
* polynomial terms: $\text{age}^2$, $\text{age}^3, \dots$ (using `poly(age, k)` in R)
* categorical predictors ("factors"), such as treatment (Control, Drug A, drug B), or sex; internally a factor with `k` levels is transformed to `k-1` dummy (0, 1) variables, representing comparisons with a reference level, typically the first.
* interaction terms, involving either quantitative or categorical predictors, e.g., `age * sex`, `treatment * sex`.



## ANOVA -\> MANOVA

## MRA -\> MMRA

## ANCOVA -\> MANCOVA

## Repeated measures designs
