---
title: "Quarto test-- eqn cross refs"
author: "Michael Friendly"
date: today
format:
  html:
    html-math-method: mathjax
    theme:
      - styles.scss
  pdf:
    documentclass: krantz
    classoption: [10pt, krantz2, titlepage, letterpaper]
    include-in-header: latex/preamble.tex
    keep-tex: true
    latex-tinytex: true
---

```{r include=FALSE}
source("R/common.R")
```


## Unresolved cross-references in aligned equations

Aligned equations, using equation labels, like: `\begin{align*} equation \end{align}{#eq-glm}` work in HTML, _but not in PDF_.
That is, they generate equation numbers which can be cross-referenced in HTML, but generate warnings in PDF and the cross-refs
print as `?@eq-glm`.

In Quarto, constructs like this already imply an equation environment in LaTeX, so they cannot be included within `$$ ... $$`

There is discussion of this in [Quarto-dev](https://github.com/quarto-dev/quarto-cli/issues/2275)

An example is:

```
\begin{align*}
\mathbf{y} & = \beta_0 + \beta_1 \mathbf{x}_1 + \beta_2 \mathbf{x}_2 + \cdots + \beta_p \mathbf{x}_p + \boldsymbol{\epsilon} \\
           & = \left[ \mathbf{1},\; \mathbf{x}_1,\; \mathbf{x}_2,\; \dots ,\; \mathbf{x}_p \right] \; \boldsymbol{\beta} + \boldsymbol{\epsilon} \\
\end{align*} {#eq-glm}
```

Try this out:

\begin{align*}
\mathbf{y} & = \beta_0 + \beta_1 \mathbf{x}_1 + \beta_2 \mathbf{x}_2 + \cdots + \beta_p \mathbf{x}_p + \boldsymbol{\epsilon} \\
           & = \left[ \mathbf{1},\; \mathbf{x}_1,\; \mathbf{x}_2,\; \dots ,\; \mathbf{x}_p \right] \; \boldsymbol{\beta} + \boldsymbol{\epsilon} \\
\end{align*} {#eq-glm}

As you see in @eq-glm ...

Or, try this with the `aligned` environment which can be used inside `$$ ... $$`

$$
\begin{aligned}
\mathbf{y} & = \beta_0 + \beta_1 \mathbf{x}_1 + \beta_2 \mathbf{x}_2 + \cdots + \beta_p \mathbf{x}_p + \boldsymbol{\epsilon} \\
           & = \left[ \mathbf{1},\; \mathbf{x}_1,\; \mathbf{x}_2,\; \dots ,\; \mathbf{x}_p \right] \; \boldsymbol{\beta} + \boldsymbol{\epsilon} \\
\end{aligned}
$${#eq-glm2}

As you see in @eq-glm2 ...



## Index entries

Want to index function references automatically.

The functions `r func("lm()")` and `r func("car::vif()")` are good test cases.

<!-- But `r func("geom_smooth()")` and `r func("stat_ellipse()")` need to have the `_` escaped inside `\texttt{}` -->
