## Bagplots

\ixon{bagplot}

If you are concerned about the assumption of bivariate normality entailed by the data ellipse, a very nice
non-parametric and robust alternative  is a 2D generalization of a boxplot called
a **bagplot**, introduced by @Rousseeuw-etal:2012. 
The idea is very simple. The bagplot consists of three nested polygons, called the "bag", the "fence", and the "loop":

* **bag**: The central 50% box of the boxplot is replaced by a polygon called the "bag", constructed on the basis of _depth_ of points from the bivariate depth median point. Depth generalizes the univariate concept of rank, but counted from the medians point outward in any direction.
The bag contains at most 50% of the most central data points.
\ix{depth}

* **fence**: The univariate fences are replaced by a "fence" polygon,  by expanding the bag outward by a factor (`coef`), usually 3, from the depth median.

* **loop**: Points beyond the fence (the "loop") are potential outliers, sometimes plotted as a convex hull surrounding _all_ of the observations, but better rendered simply as a scatterplot of just those points.

In this way, the bagplot visualizes the bivariate location (median), spread, correlation, skewness, and tails of the data.
Compared with a standard data ellipse, it serves as a visual test of normality and provides a simple way to identify outliers.

Bagplots are implemented in `r pkg("gggda", cite=TRUE)` in the `ggplot2` framework as `geom_bagplot()` with computations done
via `stat_bagplot()`.
For the Penguin data, the bagplot version of @fig-peng-ggplot2 is shown in @fig-peng-bagplot.

```{r}
#| label: fig-peng-bagplot
#| out-width: "80%"
#| code-fold: show
#| fig-cap: "**Bagplot**: For each Penguin species the darker inner (bag) polygon reflects the innermost 50% of the data points. The outer (fence) polygon corresponds to points enclosed by a multiple of the bag. Points outside the fence for each species are ploted individually."
ggplot(peng, 
       aes(x = bill_length, y = bill_depth,
           color = species, shape = species, fill=species)) +
  geom_smooth(method = "lm", formula = y ~ x,
              se=FALSE, linewidth=2) +
  geom_bagplot(bag.alpha = 0.5,
               outlier.size = 5,
               fraction = 0.5,    # bag fraction
               coef = 2.5,        # fence factor
               show.legend = FALSE) +
  theme_penguins("dark") +
  legend_position(c(0.87, 0.15)) 
```

Compared with the data ellipses shown in @fig-peng-ggplot2, the bag polygons have shapes very close to ellipses,
giving credence to the assumption of (approximate) normality. Using the factor `coef = 2.5` causes five points to be flagged as potential
outliers. Bivariate skewness is indicated when the bag and fence is not symmetric around the central median in some direction,
as is slightly true for all three species.

I discuss other visual tests of multivariate normality in @sec-multivar-normality and consider outlier identification
for the Penguin data in @sec-multnorm-penguin below.
\ix{outliers}

\ixoff{bagplot}
