## 3D scatterplots
##

Bivariate scatterplots, even with all the bells and whistles for enhancement, still remain just a 2D view of data that is really of higher dimensions.
Each 2D plot is just a shadow of the data on two of the coordinate axes (as illustrated in @fig-cover-GBE).
3D scatterplots offer the potential to visualize data with three continuous variables simultaneously.
In some cases, this may allow you to identify complex relationships, patterns, clusters, and outliers that might be missed in 2D plots. 
However, 3D plots are more difficult to construct in software and ...

By providing a spatial representation of data points in an X-Y-Z grid, they offer a comprehensive understanding of how variables interact and how changes in one affect others. Static images, if viewed from a favorable orientation, can be quite informative.
Interactivity, such as dragging or zooming with a mouse and animation, like rotation around an axis, allow for viewing the data from multiple angles, further aiding insight. Among R packages for producing such 3D graphs the most advanced are in
the `r package("rgl", cite=TRUE)`. It uses [OpenGL](https://learnopengl.com/) for real-time rendering. You can rotate, zoom, select data points with your mouse and create snapshots or movies of a 3D scene.

Example: 3D views of Penguin data
Use code from `R/penguin/peng-3d-rgl.R`

Images: static - `images/peng-3D-ellipses.png`
  Animated: images/peng-3D-ellipses.png

Example: 3D views of Duncan data

Code: R/Duncan/Duncan-3D.R
 * scatter3d() with data ellipse in x,z plane
 * vector-space representation with matlib::regvec3d()
