## About this book

This book has a very long history, but I didn't quite realize that until I was well underway. As it turns out, I've been
working towards this book for my entire career, over 60 years. You might find this account of some interest.

The first thing that happened, when I first arrived at Princeton, in the summer of 1966, we Psychometric Fellows had to take a course in matrix algebra,
given at Educational Testing Service, our patron.

When I was a graduate student in psychometrics at
Princeton, I happened to sit in on the undergraduate course on Exploratory Data Analysis given by John W. Tukey,
just as he was writing his EDA book on this topic. 
-> cite Memories of EDA

I had taken all the Psychology statistics courses 
(regression, ANOVA, factor analysis, test theory, ...), but Tukey opened my eyes, quite literally, to the wider view that 
data analysis was so much more than models, formulas and numbers. Graphical methods, even simple pencil and paper ones,
could transform a batch of numbers into plots that showed what's going on, what might be unusual and allow sensible comparisons
and reasonable conclusions. The idea of data analysis, as distinct from statistics became rooted in my head.

Then, something else happened: I discovered geometry, particularly as it related to multivariable statistical problems.
When I first arrived at Princeton, in the summer of 1966, we Psychometric Fellows had to take a course in matrix algebra,
given at Educational Testing Service, our patron. 

-> @Dempster:69

-> MDS -> geometric data analysis


## Theory into practice
* need software to express graphical ideas
-> Mao: Theory --> practice; Tukey: Practical power = statistical power * prob of use

Early on, I learned that you need to understand and write software to translate statistical analyses into results
and numerical data into graphs. Tukey (ref:Tukey-duckworth)  expressed this in the aphorism:
"The practical power of a statistical test is the product of its' statistical power and the probability of use".
A shorter version is Chairman Mao's dictum, **Theory into Practice**.

We used FORTRAN in those days

## Filling the gaps

“Without breaks, faults, and gaps, nothing could grow and nothing would become.”
― Brianna Wiest, The Mountain Is You: Transforming Self-Sabotage Into Self-Mastery 

What art is, in reality, is this missing link, not the links which exist. It's not what you see that is art; art is the gap.
- Marcel Duchamp

How does one proceed as a young academic looking to make a mark and establish a reputation in his area?

## LaTeX, Rmarkdown, Quarto


