---
title: "GavinK_pass2_comments"
output: html_document
---

The below contains comments written from my second pass through the book. My second pass was to tackle issues as outlined in `issues/Gavin-SummerWork.md`.

Note that when I quote text from the book, I remove certain things such as the r in "r pkg("package_name")" so that this doc will render properly.

# Chapter 2: Introduction

- Dead link in footnote: http://friendly.apps01.yorku.ca/psy6140/

# Chapter 3: Getting Started

> Tables are not usually designed to reveal *patterns, trends or anomalies*, although this can
be accomplished with modern table generating software such as the ` pkg("tinytable")` or `pkg("gt")` packages.[^tables]

- Maybe this is a good place to plug your `vcdExtra::color_table()` work

> See Friendly (2008); Friendly & Wainer (2021) for this history. .

- Extra dot needs removal

## 3.1 --- Why should you plot your data?

### 3.1.1 --- Anscombe's quartet

- Do you want `R/datasaurus.R` referenced here?

### 3.1.2 --- One lousy point can ruin your day

> Similarly, the regression lines showed the expected slope, $b \approx 1$ for men, but that for women was only 0.26.
It didn't make sense.

- Wondering if you want to change $b$ to $\hat{\beta}$
  + There is another example of this later on in the chapter ("$b = -0.231$")

# Chapter 4: Plots of Multivariate Data

## 4.1 --- Bivariate summaries

> Before looking at differences between males and females,
we would want consider faculty `rank` (related also to `yrs.service`)
and `discipline`,

- Missing "to": i.e., "want to consider" **[GK: FIXED]**

### 4.1.2 --- Stratifiers

> The "S Book" (@ChambersHastie1991) laid out the framework for fitting models with `lm()` and `glm()`, the notion of model objects and methods like `plot()` and `coef()` for working with them, and the basic ideas of base-R graphics, such as adding `text()`, `lines()` and `points() to a plot.

- Missing \` after `points()` **[GK: FIXED]**

# Chapter 8: Topics in Linear Models

## 8.1 --- Ellipsoids in data space and $\beta$ space

### 8.1.2 --- Data ellipse and confidence ellipse

- *fig-coffee-data-beta-both* has code dropdown appear underneath the figure as opposed to above it (in HTML version)

- Not sure how you want to handle R code appendix for "coffee measerr" files

# Chapter 9: Collinearity & Ridge Regression

## 9.5 --- Remedies for collinearity: What can I do?

>Centering of predictors has an added benefit: the fitted coefficients are **easier to interpret***

- Is this a stray \*?

# Chapter 11: Multivariate Linear Models

## 11.8 --- ANCOVA -> MANCOVA

### 11.8.1 --- Example: Paired-associate tasks and academic performance

- Code for *fig-Rohwer-scats* uses the magrittr pipe instead of the native R pipe

# Colophon

- Should R version number be updated before production?