---
title: "GavinK --- Remaining Notes/Tasks from Reviewers"
output: html_document
---

Below contains specific tasks from reviewers that have yet to be fixed, organized both by section within the book and within the Reviewer's document. I have also included ones I am unsure of, just to be sure.

This file is a work-in-progress and not all tasks/issues are listed below.
  
- Reviewer 1 tasks/issues list complete
- Reviewer 2 tasks/issues list is a work-in-progress

___

# Reviewer 1

- Missing summaries for Chapters 14 and 15
- Check if all links work in .pdf (specifically in TOC)
- Wanted more discussion and comparison of:
  + Other graphics, specifically parallel coordinate plots and rotating plots
  + Alternative models
  + Book by Hastie et al.
- Box quotation at start of chapter 12 "... fits if you change the first phrase to 'Using small datasets'"
- Numbers in first case study do not agree with what was said in the text (?)
- Origin of `iris` dataset not correctly described (?)

___

# Reviewer 2

## Chapter 3: Getting Started

**Text:**

> What went wrong here? Examination of the original data sheets showed that this woman (case 12) mistakenly switched the values, recording her reported weight in the box for measured weight and vice versa. The puzzling numerical results were crystal clear in the graphs.

**Reviewer Comment:**

> The text should indicate that the woman mistakenly reported her height (not her weight)

