---
title: "GavinK_CodeReduction_Comments"
output: html_document
---

The below contains the **code-fold audit**. Organized by section, chunks of code that I think could be folded are listed along with my reasoning.

Sections that do not contain code that I think could be folded are excluded.

# Chapter 1: Warm-up Exercises

## 1.5 --- Multivariate scientific discoveries

***Label: fig-diabetes1***

- The narrative here is what the figure shows as opposed to its creation in R

- This is the only figure in the chapter with code shown explicitly.

# Chapter 3: Getting Started

## 3.1 --- Why plot your data?

### 3.1.2 --- One lousy point can ruin your day

***Label: fig-davis-reg1***

- The narrative here is what the figure shows as opposed to its creation in R

***Label: fig-davis-reg2***

- The text describing the reversing of the `x` and `y` axes may be sufficient (removing the necessity for code to be displayed)

- A figure in Chapter 4 (label: `fig-Salaries-lm`) has similar prose before it is introduced and the code is folded. Moreover, I am thinking `fig-davis-reg2` should have its code folded for consistency.

# Chapter 4: Plots of Multivariate Data

## 4.2 --- Data Ellipses

### 4.2.3 --- R functions for data ellipses

***Label: fig-Prestige-scatterplot-educ1***

- Wondering if this figure should have its code folded since the only change from the figure directly previous (besides font size; label: `fig-Prestige-scatterplot-income1`) is the independent variable.

## 4.7.1 --- Visual thinning

***Label: fig-crime-spm***

- I think the code can be folded since the main difference between this and previous `scatterplotMatrix()` calls (two additional arguments) is sufficiently described in the preceding text.

# 4.9 --- Generalized pairs plots

***Label: ggally-smooth-fns***

- I don't think this chunk adds a substantial amount to the narrative given that the functions are mentioned in-text.

# Chapter 5: Dimension Reduction

## 5.3 --- Biplots

### 5.3.3 --- Example: Crime data

***Label: fig-crime-biplot3***

- The only addition from fig-crime-biplot***2*** was the `choices` argument (described in text)

# Chapter 7: Plots for Univariate Response Models

## 7.2 --- Coefficient displays

### 7.2.3 --- More useful coefficient plots

***Label: fig-modelplot3***

- Could be folded as it contains the same code as fig-modelplot2 apart from a change in models used, plot title, and (error bar?) line width

# Chapter 9: Collinearity and Ridge Regression

## 9.5 Remedies for collinearity: What can I do?

***Label: fig-collin-centering***

- The narrative here is what the figure shows as opposed to its creation in R

- Unlikely that the reader will need to reproduce the figure

## 9.9 --- Low-rank views

***Label: fig-longley-pca-dim56***

- I am thinking that by this point in the chapter it should be clear to the reader how to make such a plot. The code here also does not add meaningfully to the narrative (in my opinion). Thus, the code may be folded.

# Chapter 11: Multivariate Linear Models

## 11.5 --- Factorial MANOVA

***Label: fig-jury-ggline***

- Visualizations are very similar to ones shown in the previous example (which have code shown). Code can be folded here as it does not add meaningfully beyond the previous example.

## 11.6 --- MRA -> MMRA

### 11.6.1 --- Example: NLSY data

***Label: fig-NLSY-density***

- Exploratory (box)plots for a previous example in the chapter are folded already (see `fig-dogfood-boxplot`). This chunk may be folded for consistency.

# Chapter 12: Visualizing Multivariate Models

## 12.8 --- Factorial MANOVA

***Label: fig-jury-can***

- Visualization is very similar to one shown in a previous example (fig-iris-candisc). Code can be folded here as it does not add meaningfully beyond the previous example (the only meaningful difference I observed was changing the ellipse coverage with `ellipse.prob`).

    - If it's necessary to mention the `ellipse.prob` argument explicitly, I think it would be better placed in-text.

## 12.9 --- Quantitative predictors: MMRA

***Label: fig-school-heplot1***

- I am thinking that by this point in the chapter it should be clear to the reader how to make such a plot. The code here also does not add meaningfully to the narrative (in my opinion). Thus, the code may be folded.

***Label: fig-school-heplot2***

- I am thinking that by this point in the chapter it should be clear to the reader how to make such a plot. The code here also does not add meaningfully to the narrative (in my opinion). Thus, the code may be folded.


<!-- I have read up to and including Chapter 12 -->