---
title: "Quarto growing pains"
author: Michael Friendly
date: today
---

When I started writing my book, [Visualizing Multivariate Data and Models in R](https://friendly.github.io/Vis-MLM-book/),
I chose to use [Quarto](https://quarto.org/) over [bookdown]() because I thought it would be easier to produce both the printed PDF and online HTML versions from the same source (using conditional divs like `.content-visible when-format=`).

For comparison, by previous book, [Discrete Data Analysis with R](https://www.crcpress.com/Discrete-Data-Analysis-with-R-Visualization-and-Modeling-Techniques-for/Friendly-Meyer/9781498725835) was written using `knitr` and `rmarkdown`
in `.Rnw` files. These were essentially written in LaTeX, with code chunks expressed in the style of Sweave,
which looks strange now,

```
<<arth-read2>>=
levels(Arthritis$Improved)
Arthritis$Improved <- ordered(Arthritis$Improved,
                              levels = c("None", "Some", "Marked"))
@
```

I used different editors (UltraEdit) and IDEs (Eclipse) then, but for writing, I could use keyboard shorthands and macros to insert code chunks, LaTeX figure or table environments, and so forth.

But the result was that the **process of writing, editing and viewing** the current draft or just the current chapter was totally under my control.
I could ...




## You can't use Dropbox

## LaTeX math a new challenge

## Quarto doesn't like competition

```
ERROR: The process cannot access the file because it is being used by another process. (os error 32): remove 'C:\R\projects\Vis-MLM-book\index.tex'
```


