---
editor: 
  markdown: 
    wrap: 120
---

# Preface

> However, to do this it is useful to set the stage for multivariate thinking, with a grand scheme for statistics and data visualization, a parable, and an example of multivariate discovery.

- However, to do this it is useful to set the stage for multivariate thinking with a grand scheme for statistics, data visualization, a parable, and an example of multivariate discovery.

> scatterplot can show other variables using color, shape or other
> visual attributes
> His point in this classification was that once you've reached three variables, all higher

scatterplot can show other variables using color, shape or other
visual attributes.
His point in this classification was that once you've reached three variables, all higher

> the plane he inhabits. It is a large circle when seen at the moment of its' greatest extent. As the Spehere rises, it becomes progressively smaller, until it becomes a point, and then vanishes.

the plane he inhabits. It is a large circle when seen at the moment of its' greatest extent. As the Sphere rises, it becomes progressively smaller, until it becomes a point, and then vanishes.

> To really see a tesseract it helps to view it in an animation over time (@fig-tesseract).

- Rendering of `@fig-tesseract` is broken


The last parts of this section have a few `TODO`s that need to be filled in.

# Part I: Orienting Ideas

## Chapter 1: Introduction

> This material may or may not survive; it was taken from an earlier article.

- Could delete

## Chapter 2: Getting Started

# Part II: Exploratory Methods

## Chapter 3: Plots of Multivariate Data

## Chapter 4: Dimension Reduction

# Part III: Univariate Linear Models

## Chapter 5: Overview of Linear Models

## Chapter 6: Plots for univariate response models

This chapter section should be capitalized

## Chapter 7: Topics in Linear Models

## Chapter 8: Collinearity & Ridge Regression

# Part IV: Multivariate Linear Models

## Chapter 9: Hotelling's $T^2$

## Chapter 10: Multivariate Linear Models

## Chapter 11: Visualizing Multivariate Models

## Chapter 12: Visualizing Equality of Covariance Matrices

## Chapter 13: Multivariate Influence and Robust Estimation

## Chapter 14: Case studies

This chapter section should be capitalized

# Part V: End Matter

- This part section should be capitalized