---
title: "GavinK_ExampleHeadings_Summary"
output: html_document
---

It was noticed that certain "Example" sections in the book are formatted as divs (`{#exm-}`), whereas others are formatted as subheadings (`###`). Below is a per-chapter summary of "Example" section formatting:

- Chapters 1, 2, and 3 have no "Example" sections

- Chapter 4 consistently uses divs

- Chapter 5 uses both divs and subheadings

    - There is also "Example: Crime data" that is formatted as an unnumbered subheading
    
- Chapter 6 consistently uses divs

- Chapter 7 uses both divs and subheadings

- Chapter 8 uses both divs and subheadings

- Chapter 9 consistently uses divs

- Chapter 10 uses both divs and subheadings

- Chapter 11 uses both divs and subheadings

- Chapter 12 consistently uses divs

- Chapter 13 consistently uses divs

- Chapter 14 consistently uses subheadings

    - This chapter has examples as "major" subheadings (e.g., 14.x instead of 14.x.y)
    
    - I believe there is a case for formatting these as 14.x.y, as two examples have the same title (14.4 and 14.6 are "Example: Penguin data"). Both therefore appear unnested on the TOC sidebar and (perhaps) should be nested under the topics they correspond to.

- Chapter 15 consistently uses divs