---
title: "MichaelT_DiscAnalysis_Comments"
output: html_document
---

# Pre-amble

I never thought about it before, but perhaps a page where all the different symbols are listed with a simple definition would be nice? It might be a lot of work, but I think it's nice...

Reading this html and being able to mouse-over the hyper-links, I can't help but feel that HTML is vastly superior to pdfs, particularly when the reading experience isn't necessarily meant to be 'top-down'. 

> The corresponding eigenvectors, $\mathbf{V}$ of $\mathbf{H}\mathbf{E}^{-1}$

- I'm confused, is $\mathbf{V} =  \mathbf{H}\mathbf{E}^{-1}$ or is $\mathbf{V}$ some property of $\mathbf{H}\mathbf{E}^{-1}$?

> In discriminant analysis, you an replace the observed

- In discriminant analysis, you can replace the observed


> But if there are more than $s=2$ dimensions, maybe we can classify nearly as well with a small subset of $k < s$ discriminants without great loss.

- Why is that?


> These methods differ is that in PCA,

- These methods differ in that for PCA,

> This is expressed in the formula for the discriminant function $\delta(\mathbf{x})$ for a new data point $\mathbf{x}$,

- This is expressed in the formula for the discriminant function $\delta_k(\mathbf{x})$ for a new data point $\mathbf{x}$ from group $k$,
?

- Rather than print the dataframe, what about using the html quarto feature to create an HTML interactive data frame? https://quarto.org/docs/dashboards/data-display.html#tables

- Shouldn't there be a way to visualize the lda output for `peng-lda`? I guess this might be explained later-on, but no reference to this possibility is made in this section...

> LDA doesn't provide significance tests, but these are available as described below (@sec-discrim-MANOVA).

- I'm confused, this sentence seems to contradict itself regarding whether LDA has significance tests or not

# Visualizing classification in data space

> In @fig-peng-new-data, I do this in two separate plots, one for the bill length and depth variables, and another for `flipper_length` vs. `body_mass`.

- Why these specific variables? Does this has something to do with the LDA analysis you ran earlier?

# Visualizing classification in discriminant space

> Compared with the separate 2D views in data space (@fig-peng-new-data), this single view accounts for 100% of the variance due to separation of the species groups.

- This is nice, but is there a way to visualize how the predictor variables relate to the discriminant dimensions? If so, I feel that such a plot should precede this one.

## Going Furhter

> For example, if you also wanted to show data ellipses or other bivariate summaries in this plot, it would be necessary to get the predicted classes for all observations in `peng` dataset, together with the discriminant scores, `LD1` and `LD2`, obtained using `scores=TRUE` in the call to `predict_discrim()`. Data ellipses could then be added added using `car::dataEllipse()` as follows (this plot is not shown).

- Why not show the plot?

# Prediction Regions in Discrimnant space

## Adding variable vectors: LDA biplot

> it is necessary to assure that the aspect ratio of the plot is 1, so that one unit on the x-axis is the same length as one unit on the y-axis, which is done using `coord_equal()`.

- I have trust issues with `coord_equal()`. I'm suspicious about whether this plot really is 1:1 between the y and x-axes...


# Quadratic discriminant analysis

> When the covariance matrices $\mathbf{S}_k$ differ across the groups, the disciminant function @eq-lda-fun becomes (@Rao1948)

$$
\delta_k(x) = -\frac{1}{2}\ln|\mathbf{S}_k| - \frac{1}{2}(x-\bar{\mathbf{x}}_k)^\top\mathbf{S}_k^{-1}(x-\bar{\mathbf{x}}_k) + \ln(\pi_k) \; ,
$$ {#eq-qda-fun}

- The notation for $x$ seems to differ from equation A.1.

> but these did not differ dramatically in visual displays (e.g., @fig-covEllipse-pairs).

- This figure reference is broken