---
output: pdf_document
---

**Subject line: ** Permission request for CRC Press book

___

Hi \textcolor{red}{[person/publisher/etc.]},

I am writing to request permission to reprint the following material in a book that CRC Press will soon be publishing in the academic market.

The material for which I am requesting permission is:

\textcolor{red}{[bibliographic info including page range and (if applicable) word count]}

to be reprinted in:

_Visualizing Multivariate Data and Models in R_ by Michael Friendly; proposed date of publication is Fall 2026. Approximately 520 pages.

<!-- List price omitted -->

We require commercial, non-exclusive, worldwide English language rights in all forms and media, including print and eBook form, for the lifetime of the edition.

Appropriate credit will be given in the book's acknowledgements and/or alongside the material. Please indicate your preferred wording.

If you have any questions about this request, please contact either Michael or myself (his research assistant). Michael can be contacted via [friendly@yorku.ca](mailto:friendly@yorku.ca) and I can be contacted via [gklorfin@yorku.ca](mailto:gklorfin@yorku.ca).

Many thanks for your attention to this request.

Best, \newline
Gavin Klorfine