<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.550">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Visualizing Multivariate Data and Models in R - 8&nbsp; Collinearity &amp; Ridge Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./09-hotelling.html" rel="next">
<link href="./07-lin-mod-topics.html" rel="prev">
<link href="./images/favicon/favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/quarto-contrib/line-highlight-1.0.0/line-highlight.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./08-collinearity-ridge.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Collinearity &amp; Ridge Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><header id="title-block-header" class="quarto-title-block default page-columns page-full"><div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title"><span id="sec-collin" class="quarto-section-identifier"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Collinearity &amp; Ridge Regression</span></span></h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Visualizing Multivariate Data and Models in R</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/friendly/vis-MLM-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-getting_started.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Getting Started</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-multivariate_plots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Plots of Multivariate Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-pca-biplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Dimension Reduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-linear_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Overview of Linear models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-linear_models-plots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Plots for univariate response models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-lin-mod-topics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Topics in Linear Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-collinearity-ridge.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Collinearity &amp; Ridge Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-hotelling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Hotelling’s <span class="math inline">\(T^2\)</span></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-mlm-review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Multivariate Linear Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-mlm-viz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Visualizing Multivariate Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./case-studies.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Case studies</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eqcov.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Visualizing Tests for Equality of Covariance Matrices</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./90-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./91-colophon.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Colophon</span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#what-is-collinearity" id="toc-what-is-collinearity" class="nav-link active" data-scroll-target="#what-is-collinearity"><span class="header-section-number">8.1</span> What is collinearity?</a>
  <ul class="collapse">
<li><a href="#visualizing-collinearity" id="toc-visualizing-collinearity" class="nav-link" data-scroll-target="#visualizing-collinearity"><span class="header-section-number">8.1.1</span> Visualizing collinearity</a></li>
  <li><a href="#data-space-and-beta-space" id="toc-data-space-and-beta-space" class="nav-link" data-scroll-target="#data-space-and-beta-space"><span class="header-section-number">8.1.2</span> Data space and <span class="math inline">\(\beta\)</span> space</a></li>
  </ul>
</li>
  <li>
<a href="#sec-measure-collin" id="toc-sec-measure-collin" class="nav-link" data-scroll-target="#sec-measure-collin"><span class="header-section-number">8.2</span> Measuring collinearity</a>
  <ul class="collapse">
<li><a href="#sec-vif" id="toc-sec-vif" class="nav-link" data-scroll-target="#sec-vif"><span class="header-section-number">8.2.1</span> Variance inflation factors</a></li>
  <li><a href="#sec-colldiag" id="toc-sec-colldiag" class="nav-link" data-scroll-target="#sec-colldiag"><span class="header-section-number">8.2.2</span> Collinearity diagnostics</a></li>
  <li><a href="#tableplots" id="toc-tableplots" class="nav-link" data-scroll-target="#tableplots"><span class="header-section-number">8.2.3</span> Tableplots</a></li>
  <li><a href="#collinearity-biplots" id="toc-collinearity-biplots" class="nav-link" data-scroll-target="#collinearity-biplots"><span class="header-section-number">8.2.4</span> Collinearity biplots</a></li>
  </ul>
</li>
  <li><a href="#sec-remedies" id="toc-sec-remedies" class="nav-link" data-scroll-target="#sec-remedies"><span class="header-section-number">8.3</span> Remedies for collinearity: What can I do?</a></li>
  <li>
<a href="#sec:ridge" id="toc-sec:ridge" class="nav-link" data-scroll-target="#sec\:ridge"><span class="header-section-number">8.4</span> Ridge regression</a>
  <ul class="collapse">
<li><a href="#what-is-ridge-regression" id="toc-what-is-ridge-regression" class="nav-link" data-scroll-target="#what-is-ridge-regression"><span class="header-section-number">8.4.1</span> What is ridge regression?</a></li>
  <li><a href="#univariate-ridge-trace-plots" id="toc-univariate-ridge-trace-plots" class="nav-link" data-scroll-target="#univariate-ridge-trace-plots"><span class="header-section-number">8.4.2</span> Univariate ridge trace plots</a></li>
  <li><a href="#bivariate-ridge-trace-plots" id="toc-bivariate-ridge-trace-plots" class="nav-link" data-scroll-target="#bivariate-ridge-trace-plots"><span class="header-section-number">8.4.3</span> Bivariate ridge trace plots</a></li>
  </ul>
</li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/friendly/vis-MLM-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block page-columns page-full" id="quarto-document-content"><!--- For HTML Only ---><!-- %\renewcommand*{\det}[1]{\mathrm{det} (#1)} --><!-- %\renewcommand*{\det}[1]{|#1|} --><!-- \newcommand{\sizedmat}[2]{\mathord{\mathop{\mat{#1}}\limits_{(#2)}}} --><!-- \newcommand*{\E}{\mathcal{E}} --><!-- % R stuff --><blockquote class="blockquote">
<p>Some of my collinearity diagnostics have large values, or small values, or whatever they are not supposed to be * What is bad? * If bad, what can I do about it?</p>
</blockquote>
<p>In univariate multiple regression models, we usually hope to have high correlations between the outcome <span class="math inline">\(y\)</span> and each of the predictors, <span class="math inline">\(x_1, x_2, \dots\)</span>, but high correlations <em>among</em> the predictors can cause problems in estimating and testing their effects. The quote above shows the a typical quandary of some researchers in trying do understand these problems and and take steps to resolve them. This chapter illustrates the problems of collinearity, describes diagnostic measures to asses its effects, and presents some novel visual tools for these purposes using the <strong>VisCollin</strong> package.</p>
<p>One class of solutions for collinearity involves <em>regularization methods</em> such as ridge regression. Another collection of graphical methods, generalized ridge trace plots, implemented in the <strong>genridge</strong> package, sheds further light on what is accomplished by this technique.</p>
<p><strong>Packages</strong></p>
<p>In this chapter we use the following packages. Load them now.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb1" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://r-forge.r-project.org/projects/car/">car</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/friendly/VisCollin">VisCollin</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://friendly.github.io/genridge/">genridge</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://www.stats.ox.ac.uk/pub/MASS4/">MASS</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://www.sthda.com/english/rpkgs/factoextra">factoextra</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggrepel.slowkow.com/">ggrepel</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://patchwork.data-imaginist.com">patchwork</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="what-is-collinearity" class="level2 page-columns page-full" data-number="8.1"><h2 data-number="8.1" class="anchored" data-anchor-id="what-is-collinearity">
<span class="header-section-number">8.1</span> What is collinearity?</h2>
<p>The chapter quote above is not untypical of researchers who have read standard treatments of linear models (eg.: ???) and yet are still confused about what collinearity is, how to find its sources and how to correct them. In <span class="citation" data-cites="FriendlyKwan:2009">Friendly &amp; Kwan (<a href="90-references.html#ref-FriendlyKwan:2009" role="doc-biblioref">2009</a>)</span>, we liken this problem to that of the reader of Martin Hansford’s successful series of books, <em>Where’s Waldo</em>. These consist of a series of full-page illustrations of hundreds of people and things and a few Waldos— a character wearing a red and white striped shirt and hat, glasses, and carrying a walking stick or other paraphernalia. Waldo was never disguised, yet the complex arrangement of misleading visual cues in the pictures made him very hard to find. Collinearity diagnostics often provide a similar puzzle.</p>
<p>Recall the standard classical linear model for a response variable <span class="math inline">\(y\)</span> with a collection of predictors in <span class="math inline">\(\mathbf{X} = (\mathbf{x}_1, \mathbf{x}_2, ..., \mathbf{x}_p)\)</span></p>
<p><span class="math display">\[\begin{aligned}
\mathbf{y} &amp; =&amp;  \beta_0 + \beta_1 \mathbf{x}_1 + \beta_2 \mathbf{x}_2 + \cdots + \beta_p \mathbf{x}_p + \mathbf{\epsilon} \\
         &amp; = &amp; \mathbf{X} \mathbf{\beta} + \mathbf{\epsilon} \; ,
\end{aligned}\]</span> for which the ordinary least squares solution is:</p>
<p><span class="math display">\[
\widehat{\mathbf{b}} = (\mathbf{X}^\textsf{T} \mathbf{X})^{-1} \; \mathbf{X}^\textsf{T} \mathbf{y} \; ,
\]</span> with sampling variances and covariances <span class="math inline">\(\text{Var} (\widehat{\mathbf{b}}) = \sigma^2 \times (\mathbf{X}^\textsf{T} \mathbf{X})^{-1}\)</span> and <span class="math inline">\(\sigma^2\)</span> is the variance of the residuals <span class="math inline">\(\mathbf{\epsilon}\)</span>, estimated by the mean squared error (MSE).</p>
<p>In the limiting case, when one <span class="math inline">\(x_i\)</span> is <em>perfectly</em> predictable from the other <span class="math inline">\(x\)</span>s, i.e., <span class="math inline">\(R^2 (x_i | \text{other }x) = 1\)</span>,</p>
<ul>
<li>there is no <em>unique</em> solution for the regression coefficients <span class="math inline">\(\mathbf{b} = (\mathbf{X}^\textsf{T} \mathbf{X})^{-1} \mathbf{X} \mathbf{y}\)</span>;</li>
<li>the standard errors <span class="math inline">\(s (b_i)\)</span> of the estimated coefficients are infinite and <em>t</em> statistics <span class="math inline">\(t_i = b_i / s (b_i)\)</span> are 0.</li>
</ul>
<p>This extreme case reflects a situation when one or more predictors are effectively redundant, for example when you include two variables <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> and their sum <span class="math inline">\(z = x + y\)</span> in a model, or use <em>ipsatized</em> scores that sum to a constant. More generally, collinearity refers to the case when there are very high <strong>multiple correlations</strong> among the predictors, such as <span class="math inline">\(R^2 (x_i | \text{other }x) \ge 0.9\)</span>. Note that you can’t tell simply by looking at the simple correlations. A large correlation <span class="math inline">\(r_{ij}\)</span> is <em>sufficient</em> for collinearity, but not <em>necessary</em> — you can have variables <span class="math inline">\(x_1, x_2, x_3\)</span> for which the pairwise correlation are low, but the multiple correlation is high.</p>
<p>The consequences are:</p>
<ul>
<li>The estimated coefficients have large standard errors, <span class="math inline">\(s(\hat{b_j})\)</span>. They are multiplied by the square root of the variance inflation factor, <span class="math inline">\(\sqrt{\text{VIF}}\)</span>, discussed below.</li>
<li>This deflates the <span class="math inline">\(t\)</span>-statistics, <span class="math inline">\(t = \hat{b_j} / s(\hat{b_j})\)</span> by the same factor.</li>
<li>Thus you may find a situation where an overall model is highly significant (large <span class="math inline">\(F\)</span>-statistic), while no (or few) of the individual predictors are. This is a puzzlement!</li>
<li>Beyond this, the least squares solution may have poor numerical accurracy <span class="citation" data-cites="Longley:1967">(<a href="90-references.html#ref-Longley:1967" role="doc-biblioref">Longley, 1967</a>)</span>, because the solution depends on the determinant <span class="math inline">\(|\,\mathbf{X}^\textsf{T} \mathbf{X}\,|\)</span>, which approaches 0 as multiple correlations increase.</li>
<li>As well, recall that the coefficients <span class="math inline">\(\hat{b}\)</span> are <strong>partial coefficients</strong>, meaning the estimated change <span class="math inline">\(\Delta y\)</span> in <span class="math inline">\(y\)</span> when <span class="math inline">\(x\)</span> changes by one unit <span class="math inline">\(\Delta x\)</span>, but <strong>holding all other variables constant</strong>. Then, the model may be trying to estimate something that does not occur in the data.</li>
</ul>
<section id="visualizing-collinearity" class="level3" data-number="8.1.1"><h3 data-number="8.1.1" class="anchored" data-anchor-id="visualizing-collinearity">
<span class="header-section-number">8.1.1</span> Visualizing collinearity</h3>
<p>Collinearity can be illustrated in data space for two predictors in terms of the stability of the regression plane for a linear model <code>Y = X1 + X2</code>. In <a href="#fig-collin-demo" class="quarto-xref">Figure&nbsp;<span>8.1</span></a> (adapted from <span class="citation" data-cites="Fox:2016:ARA">Fox (<a href="90-references.html#ref-Fox:2016:ARA" role="doc-biblioref">2016</a>)</span>, Fig. 13.2):</p>
<ol type="a">
<li><p>shows a case where <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span> are uncorrelated as can be seen in their scatter in the horizontal plane (<code>+</code> symbols). The regression plane is well-supported; a small change in Y for one observation won’t make much difference.</p></li>
<li><p>In panel (b), <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span> have a perfect correlation, <span class="math inline">\(r (x_1, x_2) = 1.0\)</span>. The regression plane is not unique; in fact there are an infinite number of planes that fit the data equally well. Note that, if all we care about is prediction (not the coefficients), we could use <span class="math inline">\(X_1\)</span> or <span class="math inline">\(X_2\)</span>, or both, or any weighted sum of them in a model and get the same predicted values.</p></li>
<li><p>Shows a typical case where there is a strong correlation between <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span>. The regression plane here is unique, but is not well determined. A small change in Y <strong>can</strong> make quite a difference in the fitted value or coefficients, depending on the values of <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span>. Where <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span> are far from their near linear relation in the botom plane, you can imagine that it is easy to tilt the plane substantially by a small change in <span class="math inline">\(Y\)</span>.</p></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-collin-demo" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-collin-demo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/collin-demo.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-collin-demo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.1: Effect of collinearity on the least squares regression plane. (a) Small correlation between predictors; (b) Perfect correlation ; (c) Very strong correlation. The black points show the data Y values, white points are the fitted values in the regression plane, and + signs represent the values of X1 and X2. <em>Source</em>: Adapted from <span class="citation" data-cites="Fox:2016:ARA">Fox (<a href="90-references.html#ref-Fox:2016:ARA" role="doc-biblioref">2016</a>)</span>, Fig. 13.2
</figcaption></figure>
</div>
</div>
</div>
</section><section id="data-space-and-beta-space" class="level3 page-columns page-full" data-number="8.1.2"><h3 data-number="8.1.2" class="anchored" data-anchor-id="data-space-and-beta-space">
<span class="header-section-number">8.1.2</span> Data space and <span class="math inline">\(\beta\)</span> space</h3>
<p>It is also useful to visualize collinearity by comparing the representation in <strong>data space</strong> with the analogous view of the confidence ellipses for coefficients in <strong>beta space</strong>. To do so, we generate data from a known model <span class="math inline">\(y = 3 x_1 + 3 x_2 + \epsilon\)</span> with <span class="math inline">\(\epsilon \sim \mathcal{N} (0, 100)\)</span> and various true correlations between <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>, <span class="math inline">\(\rho_{12} = (0, 0.8, 0.97)\)</span> <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Working file: <code>R/collin-data-beta.R</code></p>
</div></div><p>First, we use <code>MASS:mvrnorm()</code> to construct a list of data frames <code>XY</code> with specified values for the means and covariance matrices and a corresponding list of models, <code>mods</code>.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb2" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://www.stats.ox.ac.uk/pub/MASS4/">MASS</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://r-forge.r-project.org/projects/car/">car</a></span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">421</span><span class="op">)</span>            <span class="co"># reproducibility</span></span>
<span><span class="va">N</span> <span class="op">&lt;-</span> <span class="fl">200</span>                 <span class="co"># sample size</span></span>
<span><span class="va">mu</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">0</span><span class="op">)</span>            <span class="co"># means</span></span>
<span><span class="va">s</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">1</span><span class="op">)</span>             <span class="co"># standard deviations</span></span>
<span><span class="va">rho</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">0.8</span>, <span class="fl">0.97</span><span class="op">)</span>   <span class="co"># correlations</span></span>
<span><span class="va">beta</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">3</span><span class="op">)</span>          <span class="co"># true coefficients</span></span>
<span></span>
<span><span class="co"># Specify a covariance matrix, with standard deviations s[1], s[2] and correlation r</span></span>
<span><span class="va">Cov</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">s</span>, <span class="va">r</span><span class="op">)</span><span class="op">{</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">s</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>,    <span class="va">r</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/prod.html">prod</a></span><span class="op">(</span><span class="va">s</span><span class="op">)</span>,</span>
<span>         <span class="va">r</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/prod.html">prod</a></span><span class="op">(</span><span class="va">s</span><span class="op">)</span>, <span class="va">s</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span>, nrow <span class="op">=</span> <span class="fl">2</span>, ncol <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="co"># Generate a dataframe of X, y for each rho</span></span>
<span><span class="co"># Fit the model for each</span></span>
<span><span class="va">XY</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/vector.html">vector</a></span><span class="op">(</span>mode <span class="op">=</span><span class="st">"list"</span>, length <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">rho</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">mods</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/vector.html">vector</a></span><span class="op">(</span>mode <span class="op">=</span><span class="st">"list"</span>, length <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">rho</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_along</a></span><span class="op">(</span><span class="va">rho</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">r</span> <span class="op">&lt;-</span> <span class="va">rho</span><span class="op">[</span><span class="va">i</span><span class="op">]</span></span>
<span>  <span class="va">X</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/MASS/man/mvrnorm.html">mvrnorm</a></span><span class="op">(</span><span class="va">N</span>, <span class="va">mu</span>, Sigma <span class="op">=</span> <span class="fu">Cov</span><span class="op">(</span><span class="va">s</span>, <span class="va">r</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">X</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"x1"</span>, <span class="st">"x2"</span><span class="op">)</span></span>
<span>  <span class="va">y</span> <span class="op">&lt;-</span> <span class="va">beta</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span> <span class="op">*</span> <span class="va">X</span><span class="op">[</span>,<span class="fl">1</span><span class="op">]</span> <span class="op">+</span> <span class="va">beta</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span> <span class="op">*</span> <span class="va">X</span><span class="op">[</span>,<span class="fl">2</span><span class="op">]</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span>, <span class="fl">0</span>, <span class="fl">10</span><span class="op">)</span></span>
<span></span>
<span>  <span class="va">XY</span><span class="op">[[</span><span class="va">i</span><span class="op">]</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">X</span>, y<span class="op">=</span><span class="va">y</span><span class="op">)</span></span>
<span>  <span class="va">mods</span><span class="op">[[</span><span class="va">i</span><span class="op">]</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="va">x1</span> <span class="op">+</span> <span class="va">x2</span>, data<span class="op">=</span><span class="va">XY</span><span class="op">[[</span><span class="va">i</span><span class="op">]</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="op">}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The estimated coefficients in these models are:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb3" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">coefs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span><span class="op">(</span><span class="va">mods</span>, <span class="va">coef</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">coefs</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Intercept"</span>, <span class="st">"b1"</span>, <span class="st">"b2"</span><span class="op">)</span></span>
<span><span class="va">coefs</span></span>
<span><span class="co">#&gt;             Intercept      b1    b2</span></span>
<span><span class="co">#&gt; (Intercept)      1.01 -0.0535 0.141</span></span>
<span><span class="co">#&gt; x1               3.18  3.4719 3.053</span></span>
<span><span class="co">#&gt; x2               1.68  2.9734 2.059</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then, we define a function to plot the data ellipse (<code><a href="https://rdrr.io/pkg/car/man/Ellipses.html">car::dataEllipse()</a></code>) for each data frame and confidence ellipse (<code><a href="https://rdrr.io/pkg/car/man/Ellipses.html">car::dataEllipse()</a></code>) in the corresponding fitted model. In this figure, I specify the x, y limits for each plot so that the relative sizes of these ellipses are comparable, so that variance inflation can be assesed visually.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb4" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">do_plots</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">XY</span>, <span class="va">mod</span>, <span class="va">r</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">X</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">as.matrix</a></span><span class="op">(</span><span class="va">XY</span><span class="op">[</span>, <span class="fl">1</span><span class="op">:</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/car/man/Ellipses.html">dataEllipse</a></span><span class="op">(</span><span class="va">X</span>,</span>
<span>              levels<span class="op">=</span> <span class="fl">0.95</span>,</span>
<span>              col <span class="op">=</span> <span class="st">"darkgreen"</span>,</span>
<span>              fill <span class="op">=</span> <span class="cn">TRUE</span>, fill.alpha <span class="op">=</span> <span class="fl">0.05</span>,</span>
<span>              xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">3</span>, <span class="fl">3</span><span class="op">)</span>,</span>
<span>              ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">3</span>, <span class="fl">3</span><span class="op">)</span>, asp <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/graphics/text.html">text</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">3</span>, <span class="fu"><a href="https://rdrr.io/r/base/bquote.html">bquote</a></span><span class="op">(</span><span class="va">rho</span> <span class="op">==</span> <span class="fu">.</span><span class="op">(</span><span class="va">r</span><span class="op">)</span><span class="op">)</span>, cex <span class="op">=</span> <span class="fl">2</span>, pos <span class="op">=</span> <span class="cn">NULL</span><span class="op">)</span></span>
<span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/car/man/Ellipses.html">confidenceEllipse</a></span><span class="op">(</span><span class="va">mod</span>,</span>
<span>                    col <span class="op">=</span> <span class="st">"red"</span>,</span>
<span>                    fill <span class="op">=</span> <span class="cn">TRUE</span>, fill.alpha <span class="op">=</span> <span class="fl">0.1</span>,</span>
<span>                    xlab <span class="op">=</span> <span class="st">"x1 coefficient"</span>,</span>
<span>                    ylab <span class="op">=</span> <span class="st">"x2 coefficient"</span>,</span>
<span>                    xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">5</span>, <span class="fl">10</span><span class="op">)</span>,</span>
<span>                    ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">5</span>, <span class="fl">10</span><span class="op">)</span>,</span>
<span>                    asp <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/graphics/points.html">points</a></span><span class="op">(</span><span class="va">beta</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, <span class="va">beta</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>, pch <span class="op">=</span> <span class="st">"+"</span>, cex<span class="op">=</span><span class="fl">2</span><span class="op">)</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span><span class="op">(</span>v<span class="op">=</span><span class="fl">0</span>, h<span class="op">=</span><span class="fl">0</span>, lwd<span class="op">=</span><span class="fl">2</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="va">op</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mar <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4</span>,<span class="fl">4</span>,<span class="fl">1</span>,<span class="fl">1</span><span class="op">)</span><span class="op">+</span><span class="fl">0.1</span>,</span>
<span>          mfcol <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">3</span><span class="op">)</span>,</span>
<span>          cex.lab <span class="op">=</span> <span class="fl">1.5</span><span class="op">)</span></span>
<span></span>
<span><span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_along</a></span><span class="op">(</span><span class="va">rho</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu">do_plots</span><span class="op">(</span><span class="va">XY</span><span class="op">[[</span><span class="va">i</span><span class="op">]</span><span class="op">]</span>, <span class="va">mods</span><span class="op">[[</span><span class="va">i</span><span class="op">]</span><span class="op">]</span>, <span class="va">rho</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span><span class="va">op</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div id="fig-collin-data-beta" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-collin-data-beta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/fig-collin-data-beta-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-collin-data-beta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.2: 95% Ddata ellipses for x1, x2 and the corresponding 95% confidence ellipses for their coefficients. In the confidence ellipse plots, reference lines show the value (0,0) for the null hypothesis and “+” marks the true values for the coefficients. This figure adapts an example by John Fox (2022).
</figcaption></figure>
</div>
</div>
</div>
<p>Recall (Section #sec-data-beta) that the confidence ellipse for <span class="math inline">\((\beta_1, \beta_2)\)</span> is just a 90 degree rotation (and rescaling) of the data ellipse for <span class="math inline">\((x_1, x_2)\)</span>: it is wide (more variance) in any direction where the data ellipse is narrow.</p>
<p>The shadows of the confidence ellipses on the coordinate axes in <a href="#fig-collin-data-beta" class="quarto-xref">Figure&nbsp;<span>8.2</span></a> represent the standard errors of the coefficients, and get larger with increasing <span class="math inline">\(\rho\)</span>. This is the effect of variance inflation, described in the following section.</p>
</section></section><section id="sec-measure-collin" class="level2" data-number="8.2"><h2 data-number="8.2" class="anchored" data-anchor-id="sec-measure-collin">
<span class="header-section-number">8.2</span> Measuring collinearity</h2>
<section id="sec-vif" class="level3" data-number="8.2.1"><h3 data-number="8.2.1" class="anchored" data-anchor-id="sec-vif">
<span class="header-section-number">8.2.1</span> Variance inflation factors</h3>
<p>How can we measure the effect of collinearity? The essential idea is to compare, for each predictor the variance <span class="math inline">\(s^2 (\widehat{b_j})\)</span> that the coefficient that <span class="math inline">\(x_j\)</span> would have if it was totally unrelated to the other predictors to the actual variance it has in the given model.</p>
<p>For two predictors such as shown in <a href="#fig-collin-data-beta" class="quarto-xref">Figure&nbsp;<span>8.2</span></a> the sampling variance of <span class="math inline">\(x_1\)</span> can be expressed as</p>
<p><span class="math display">\[
s^2 (\widehat{b_1}) = \frac{MSE}{(n-1) \; s^2(x_1)} \; \times \; \left[ \frac{1}{1-r^2_{12}} \right]
\]</span> The first term here is the variance of <span class="math inline">\(b_1\)</span> when the two predictors are uncorrelated. The term in brackets represents the <strong>variance inflation factor</strong> <span class="citation" data-cites="Marquardt:1970">(<a href="90-references.html#ref-Marquardt:1970" role="doc-biblioref">Marquardt, 1970</a>)</span>, the amount by which the variance of the coefficient is multiplied as a consequence of the correlation <span class="math inline">\(r_{12}\)</span> of the predictors. As <span class="math inline">\(r_{12} \rightarrow 1\)</span>, the variances approaches infinity.</p>
<p>More generally, with any number of predictors, this relation has a similar form, replacing the simple correlation <span class="math inline">\(r_{12}\)</span> with the multiple correlation predicting <span class="math inline">\(x_j\)</span> from all others,</p>
<p><span class="math display">\[
s^2 (\widehat{b_j}) = \frac{MSE}{(n-1) \; s^2(x_j)} \; \times \; \left[ \frac{1}{1-R^2_{j | \text{others}}} \right]
\]</span> So, we have that the variance inflation factors are:</p>
<p><span class="math display">\[
\text{VIF}_j = \frac{1}{1-R^2_{j \,|\, \text{others}}}
\]</span> In practice, it is often easier to think in terms of the square root, <span class="math inline">\(\sqrt{\text{VIF}_j}\)</span> as the multiplier of the standard errors. The denominator, <span class="math inline">\(1-R^2_{j | \text{others}}\)</span> is sometimes called <strong>tolerance</strong>, a term I don’t find particularly useful.</p>
<p>For the cases shown in <a href="#fig-collin-data-beta" class="quarto-xref">Figure&nbsp;<span>8.2</span></a> the VIFs and their square roots are:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb5" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">vifs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span><span class="op">(</span><span class="va">mods</span>, <span class="fu">car</span><span class="fu">::</span><span class="va"><a href="https://rdrr.io/pkg/car/man/vif.html">vif</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">vifs</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">"rho:"</span>, <span class="va">rho</span><span class="op">)</span></span>
<span><span class="va">vifs</span></span>
<span><span class="co">#&gt;    rho: 0 rho: 0.8 rho: 0.97</span></span>
<span><span class="co">#&gt; x1      1     3.09      18.6</span></span>
<span><span class="co">#&gt; x2      1     3.09      18.6</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">vifs</span><span class="op">)</span></span>
<span><span class="co">#&gt;    rho: 0 rho: 0.8 rho: 0.97</span></span>
<span><span class="co">#&gt; x1      1     1.76      4.31</span></span>
<span><span class="co">#&gt; x2      1     1.76      4.31</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that when there are terms in the model with more than one df, such as education with four levels (and hence 3 df) or a polynomial term specified as <code>poly(x, 3)</code>, the standard VIF calculation gives results that vary with how those terms are coded in the model. <span class="citation" data-cites="FoxMonette:92">Fox &amp; Monette (<a href="90-references.html#ref-FoxMonette:92" role="doc-biblioref">1992</a>)</span> define <em>generalized</em>, GVIFs as the inflation in the squared area of the confidence ellipse for the coefficients of such terms, relative to what would be obtained with uncorrelated data. Visually, this can be seen by comparing the areas of the ellipses in the bottom row of <a href="#fig-collin-data-beta" class="quarto-xref">Figure&nbsp;<span>8.2</span></a>. Because the magnitude of the GVIF increases with the number of degrees of freedom for the set of parameters, Fox &amp; Monette suggest the analog <span class="math inline">\(\sqrt{\text{GVIF}^{1/2 \text{df}}}\)</span> as the measure of impact on standard errors.</p>
<p><strong>Example</strong>: This example uses the <code>cars</code> dataset in the <code>VisCollin</code> package containing various measures of size and performance on 406 models of automobiles from 1982. Interest is focused on predicting gas mileage, <code>mpg</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb6" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="va">cars</span>, package <span class="op">=</span> <span class="st">"VisCollin"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">cars</span><span class="op">)</span></span>
<span><span class="co">#&gt; 'data.frame':    406 obs. of  10 variables:</span></span>
<span><span class="co">#&gt;  $ make    : Factor w/ 30 levels "amc","audi","bmw",..: 6 4 22 1 12 12 6 22 23 1 ...</span></span>
<span><span class="co">#&gt;  $ model   : chr  "chevelle" "skylark" "satellite" "rebel" ...</span></span>
<span><span class="co">#&gt;  $ mpg     : num  18 15 18 16 17 15 14 14 14 15 ...</span></span>
<span><span class="co">#&gt;  $ cylinder: int  8 8 8 8 8 8 8 8 8 8 ...</span></span>
<span><span class="co">#&gt;  $ engine  : num  307 350 318 304 302 429 454 440 455 390 ...</span></span>
<span><span class="co">#&gt;  $ horse   : int  130 165 150 150 140 198 220 215 225 190 ...</span></span>
<span><span class="co">#&gt;  $ weight  : int  3504 3693 3436 3433 3449 4341 4354 4312 4425 3850 ...</span></span>
<span><span class="co">#&gt;  $ accel   : num  12 11.5 11 12 10.5 10 9 8.5 10 8.5 ...</span></span>
<span><span class="co">#&gt;  $ year    : int  70 70 70 70 70 70 70 70 70 70 ...</span></span>
<span><span class="co">#&gt;  $ origin  : Factor w/ 3 levels "Amer","Eur","Japan": 1 1 1 1 1 1 1 1 1 1 ...</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We fit a model predicting gas mileage (<code>mpg</code>) from the number of cylinders, engine displacement, horsepower, weight, time to accelerate from 0 – 60 mph and model year (1970–1982). Perhaps surprisingly, only <code>weight</code> and <code>year</code> appear to significantly predict gas mileage. What’s going on here?</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb7" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">cars.mod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span> <span class="op">(</span><span class="va">mpg</span> <span class="op">~</span> <span class="va">cylinder</span> <span class="op">+</span> <span class="va">engine</span> <span class="op">+</span> <span class="va">horse</span> <span class="op">+</span> <span class="va">weight</span> <span class="op">+</span> <span class="va">accel</span> <span class="op">+</span> <span class="va">year</span>, </span>
<span>                data<span class="op">=</span><span class="va">cars</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/car/man/Anova.html">Anova</a></span><span class="op">(</span><span class="va">cars.mod</span><span class="op">)</span></span>
<span><span class="co">#&gt; Anova Table (Type II tests)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Response: mpg</span></span>
<span><span class="co">#&gt;           Sum Sq  Df F value Pr(&gt;F)    </span></span>
<span><span class="co">#&gt; cylinder      12   1    0.99   0.32    </span></span>
<span><span class="co">#&gt; engine        13   1    1.09   0.30    </span></span>
<span><span class="co">#&gt; horse          0   1    0.00   0.98    </span></span>
<span><span class="co">#&gt; weight      1214   1  102.84 &lt;2e-16 ***</span></span>
<span><span class="co">#&gt; accel          8   1    0.70   0.40    </span></span>
<span><span class="co">#&gt; year        2419   1  204.99 &lt;2e-16 ***</span></span>
<span><span class="co">#&gt; Residuals   4543 385                   </span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We check the variance inflation factors, using <code><a href="https://rdrr.io/pkg/car/man/vif.html">car::vif()</a></code>. We see that most predictors have very high VIFs, indicating moderately severe multicollinearity.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb8" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/car/man/vif.html">vif</a></span><span class="op">(</span><span class="va">cars.mod</span><span class="op">)</span></span>
<span><span class="co">#&gt; cylinder   engine    horse   weight    accel     year </span></span>
<span><span class="co">#&gt;    10.63    19.64     9.40    10.73     2.63     1.24</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/car/man/vif.html">vif</a></span><span class="op">(</span><span class="va">cars.mod</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; cylinder   engine    horse   weight    accel     year </span></span>
<span><span class="co">#&gt;     3.26     4.43     3.07     3.28     1.62     1.12</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>According to <span class="math inline">\(\sqrt{\text{VIF}}\)</span>, the standard error of <code>cylinder</code> has been multiplied by 3.26 and it’s <span class="math inline">\(t\)</span>-value divided by this number, compared with the case when all predictors are uncorrelated. <code>engine</code>, <code>horse</code> and <code>weight</code> suffer a similar fate.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Connection with inverse of correlation matrix">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Connection with inverse of correlation matrix
</div>
</div>
<div class="callout-body-container callout-body">
<p>In the linear regression model with standardized predictors, the covariance matrix of the estimated intercept-excluding parameter vector <span class="math inline">\(\mathbf{b}^\star\)</span> has the simpler form, <span class="math display">\[
\mathcal{V} (\mathbf{b}^\star) = \frac{\sigma^2}{n-1} \mathbf{R}^{-1}_{X} \; .
\]</span> where <span class="math inline">\(\mathbf{R}_{X}\)</span> is the correlation matrix among the predictors. It can then be seen that the VIF<span class="math inline">\(_j\)</span> are just the diagonal entries of <span class="math inline">\(\mathbf{R}^{-1}_{X}\)</span>.</p>
<p>More generally, the matrix <span class="math inline">\(\mathbf{R}^{-1}_{X} = (r^{ij})\)</span>, when standardized to a correlation matrix as <span class="math inline">\(-r^{ij} / \sqrt{r^{ii} \; r^{jj}}\)</span> gives the matrix of all partial correlations, <span class="math inline">\(r_{ij \,|\, \textrm{others}}\)</span>. }</p>
</div>
</div>
</section><section id="sec-colldiag" class="level3" data-number="8.2.2"><h3 data-number="8.2.2" class="anchored" data-anchor-id="sec-colldiag">
<span class="header-section-number">8.2.2</span> Collinearity diagnostics</h3>
<p>OK, we now know that large VIF<span class="math inline">\(_j\)</span> indicate predictor coefficients whose estimation is degraded due to large <span class="math inline">\(R^2_{j \,|\, \text{others}}\)</span>. But for this to be useful, we need to determine:</p>
<ul>
<li>how many dimensions in the space of the predictors are associated with nearly collinear relations?</li>
<li>which predictors are most strongly implicated in each of these?</li>
</ul>
<p>Answers to these questions are provided using measures developed by Belsley and colleagues <span class="citation" data-cites="Belsley-etal:80 Belsley:91a">(<a href="90-references.html#ref-Belsley-etal:80" role="doc-biblioref">Belsley et al., 1980</a>; <a href="90-references.html#ref-Belsley:91a" role="doc-biblioref">Belsley, 1991</a>)</span>. These measures are based on the eigenvalues <span class="math inline">\(\lambda_1, \lambda_2, \dots \lambda_p\)</span> of the correlation matrix <span class="math inline">\(R_{X}\)</span> of the predictors (preferably centered and scaled, and not including the constant term for the intercept), and the corresponding eigenvectors in the columns of <span class="math inline">\(\mathbf{V}_{p \times p}\)</span>, given by the the eigen decomposition <span class="math display">\[
\mathbf{R}_{X} = \mathbf{V} \mathbf{\Lambda} \mathbf{V}^\textsf{T}
\]</span> By elementary matrix algebra, the eigen decomposition of <span class="math inline">\(\mathbf{R}_{XX}^{-1}\)</span> is then <span id="eq-rxinv-eigen"><span class="math display">\[
\mathbf{R}_{X}^{-1} = \mathbf{V} \mathbf{\Lambda}^{-1} \mathbf{V}^\textsf{T} \; ,
\tag{8.1}\]</span></span> so, <span class="math inline">\(\mathbf{R}_{X}\)</span> and <span class="math inline">\(\mathbf{R}_{XX}^{-1}\)</span> have the same eigenvectors, and the eigenvalues of <span class="math inline">\(\mathbf{R}_{X}^{-1}\)</span> are just <span class="math inline">\(\lambda_i^{-1}\)</span>. Using <a href="#eq-rxinv-eigen" class="quarto-xref">Equation&nbsp;<span>8.1</span></a>, the variance inflation factors may be expressed as <span class="math display">\[
\text{VIF}_j = \sum_{k=1}^p \frac{V^2_{jk}}{\lambda_k} \; ,
\]</span> which shows that only the <em>small</em> eigenvalues contribute to variance inflation, but only for those predictors that have large eigenvector coefficients on those small components. These facts lead to the following diagnostic statistics for collinearity:</p>
<ul>
<li>
<p><strong>Condition indices</strong>: The smallest of the eigenvalues, those for which <span class="math inline">\(\lambda_j \approx 0\)</span>, indicate collinearity and the number of small values indicates the number of near collinear relations. Because the sum of the eigenvalues, <span class="math inline">\(\Sigma \lambda_i = p\)</span> increases with the number of predictors <span class="math inline">\(p\)</span>, it is useful to scale them all in relation to the largest. This leads to <em>condition indices</em>, defined as <span class="math inline">\(\kappa_j = \sqrt{ \lambda_1 / \lambda_j}\)</span>. These have the property that the resulting numbers have common interpretations regardless of the number of predictors.</p>
<ul>
<li>For completely uncorrelated predictors, all <span class="math inline">\(\kappa_j = 1\)</span>.</li>
<li>
<span class="math inline">\(\kappa_j \rightarrow \infty\)</span> as any <span class="math inline">\(\lambda_k \rightarrow 0\)</span>.</li>
</ul>
</li>
<li><p><strong>Variance decomposition proportions</strong>: Large VIFs indicate variables that are involved in <em>some</em> nearly collinear relations, but they don’t indicate <em>which</em> other variable(s) each is involved with. For this purpose, <span class="citation" data-cites="Belsley-etal:80">Belsley et al. (<a href="90-references.html#ref-Belsley-etal:80" role="doc-biblioref">1980</a>)</span> and <span class="citation" data-cites="Belsley:91a">Belsley (<a href="90-references.html#ref-Belsley:91a" role="doc-biblioref">1991</a>)</span> proposed calculation of the proportions of variance of each variable associated with each principal component as a decomposition of the coefficient variance for each dimension.</p></li>
</ul>
<p>These measures can be calculated using <code><a href="https://rdrr.io/pkg/VisCollin/man/colldiag.html">VisCollin::colldiag()</a></code>. For the current model, the usual display contains both the condition indices and variance proportions. However, even for a small example, it is often difficult to know what numbers to pay attention to.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb9" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="op">(</span><span class="va">cd</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/VisCollin/man/colldiag.html">colldiag</a></span><span class="op">(</span><span class="va">cars.mod</span>, center<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; Condition</span></span>
<span><span class="co">#&gt; Index    Variance Decomposition Proportions</span></span>
<span><span class="co">#&gt;           cylinder engine horse weight accel year </span></span>
<span><span class="co">#&gt; 1   1.000 0.005    0.003  0.005 0.004  0.009 0.010</span></span>
<span><span class="co">#&gt; 2   2.252 0.004    0.002  0.000 0.007  0.022 0.787</span></span>
<span><span class="co">#&gt; 3   2.515 0.004    0.001  0.002 0.010  0.423 0.142</span></span>
<span><span class="co">#&gt; 4   5.660 0.309    0.014  0.306 0.087  0.063 0.005</span></span>
<span><span class="co">#&gt; 5   8.342 0.115    0.000  0.654 0.715  0.469 0.052</span></span>
<span><span class="co">#&gt; 6  10.818 0.563    0.981  0.032 0.176  0.013 0.004</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><span class="citation" data-cites="Belsley:91a">Belsley (<a href="90-references.html#ref-Belsley:91a" role="doc-biblioref">1991</a>)</span> recommends that the sources of collinearity be diagnosed (a) only for those components with large <span class="math inline">\(\kappa_j\)</span>, and (b) for those components for which the variance proportion is large (say, <span class="math inline">\(\ge 0.5\)</span>) on <em>two</em> or more predictors. The print method for <code>"colldiag"</code> objects has a <code>fuzz</code> argument controlling this.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb10" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">cd</span>, fuzz <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span></span>
<span><span class="co">#&gt; Condition</span></span>
<span><span class="co">#&gt; Index    Variance Decomposition Proportions</span></span>
<span><span class="co">#&gt;           cylinder engine horse weight accel year </span></span>
<span><span class="co">#&gt; 1   1.000  .        .      .     .      .     .   </span></span>
<span><span class="co">#&gt; 2   2.252  .        .      .     .      .    0.787</span></span>
<span><span class="co">#&gt; 3   2.515  .        .      .     .      .     .   </span></span>
<span><span class="co">#&gt; 4   5.660  .        .      .     .      .     .   </span></span>
<span><span class="co">#&gt; 5   8.342  .        .     0.654 0.715   .     .   </span></span>
<span><span class="co">#&gt; 6  10.818 0.563    0.981   .     .      .     .</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The mystery is solved, if you can read that table with these recommendations in mind. There are two nearly collinear relations among the predictors, corresponding to the two smallest dimensions.</p>
<ul>
<li>Dimension 5 reflects the high correlation between horsepower and weight,</li>
<li>Dimension 6 reflects the high correlation between number of cylinders and engine displacement.</li>
</ul>
<p>Note that the high variance proportion for <code>year</code> (0.787) on the second component creates no problem and should be ignored because (a) the condition index is low and (b) it shares nothing with other predictors.</p>
</section><section id="tableplots" class="level3" data-number="8.2.3"><h3 data-number="8.2.3" class="anchored" data-anchor-id="tableplots">
<span class="header-section-number">8.2.3</span> Tableplots</h3>
<p>The default tabular display of condition indices and variance proportions from <code><a href="https://rdrr.io/pkg/VisCollin/man/colldiag.html">colldiag()</a></code> is what triggered the comparison to “Where’s Waldo”. It suffers from the fact that the important information — (a) how many Waldos? (b) where are they hiding — is disguised by being embedded in a sea of mostly irrelevant numbers. The simple option of using a principled <code>fuzz</code> factor helps considerably, but not entirely.</p>
<p>The simplified tabular display above can be improved to make the patterns of collinearity more visually apparent and to signify warnings directly to the eyes. A <strong>tableplot</strong> <span class="citation" data-cites="Kwan-etal:2009">(<a href="90-references.html#ref-Kwan-etal:2009" role="doc-biblioref">Kwan et al., 2009</a>)</span> is a semi-graphic display that presents numerical information in a table using shapes proportional to the value in a cell and other visual attributes (shape type, color fill, and so forth) to encode other information.</p>
<p>For collinearity diagnostics, these show:</p>
<ul>
<li><p>the condition indices, using using <em>squares</em> whose background color is red for condition indices &gt; 10, green for values &gt; 5 and green otherwise, reflecting danger, warning and OK respectively. The value of the condition index is encoded within this using a white square whose side is proportional to the value (up to some maximum value, <code>cond.max</code> that fills the cell).</p></li>
<li><p>Variance decomposition proportions are shown by filled <em>circles</em> whose radius is proportional to those values and are filled (by default) with shades ranging from white through pink to red. Rounded values of those diagnostics are printed in the cells.</p></li>
</ul>
<p>The tableplot below (<a href="#fig-cars-tableplot" class="quarto-xref">Figure&nbsp;<span>8.3</span></a>) encodes all the information from the values of <code><a href="https://rdrr.io/pkg/VisCollin/man/colldiag.html">colldiag()</a></code> printed above (but using <code>prop.col</code> color breaks such that variance proportions &lt; 0.3 are shaded white). The visual message is that one should attend to collinearities with large condition indices <strong>and</strong> large variance proportions implicating two or more predictors.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb11" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/VisCollin/man/tableplot.html">tableplot</a></span><span class="op">(</span><span class="va">cd</span>, title <span class="op">=</span> <span class="st">"Tableplot of cars data"</span>, cond.max <span class="op">=</span> <span class="fl">30</span> <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-cars-tableplot" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-cars-tableplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/fig-cars-tableplot-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cars-tableplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.3: Tableplot of condition indices and variance proportions for the Cars data. In column 1, the square symbols are scaled relative to a maximum condition index of 30. In the remaining columns, variance proportions (times 100) are shown as circles scaled relative to a maximum of 100.
</figcaption></figure>
</div>
</div>
</div>
</section><section id="collinearity-biplots" class="level3" data-number="8.2.4"><h3 data-number="8.2.4" class="anchored" data-anchor-id="collinearity-biplots">
<span class="header-section-number">8.2.4</span> Collinearity biplots</h3>
<p>As we have seen, the collinearity diagnostics are all functions of the eigenvalues and eigenvectors of the correlation matrix of the predictors in the regression model, or alternatively, the SVD of the <span class="math inline">\(\mathbf{X}\)</span> matrix in the linear model (excluding the constant). The standard biplot <span class="citation" data-cites="Gabriel:71 GowerHand:96">(<a href="90-references.html#ref-Gabriel:71" role="doc-biblioref">Gabriel, 1971</a>; <a href="90-references.html#ref-GowerHand:96" role="doc-biblioref">Gower &amp; Hand, 1996</a>)</span> (see: <a href="04-pca-biplot.html#sec-biplot" class="quarto-xref"><span>Section 4.3</span></a>) can be regarded as a multivariate analog of a scatterplot, obtained by projecting a multivariate sample into a low-dimensional space (typically of 2 or 3 dimensions) accounting for the greatest variance in the data.</p>
<p>However the standard biplot is less useful for visualizing the relations among the predictors that lead to nearly collinear relations. Instead, biplots of the <strong>smallest dimensions</strong> show these relations directly, and can show other features of the data as well, such as outliers and leverage points. We use <code>prcomp(X, scale.=TRUE)</code> to obtain the PCA of the correlation matrix of the predictors:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb12" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">cars.X</span> <span class="op">&lt;-</span> <span class="va">cars</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/MASS/man/lm.ridge.html">select</a></span><span class="op">(</span><span class="fu"><a href="https://tidyselect.r-lib.org/reference/where.html">where</a></span><span class="op">(</span><span class="va">is.numeric</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/MASS/man/lm.ridge.html">select</a></span><span class="op">(</span><span class="op">-</span><span class="va">mpg</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">tidyr</span><span class="fu">::</span><span class="fu"><a href="https://tidyr.tidyverse.org/reference/drop_na.html">drop_na</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">cars.pca</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/prcomp.html">prcomp</a></span><span class="op">(</span><span class="va">cars.X</span>, scale. <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">cars.pca</span></span>
<span><span class="co">#&gt; Standard deviations (1, .., p=6):</span></span>
<span><span class="co">#&gt; [1] 2.070 0.911 0.809 0.367 0.245 0.189</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Rotation (n x k) = (6 x 6):</span></span>
<span><span class="co">#&gt;             PC1     PC2    PC3    PC4     PC5     PC6</span></span>
<span><span class="co">#&gt; cylinder -0.454 -0.1869  0.168 -0.659 -0.2711 -0.4725</span></span>
<span><span class="co">#&gt; engine   -0.467 -0.1628  0.134 -0.193 -0.0109  0.8364</span></span>
<span><span class="co">#&gt; horse    -0.462 -0.0177 -0.123  0.620 -0.6123 -0.1067</span></span>
<span><span class="co">#&gt; weight   -0.444 -0.2598  0.278  0.350  0.6860 -0.2539</span></span>
<span><span class="co">#&gt; accel     0.330 -0.2098  0.865  0.143 -0.2774  0.0337</span></span>
<span><span class="co">#&gt; year      0.237 -0.9092 -0.335  0.025 -0.0624  0.0142</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The standard deviations above are the square roots <span class="math inline">\(\sqrt{\lambda_j}\)</span> of the eigenvalues of the correlation matrix, and are returned in the <code>sdev</code> component of the <code>"prcomp"</code> object. The eigenvectors are returned in the <code>rotation</code> component, whose directions are arbitrary. Because we are interested in seeing the relative magnitude of variable vectors, we are free to multiply them by any constant to make them more visible in relation to the scores for the cars.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb13" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">cars.pca</span><span class="op">$</span><span class="va">rotation</span> <span class="op">&lt;-</span> <span class="op">-</span><span class="fl">2.5</span> <span class="op">*</span> <span class="va">cars.pca</span><span class="op">$</span><span class="va">rotation</span>    <span class="co"># reflect &amp; scale the variable vectors</span></span>
<span></span>
<span><span class="va">ggp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/factoextra/man/fviz_pca.html">fviz_pca_biplot</a></span><span class="op">(</span></span>
<span>  <span class="va">cars.pca</span>,</span>
<span>  axes <span class="op">=</span> <span class="fl">6</span><span class="op">:</span><span class="fl">5</span>,</span>
<span>  geom <span class="op">=</span> <span class="st">"point"</span>,</span>
<span>  col.var <span class="op">=</span> <span class="st">"blue"</span>,</span>
<span>  labelsize <span class="op">=</span> <span class="fl">5</span>,</span>
<span>  pointsize <span class="op">=</span> <span class="fl">1.5</span>,</span>
<span>  arrowsize <span class="op">=</span> <span class="fl">1.5</span>,</span>
<span>  addEllipses <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>  ggtheme <span class="op">=</span> <span class="fu">ggplot2</span><span class="fu">::</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span>base_size <span class="op">=</span> <span class="fl">14</span><span class="op">)</span>,</span>
<span>  title <span class="op">=</span> <span class="st">"Collinearity biplot for cars data"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># add point labels for outlying points</span></span>
<span><span class="va">dsq</span> <span class="op">&lt;-</span> <span class="fu">heplots</span><span class="fu">::</span><span class="fu"><a href="https://friendly.github.io/heplots/reference/Mahalanobis.html">Mahalanobis</a></span><span class="op">(</span><span class="va">cars.pca</span><span class="op">$</span><span class="va">x</span><span class="op">[</span>, <span class="fl">6</span><span class="op">:</span><span class="fl">5</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="va">scores</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="va">cars.pca</span><span class="op">$</span><span class="va">x</span><span class="op">[</span>, <span class="fl">6</span><span class="op">:</span><span class="fl">5</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="va">scores</span><span class="op">$</span><span class="va">name</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">scores</span><span class="op">)</span></span>
<span></span>
<span><span class="va">ggp</span> <span class="op">+</span> <span class="fu"><a href="https://ggrepel.slowkow.com/reference/geom_text_repel.html">geom_text_repel</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">scores</span><span class="op">[</span><span class="va">dsq</span> <span class="op">&gt;</span> <span class="fu"><a href="https://rdrr.io/r/stats/Chisquare.html">qchisq</a></span><span class="op">(</span><span class="fl">0.95</span>, df <span class="op">=</span> <span class="fl">6</span><span class="op">)</span>,<span class="op">]</span>,</span>
<span>                <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">PC6</span>,</span>
<span>                    y <span class="op">=</span> <span class="va">PC5</span>,</span>
<span>                    label <span class="op">=</span> <span class="va">name</span><span class="op">)</span>,</span>
<span>                vjust <span class="op">=</span> <span class="op">-</span><span class="fl">0.5</span>,</span>
<span>                size <span class="op">=</span> <span class="fl">5</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-cars-collin-biplot" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-cars-collin-biplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/fig-cars-collin-biplot-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cars-collin-biplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.4: Collinearity biplot of the Cars data, showing the last two dimensions. The projections of the variable vectors on the coordinate axes are proportional to their variance proportions. To reduce graphic clutter, only the most outlying observations in predictor space are identified by case labels. An extreme outlier (case 20) appears in the lower left corner.
</figcaption></figure>
</div>
</div>
</div>
<p>As with the tabular display of variance proportions, Waldo is hiding in the dimensions associated with the smallest eigenvalues (largest condition indices).<br>
As well, it turns out that outliers in the predictor space (also high leverage observations) can often be seen as observations far from the centroid in the space of the smallest principal components.</p>
<p>The projections of the variable vectors in <a href="#fig-cars-collin-biplot" class="quarto-xref">Figure&nbsp;<span>8.4</span></a> on the Dimension 5 and Dimension 6 axes are proportional to their variance proportions shown above. The relative lengths of these variable vectors can be considered to indicate the extent to which each variable contributes to collinearity for these two near-singular dimensions.</p>
<p>Thus, we see again that Dimension 6 is largely determined by <code>engine</code> size, with a substantial (negative) relation to <code>cylinder</code>. Dimension 5 has its’ strongest relations to <code>weight</code> and <code>horse</code>.</p>
<p>Moreover, there is one observation, #20, that stands out as an outlier in predictor space, far from the centroid. It turns out that this vehicle, a Buick Estate wagon, is an early-year (1970) American behemoth, with an 8-cylinder, 455 cu. in, 225 horse-power engine, and able to go from 0 to 60 mph in 10 sec. (Its MPG is only slightly under-predicted from the regression model, however.)</p>
</section></section><section id="sec-remedies" class="level2" data-number="8.3"><h2 data-number="8.3" class="anchored" data-anchor-id="sec-remedies">
<span class="header-section-number">8.3</span> Remedies for collinearity: What can I do?</h2>
<p>Collinearity is often a <strong>data</strong> problem, for which there is no magic cure. Nevertheless there are some general guidelines and useful techniques to address this problem.</p>
<ul>
<li><p><strong>Pure prediction</strong>: If we are only interested in predicting / explaining an outcome, and not the model coefficients or which are “significant”, collinearity can be largely ignored. The fitted values are unaffected by collinearity, even in the case of perfect collinearity as shown in <a href="#fig-collin-demo" class="quarto-xref">Figure&nbsp;<span>8.1</span></a> (b).</p></li>
<li>
<p><strong>structural collinearity</strong>: Sometimes collinearity results from structural relations among the variables that relate to how they have been defined.</p>
<ul>
<li><p>For example, polynomial terms, like <span class="math inline">\(x, x^2, x^3\)</span> or interaction terms like <span class="math inline">\(x_1, x_2, x_1 * x_2\)</span> are necessarily correlated. A simple cure is to <em>center</em> the predictors at their means, using <span class="math inline">\(x - \bar{x}, (x - \bar{x})^2, (x - \bar{x})^3\)</span> or <span class="math inline">\((x_1 - \bar{x}_1), (x_2 - \bar{x}_2), (x_1 - \bar{x}_1) * (x_2 - \bar{x}_2)\)</span>. Centering removes the spurious ill-conditioning, thus reducing the VIFs. Note that in polynomial models, using <code>y ~ poly(x, 3)</code> to specify a cubic model generates <em>orthogonal</em> (uncorrelated) regressors, whereas in <code>y ~ x + I(x^2) + I(x^3)</code> the terms have built-in correlations.</p></li>
<li><p>When some predictors share a common cause, as in GNP or population in time-series or cross-national data, you can reduce collinearity by re-defining predictors to reflect <em>per capita measures</em>. In a related example with sports data, when you have cumulative totals (e.g., runs, hits, homeruns in baseball) for players over years, expressing these measures as <em>per year</em> will reduce the common effect of longevity on these measures.</p></li>
</ul>
</li>
<li>
<p><strong>Model re-specification</strong>:</p>
<ul>
<li><p>Drop one or more regressors that have a high VIF if they are not deemed to be essential</p></li>
<li><p>Replace highly correlated regressors with linear combination(s) of them. For example, two related variables, <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span> can be replaced without any loss of information by replacing them with their sum and difference, <span class="math inline">\(z_1 = x_1 + x_2\)</span> and <span class="math inline">\(z_2 = x_1 - x_2\)</span>. For example, in a dataset on fitness, we may have correlated predictors of resting pulse rate and pulse rate while running. Transforming these to average pulse rate and their difference gives new variables which are interpretable and less correlated.</p></li>
</ul>
</li>
<li>
<p><strong>Statistical remedies</strong>:</p>
<ul>
<li><p>Transform the predictors <span class="math inline">\(\mathbf{X}\)</span> to uncorrelated principal component scores <span class="math inline">\(\mathbf{Z} = \mathbf{X} \mathbf{V}\)</span>, and regress <span class="math inline">\(\mathbf{y}\)</span> on <span class="math inline">\(\mathbf{Z}\)</span>. These will have the identical overall model fit without loss of information. A related technique is <em>incomplete</em> principal components regression, where some of the smallest dimensions (those causing collinearity) are omitted from the model. The trade-off is that it may be more difficult to interpret what the model means, but this can be countered with a biplot, showing the projections of the original variables into the reduced space of the principal components.</p></li>
<li><p>use <strong>regularization methods</strong> such as ridge regression and lasso, which correct for collinearity by introducing shrinking coefficients towards 0, introducing a small amount of bias, . See the <a href="https://CRAN.R-project.org/package=genridge">genridge</a> package and its <a href="https://friendly.github.io/genridge/"><code>pkgdown</code> documentation</a> for visualization methods.</p></li>
<li><p>use Bayesian regression; if multicollinearity prevents a regression coefficient from being estimated precisely, then a prior on that coefficient will help to reduce its posterior variance.</p></li>
</ul>
</li>
</ul>
<p><strong>Example</strong>: Centering</p>
<p>To illustrate the effect of centering a predictor in a polynomial model, we generate a perfect quadratic relationship, <span class="math inline">\(y = x^2\)</span> and consider the correlations of <span class="math inline">\(y\)</span> with <span class="math inline">\(x\)</span> and with <span class="math inline">\((x - \bar{x})^2\)</span>. The correlation of <span class="math inline">\(y\)</span> with <span class="math inline">\(x\)</span> is 0.97, while the correlation of <span class="math inline">\(y\)</span> with <span class="math inline">\((x - \bar{x})^2\)</span> is zero.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb14" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">x</span> <span class="op">&lt;-</span> <span class="fl">1</span><span class="op">:</span><span class="fl">20</span></span>
<span><span class="va">y1</span> <span class="op">&lt;-</span> <span class="va">x</span><span class="op">^</span><span class="fl">2</span></span>
<span><span class="va">y2</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">x</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span></span>
<span><span class="va">XY</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">y1</span>, <span class="va">y2</span><span class="op">)</span></span>
<span></span>
<span><span class="op">(</span><span class="va">R</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">XY</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt;        x    y1    y2</span></span>
<span><span class="co">#&gt; x  1.000 0.971 0.000</span></span>
<span><span class="co">#&gt; y1 0.971 1.000 0.238</span></span>
<span><span class="co">#&gt; y2 0.000 0.238 1.000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The effect of centering here is remove the linear association in what is a purely quadratic relationship, as can be seen by plotting <code>y1</code> and <code>y2</code> against <code>x</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb15" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">r1</span> <span class="op">&lt;-</span> <span class="va">R</span><span class="op">[</span><span class="fl">1</span>, <span class="fl">2</span><span class="op">]</span></span>
<span><span class="va">r2</span> <span class="op">&lt;-</span> <span class="va">R</span><span class="op">[</span><span class="fl">1</span>, <span class="fl">3</span><span class="op">]</span></span>
<span></span>
<span><span class="va">gg1</span> <span class="op">&lt;-</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">XY</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">x</span>, y <span class="op">=</span> <span class="va">y1</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">3</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, formula <span class="op">=</span> <span class="va">y</span><span class="op">~</span><span class="va">x</span>, linewidth <span class="op">=</span> <span class="fl">2</span>, se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"X"</span>, y <span class="op">=</span> <span class="st">"Y"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span>base_size <span class="op">=</span> <span class="fl">16</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/annotate.html">annotate</a></span><span class="op">(</span><span class="st">"text"</span>, x <span class="op">=</span> <span class="fl">5</span>, y <span class="op">=</span> <span class="fl">350</span>, size <span class="op">=</span> <span class="fl">6</span>,</span>
<span>           label <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">"X Uncentered\nr ="</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">r1</span>, <span class="fl">3</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">gg2</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">XY</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">x</span>, y <span class="op">=</span> <span class="va">y2</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">3</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, formula <span class="op">=</span> <span class="va">y</span><span class="op">~</span><span class="va">x</span>, linewidth <span class="op">=</span> <span class="fl">2</span>, se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"X"</span>, y <span class="op">=</span> <span class="st">"Y"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span>base_size <span class="op">=</span> <span class="fl">16</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/annotate.html">annotate</a></span><span class="op">(</span><span class="st">"text"</span>, x <span class="op">=</span> <span class="fl">5</span>, y <span class="op">=</span> <span class="fl">80</span>, size <span class="op">=</span> <span class="fl">6</span>,</span>
<span>           label <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">"X Centered\nr ="</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">r2</span>, <span class="fl">3</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">gg1</span> <span class="op">+</span> <span class="va">gg2</span>         <span class="co"># show plots side-by-side</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-collin-centering" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-collin-centering-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/fig-collin-centering-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-collin-centering-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.5: Centering a predictor removes the nessessary correlation in a quadratic regression
</figcaption></figure>
</div>
</div>
</div>
<p><strong>Example</strong>: Interactions</p>
<p>The dataset <code><a href="https://friendly.github.io/genridge/reference/Acetylene.html">genridge::Acetylene</a></code> gives data from <span class="citation" data-cites="MarquardtSnee1975">Marquardt &amp; Snee (<a href="90-references.html#ref-MarquardtSnee1975" role="doc-biblioref">1975</a>)</span> on the <code>yield</code> of a chemical manufacturing process to produce acetylene in relation to reactor temperature (<code>temp</code>), the <code>ratio</code> of two components and the contact <code>time</code> in the reactor. A naive response surface model might suggest that yield is quadratic in time and there are potential interactions among all pairs of predictors.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb16" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="va">Acetylene</span>, package <span class="op">=</span> <span class="st">"genridge"</span><span class="op">)</span></span>
<span><span class="va">acetyl.mod0</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">yield</span> <span class="op">~</span> <span class="va">temp</span> <span class="op">+</span> <span class="va">ratio</span> <span class="op">+</span> <span class="va">time</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">time</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span> <span class="op">+</span> </span>
<span>                          <span class="va">temp</span><span class="op">:</span><span class="va">time</span> <span class="op">+</span> <span class="va">temp</span><span class="op">:</span><span class="va">ratio</span> <span class="op">+</span> <span class="va">time</span><span class="op">:</span><span class="va">ratio</span>,</span>
<span>                  data<span class="op">=</span><span class="va">Acetylene</span><span class="op">)</span></span>
<span></span>
<span><span class="op">(</span><span class="va">acetyl.vif0</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/car/man/vif.html">vif</a></span><span class="op">(</span><span class="va">acetyl.mod0</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt;       temp      ratio       time  I(time^2)  temp:time temp:ratio </span></span>
<span><span class="co">#&gt;        383      10555      18080        564       9719       9693 </span></span>
<span><span class="co">#&gt; ratio:time </span></span>
<span><span class="co">#&gt;        225</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>These results are horrible! How much does centering help? I first center all three predictors and then use <code><a href="https://rdrr.io/r/stats/update.html">update()</a></code> to re-fit the same model using the centered data.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb17" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">Acetylene.centered</span> <span class="op">&lt;-</span></span>
<span>  <span class="va">Acetylene</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>temp <span class="op">=</span> <span class="va">temp</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">temp</span><span class="op">)</span>,</span>
<span>         time <span class="op">=</span> <span class="va">time</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">time</span><span class="op">)</span>,</span>
<span>         ratio <span class="op">=</span> <span class="va">ratio</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">ratio</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">acetyl.mod1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/update.html">update</a></span><span class="op">(</span><span class="va">acetyl.mod0</span>, data<span class="op">=</span><span class="va">Acetylene.centered</span><span class="op">)</span></span>
<span><span class="op">(</span><span class="va">acetyl.vif1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/car/man/vif.html">vif</a></span><span class="op">(</span><span class="va">acetyl.mod1</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt;       temp      ratio       time  I(time^2)  temp:time temp:ratio </span></span>
<span><span class="co">#&gt;      57.09       1.09      81.57      51.49      44.67      30.69 </span></span>
<span><span class="co">#&gt; ratio:time </span></span>
<span><span class="co">#&gt;      33.33</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This is far better, although still not great in terms of VIF. But, how much have we improved the situation by the simple act of centering the predictors? The square roots of the ratios of VIFs tell us the impact of centering on the standard errors.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb18" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">acetyl.vif0</span> <span class="op">/</span> <span class="va">acetyl.vif1</span><span class="op">)</span></span>
<span><span class="co">#&gt;       temp      ratio       time  I(time^2)  temp:time temp:ratio </span></span>
<span><span class="co">#&gt;       2.59      98.24      14.89       3.31      14.75      17.77 </span></span>
<span><span class="co">#&gt; ratio:time </span></span>
<span><span class="co">#&gt;       2.60</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Finally, we use <code>poly(time, 2)</code> in the model for the centered data. Because there are multiple degree of freedom terms in the model, <code><a href="https://rdrr.io/pkg/car/man/vif.html">car::vif()</a></code> calculates GVIFs here. The final column gives <span class="math inline">\(\sqrt{\text{GVIF}^{1/2 \text{df}}}\)</span>, the remaining effect of collinearity on the standard errors of terms in this model.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb19" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">acetyl.mod2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">yield</span> <span class="op">~</span> <span class="va">temp</span> <span class="op">+</span> <span class="va">ratio</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/poly.html">poly</a></span><span class="op">(</span><span class="va">time</span>, <span class="fl">2</span><span class="op">)</span> <span class="op">+</span> </span>
<span>                          <span class="va">temp</span><span class="op">:</span><span class="va">time</span> <span class="op">+</span> <span class="va">temp</span><span class="op">:</span><span class="va">ratio</span> <span class="op">+</span> <span class="va">time</span><span class="op">:</span><span class="va">ratio</span>,</span>
<span>                  data<span class="op">=</span><span class="va">Acetylene.centered</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/car/man/vif.html">vif</a></span><span class="op">(</span><span class="va">acetyl.mod2</span>, type <span class="op">=</span> <span class="st">"term"</span><span class="op">)</span></span>
<span><span class="co">#&gt;                  GVIF Df GVIF^(1/(2*Df))</span></span>
<span><span class="co">#&gt; temp            57.09  1            7.56</span></span>
<span><span class="co">#&gt; ratio            1.09  1            1.05</span></span>
<span><span class="co">#&gt; poly(time, 2) 1733.56  2            6.45</span></span>
<span><span class="co">#&gt; temp:time       44.67  1            6.68</span></span>
<span><span class="co">#&gt; temp:ratio      30.69  1            5.54</span></span>
<span><span class="co">#&gt; ratio:time      33.33  1            5.77</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="sec:ridge" class="level2" data-number="8.4"><h2 data-number="8.4" class="anchored" data-anchor-id="sec:ridge">
<span class="header-section-number">8.4</span> Ridge regression</h2>
<section id="what-is-ridge-regression" class="level3" data-number="8.4.1"><h3 data-number="8.4.1" class="anchored" data-anchor-id="what-is-ridge-regression">
<span class="header-section-number">8.4.1</span> What is ridge regression?</h3>
</section><section id="univariate-ridge-trace-plots" class="level3" data-number="8.4.2"><h3 data-number="8.4.2" class="anchored" data-anchor-id="univariate-ridge-trace-plots">
<span class="header-section-number">8.4.2</span> Univariate ridge trace plots</h3>
</section><section id="bivariate-ridge-trace-plots" class="level3" data-number="8.4.3"><h3 data-number="8.4.3" class="anchored" data-anchor-id="bivariate-ridge-trace-plots">
<span class="header-section-number">8.4.3</span> Bivariate ridge trace plots</h3>
<div class="cell" data-layout-align="center">
<pre data-code-line-numbers=""><code>#&gt; Writing packages to  C:/R/projects/Vis-MLM-book/bib/pkgs.txt
#&gt; 11  packages used here:
#&gt;  car, carData, dplyr, factoextra, genridge, ggplot2, ggrepel, knitr, MASS, patchwork, VisCollin</code></pre>
</div>
<!-- ## References {.unnumbered} -->


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-Belsley:91a" class="csl-entry" role="listitem">
Belsley, D. A. (1991). <em>Conditioning diagnostics: Collinearity and weak data in regression</em>. Wiley.
</div>
<div id="ref-Belsley-etal:80" class="csl-entry" role="listitem">
Belsley, D. A., Kuh, E., &amp; Welsch, R. E. (1980). <em>Regression diagnostics: Identifying influential data and sources of collinearity</em>. John Wiley; Sons.
</div>
<div id="ref-Fox:2016:ARA" class="csl-entry" role="listitem">
Fox, J. (2016). <em>Applied regression analysis and generalized linear models</em> (Third edition.). SAGE.
</div>
<div id="ref-FoxMonette:92" class="csl-entry" role="listitem">
Fox, J., &amp; Monette, G. (1992). Generalized collinearity diagnostics. <em>Journal of the American Statistical Association</em>, <em>87</em>(417), 178–183.
</div>
<div id="ref-FriendlyKwan:2009" class="csl-entry" role="listitem">
Friendly, M., &amp; Kwan, E. (2009). Where’s <span>Waldo</span>: Visualizing collinearity diagnostics. <em>The American Statistician</em>, <em>63</em>(1), 56–65. <a href="https://doi.org/10.1198/tast.2009.0012">https://doi.org/10.1198/tast.2009.0012</a>
</div>
<div id="ref-Gabriel:71" class="csl-entry" role="listitem">
Gabriel, K. R. (1971). The biplot graphic display of matrices with application to principal components analysis. <em>Biometrics</em>, <em>58</em>(3), 453–467. <a href="https://doi.org/10.2307/2334381">https://doi.org/10.2307/2334381</a>
</div>
<div id="ref-GowerHand:96" class="csl-entry" role="listitem">
Gower, J. C., &amp; Hand, D. J. (1996). <em>Biplots</em>. Chapman &amp; Hall.
</div>
<div id="ref-Kwan-etal:2009" class="csl-entry" role="listitem">
Kwan, E., Lu, I. R. R., &amp; Friendly, M. (2009). Tableplot: A new tool for assessing precise predictions. <em>Zeitschrift f<span>ü</span>r Psychologie / Journal of Psychology</em>, <em>217</em>(1), 38–48. <a href="https://doi.org/10.1027/0044-3409.217.1.38">https://doi.org/10.1027/0044-3409.217.1.38</a>
</div>
<div id="ref-Longley:1967" class="csl-entry" role="listitem">
Longley, J. W. (1967). An appraisal of least squares programs for the electronic computer from the point of view of the user. <em>Journal of the American Statistical Association</em>, <em>62</em>, 819–841. https://doi.org/<a href="https://www.tandfonline.com/doi/abs/10.1080/01621459.1967.10500896">https://www.tandfonline.com/doi/abs/10.1080/01621459.1967.10500896</a>
</div>
<div id="ref-Marquardt:1970" class="csl-entry" role="listitem">
Marquardt, D. W. (1970). Generalized inverses, ridge regression, biased linear estimation, and nonlinear estimation. <em>Technometrics</em>, <em>12</em>, 591–612.
</div>
<div id="ref-MarquardtSnee1975" class="csl-entry" role="listitem">
Marquardt, D. W., &amp; Snee, R. D. (1975). Ridge regression in practice. <em>The American Statistician</em>, <em>29</em>(1), 3–20. <a href="https://doi.org/10.1080/00031305.1975.10479105">https://doi.org/10.1080/00031305.1975.10479105</a>
</div>
</div>
</section></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1"><p>This example is adapted from one by John Fox (2022), <a href="https://socialsciences.mcmaster.ca/jfox/Courses/SORA-TABA/slides-collinearity.pdf">Collinearity Diagnostics</a><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./07-lin-mod-topics.html" class="pagination-link" aria-label="Topics in Linear Models">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Topics in Linear Models</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./09-hotelling.html" class="pagination-link" aria-label="Hotelling's $T^2$">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Hotelling’s <span class="math inline">\(T^2\)</span></span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/friendly/vis-MLM-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div></div></footer><script src="site_libs/quarto-contrib/line-highlight-1.0.0/line-highlight.js" defer="true"></script>
</body></html>