<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.550">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Visualizing Multivariate Data and Models in R - 10&nbsp; Multivariate Linear Models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./11-mlm-viz.html" rel="next">
<link href="./09-hotelling.html" rel="prev">
<link href="./images/favicon/favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/quarto-contrib/line-highlight-1.0.0/line-highlight.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./09-hotelling.html">Multivariate Linear Models</a></li><li class="breadcrumb-item"><a href="./10-mlm-review.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Multivariate Linear Models</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><header id="title-block-header" class="quarto-title-block default page-columns page-full"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./09-hotelling.html">Multivariate Linear Models</a></li><li class="breadcrumb-item"><a href="./10-mlm-review.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Multivariate Linear Models</span></a></li></ol></nav><div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title"><span id="sec-mlm-review" class="quarto-section-identifier"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Multivariate Linear Models</span></span></h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Visualizing Multivariate Data and Models in R</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/friendly/vis-MLM-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Orienting Ideas</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-getting_started.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Getting Started</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Exploratory Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-multivariate_plots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Plots of Multivariate Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-pca-biplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Dimension Reduction</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Univariate Linear Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-linear_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Overview of Linear models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-linear_models-plots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Plots for univariate response models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-lin-mod-topics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Topics in Linear Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-collinearity-ridge.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Collinearity &amp; Ridge Regression</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Multivariate Linear Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-hotelling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Hotelling’s <span class="math inline">\(T^2\)</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-mlm-review.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Multivariate Linear Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-mlm-viz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Visualizing Multivariate Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-eqcov.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Visualizing Equality of Covariance Matrices</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-case-studies.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Case studies</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">End matter</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./91-colophon.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Colophon</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./95-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#structure-of-the-mlm" id="toc-structure-of-the-mlm" class="nav-link active" data-scroll-target="#structure-of-the-mlm"><span class="header-section-number">10.1</span> Structure of the MLM</a>
  <ul class="collapse">
<li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions"><span class="header-section-number">10.1.1</span> Assumptions</a></li>
  </ul>
</li>
  <li>
<a href="#fitting-the-model" id="toc-fitting-the-model" class="nav-link" data-scroll-target="#fitting-the-model"><span class="header-section-number">10.2</span> Fitting the model</a>
  <ul class="collapse">
<li><a href="#example-dog-food-data" id="toc-example-dog-food-data" class="nav-link" data-scroll-target="#example-dog-food-data"><span class="header-section-number">10.2.1</span> Example: Dog Food Data</a></li>
  <li><a href="#sums-of-squares" id="toc-sums-of-squares" class="nav-link" data-scroll-target="#sums-of-squares"><span class="header-section-number">10.2.2</span> Sums of squares</a></li>
  <li><a href="#how-big-is-ss_h-compared-to-ss_e" id="toc-how-big-is-ss_h-compared-to-ss_e" class="nav-link" data-scroll-target="#how-big-is-ss_h-compared-to-ss_e"><span class="header-section-number">10.2.3</span> How big is <span class="math inline">\(SS_H\)</span> compared to <span class="math inline">\(SS_E\)</span>?</a></li>
  </ul>
</li>
  <li>
<a href="#multivariate-test-statistics" id="toc-multivariate-test-statistics" class="nav-link" data-scroll-target="#multivariate-test-statistics"><span class="header-section-number">10.3</span> Multivariate test statistics</a>
  <ul class="collapse">
<li><a href="#testing-contrasts-and-linear-hypotheses" id="toc-testing-contrasts-and-linear-hypotheses" class="nav-link" data-scroll-target="#testing-contrasts-and-linear-hypotheses"><span class="header-section-number">10.3.1</span> Testing contrasts and linear hypotheses</a></li>
  </ul>
</li>
  <li>
<a href="#anova-rightarrow-manova" id="toc-anova-rightarrow-manova" class="nav-link" data-scroll-target="#anova-rightarrow-manova"><span class="header-section-number">10.4</span> ANOVA <span class="math inline">\(\rightarrow\)</span> MANOVA</a>
  <ul class="collapse">
<li><a href="#example-father-parenting-data" id="toc-example-father-parenting-data" class="nav-link" data-scroll-target="#example-father-parenting-data"><span class="header-section-number">10.4.1</span> Example: Father parenting data</a></li>
  <li><a href="#ordered-factors" id="toc-ordered-factors" class="nav-link" data-scroll-target="#ordered-factors"><span class="header-section-number">10.4.2</span> Ordered factors</a></li>
  <li><a href="#example-adolescent-mental-health" id="toc-example-adolescent-mental-health" class="nav-link" data-scroll-target="#example-adolescent-mental-health"><span class="header-section-number">10.4.3</span> Example: Adolescent mental health</a></li>
  <li><a href="#factorial-manova" id="toc-factorial-manova" class="nav-link" data-scroll-target="#factorial-manova"><span class="header-section-number">10.4.4</span> Factorial MANOVA</a></li>
  </ul>
</li>
  <li><a href="#mra-rightarrow-mmra" id="toc-mra-rightarrow-mmra" class="nav-link" data-scroll-target="#mra-rightarrow-mmra"><span class="header-section-number">10.5</span> MRA <span class="math inline">\(\rightarrow\)</span> MMRA</a></li>
  <li><a href="#ancova-rightarrow-mancova" id="toc-ancova-rightarrow-mancova" class="nav-link" data-scroll-target="#ancova-rightarrow-mancova"><span class="header-section-number">10.6</span> ANCOVA <span class="math inline">\(\rightarrow\)</span> MANCOVA</a></li>
  <li><a href="#repeated-measures-designs" id="toc-repeated-measures-designs" class="nav-link" data-scroll-target="#repeated-measures-designs"><span class="header-section-number">10.7</span> Repeated measures designs</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/friendly/vis-MLM-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content"><!--- For HTML Only ---><!-- \require{newcommand} --><!-- %\renewcommand*{\det}[1]{\mathrm{det} (#1)} --><!-- %\renewcommand*{\det}[1]{|#1|} --><!-- \newcommand{\sizedmat}[2]{\mathord{\mathop{\mat{#1}}\limits_{(#2)}}} --><!-- \newcommand*{\E}{\mathcal{E}} --><!-- Index generation --><!-- % R packages:  indexed under both package name and packages! --><!-- % data sets:  --><!-- % R stuff --><p><a href="09-hotelling.html" class="quarto-xref"><span>Chapter 9</span></a> introduced the essential ideas of multivariate analysis in the context of a two-group design using Hotelling’s <span class="math inline">\(T^2\)</span>. Here, I extend this to the general Multivariate Linear Model (MLM). This can be understood as a simple extension of the univariate linear model, with the main difference being that there are multiple response variables considered together, instead of just one, analysed alone. These outcomes might reflect several different ways or scales for measuring an underlying theoretical construct, or they might represent different aspects of some phenomenon that are better understood when studied jointly.</p>
<p>For example, in the first case of different measures, there are numerous psychological scales used to assess depression or anxiety and it may be important to include more than one measure to ensure that the construct has been measured adequately. In the second case of various aspects, student “aptitude” or “achievement” reflects competency in different various subjects (reading, math, history, science, …) that are better studied together.</p>
<p>In this context, there are multiple techniques that can be applied depending on the structure of the variables at hand. For instance, with one or more continuous predictors and multiple response variables, one could use multivariate multiple regression (MMRA) to obtain estimates useful for prediction. Instead, if the predictors are categorical, multivariate analysis of variance (MANOVA) can be applied to test for differences between groups. Again, this is akin to multiple regression and ANOVA in the univariate context – the same underlying model is utilized, but the tests for terms in the model are multivariate ones for the collection of all response variables, rather than univariate ones for a single response.</p>
<!-- **TODO** Use `\Epsilon` = $\Epsilon$ here, which is defined as `\boldsymbol{\large\varepsilon}` for residuals. -->
<!-- Could also use a larger version, `\boldsymbol{\Large\varepsilon}` = -->
<!-- $\boldsymbol{\Large\varepsilon}$ if that makes a difference. -->
<p>Before considering the details and examples that apply to MANOVA and MMRA, it is useful to consider the features of the multivariate linear model of which these cases are examples.</p>
<p><strong>Packages</strong></p>
<p>In this chapter I use the following packages. Load them now:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb1" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://broom.tidymodels.org/">broom</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://r-forge.r-project.org/projects/car/">car</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://friendly.github.io/heplots/">heplots</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://patchwork.data-imaginist.com">patchwork</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyr.tidyverse.org">tidyr</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/friendly/matlib">matlib</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="structure-of-the-mlm" class="level2" data-number="10.1"><h2 data-number="10.1" class="anchored" data-anchor-id="structure-of-the-mlm">
<span class="header-section-number">10.1</span> Structure of the MLM</h2>
<p><strong>TODO</strong> Revise notation here</p>
<p>With <span class="math inline">\(p\)</span> response variables, the multivariate linear model is most easily appreciated as the collection of <span class="math inline">\(p\)</span> linear models, one for each response.</p>
<p><span class="math display">\[\begin{aligned}
\mathbf{y}_1 =&amp; \mathbf{X}\boldsymbol{\beta}_1 + \boldsymbol{\epsilon}_1 \\
\mathbf{y}_2 =&amp; \mathbf{X}\boldsymbol{\beta}_2 + \boldsymbol{\epsilon}_2 \\
  \vdots      &amp;  \\
\mathbf{y}_p =&amp; \mathbf{X}\boldsymbol{\beta}_p + \boldsymbol{\epsilon}_p \\
\end{aligned}\]</span></p>
<p>The model matrix <span class="math inline">\(\mathbf{X}\)</span> is the same for all responses, but each one gets its own vector <span class="math inline">\(\boldsymbol{\beta}_j\)</span> of coefficients for how the predictors in <span class="math inline">\(\mathbf{X}\)</span> fit a given response <span class="math inline">\(\mathbf{y}_j\)</span>.</p>
<p>Among the beauties of multivariate thinking is that we can put these separate equations together in single equation by joining the responses <span class="math inline">\(\mathbf{y}_j\)</span> as columns in a matrix <span class="math inline">\(\mathbf{Y}\)</span> and similarly arranging the vectors of coefficients <span class="math inline">\(\boldsymbol{\beta}_j\)</span> as columns in a matrix <span class="math inline">\(\mathbf{B}\)</span>. (A slight hiccup in notation is that the <em>uppercase</em> for the greek <span class="math inline">\(\boldsymbol{\beta}\)</span> is the same as <span class="math inline">\(\mathbf{B}\)</span>, so I use <span class="math inline">\(\mathbf{b}_1 , \mathbf{b}_2 , \dots\)</span> below to refer to its’ columns.)</p>
<p>The MLM then becomes:</p>
<!-- $$ -->
<!-- \newcommand{\sizedmat}[2]{\mathord{\mathop{\mathbf{#1}\limits_{(#2)}}} -->
<!-- $$ -->
<p><span id="eq-mlm"><span class="math display">\[
\mathord{\mathop{\mathbf{Y}}\limits_{n \times p}} =
\mathord{\mathop{\mathbf{X}}\limits_{n \times (q+1)}} \, \mathord{\mathop{\mathbf{B}}\limits_{(q+1) \times p}} + \mathord{\mathop{\mathbf{\boldsymbol{\Large\varepsilon}}}\limits_{n \times p}} \:\: ,
\tag{10.1}\]</span></span></p>
<p>where</p>
<ul>
<li>
<span class="math inline">\(\mathbf{Y} = (\mathbf{y}_1 , \mathbf{y}_2, \dots ,  \mathbf{y}_p )\)</span> is the matrix of <span class="math inline">\(n\)</span> observations on <span class="math inline">\(p\)</span> responses, with typical column <span class="math inline">\(\mathbf{y}_j\)</span>;</li>
<li>
<span class="math inline">\(\mathbf{X}\)</span> is the model matrix with columns <span class="math inline">\(\mathbf{x}_i\)</span> for <span class="math inline">\(q\)</span> regressors, which typically includes an initial column <span class="math inline">\(\mathbf{x}_0\)</span> of 1s for the intercept;</li>
<li>
<span class="math inline">\(\mathbf{B} = ( \mathbf{b}_1 , \mathbf{b}_2 , \dots,  \mathbf{b}_p )\)</span> is a matrix of regression coefficients, one column <span class="math inline">\(\mathbf{b}_j\)</span> for each response variable;</li>
<li>
<span class="math inline">\(\boldsymbol{\Large\varepsilon}\)</span> is a matrix of errors in predicting <span class="math inline">\(\mathbf{Y}\)</span>.</li>
</ul>
<p>Writing <a href="#eq-mlm" class="quarto-xref">Equation&nbsp;<span>10.1</span></a> in terms of its elements, we have</p>
<p><span class="math display">\[
\begin{align*}
\overset{\mathbf{Y}}
  {\begin{bmatrix}
  y_{11} &amp; y_{12} &amp; \cdots &amp; y_{1p} \\
  y_{21} &amp; y_{22} &amp; \cdots &amp; y_{2p} \\
  \vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
  y_{n1} &amp; y_{n2} &amp; \cdots &amp; y_{np}
  \end{bmatrix}
  }
&amp; =
\overset{\mathbf{X}}
  {\begin{bmatrix}
  1 &amp; x_{11} &amp; \cdots &amp; x_{1q} \\
  1 &amp; x_{21} &amp; \cdots &amp; x_{2q} \\
  \vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
  1 &amp; x_{n1} &amp; \cdots &amp; x_{nq}
  \end{bmatrix}
  }
\overset{\mathbf{B}}
  {\begin{bmatrix}
  \beta_{01} &amp; \beta_{02} &amp; \cdots &amp; \beta_{0p} \\
  \beta_{11} &amp; \beta_{12} &amp; \cdots &amp; \beta_{1p} \\
  \vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
  \beta_{q1} &amp; \beta_{q2} &amp; \cdots &amp; \beta_{qp}
  \end{bmatrix}
  } \\
&amp; + \quad\quad
\overset{\mathcal{\boldsymbol{\Large\varepsilon}}}
  {\begin{bmatrix}
  \epsilon_{11} &amp; \epsilon_{12} &amp; \cdots &amp; \epsilon_{1p} \\
  \epsilon_{21} &amp; \epsilon_{22} &amp; \cdots &amp; \epsilon_{2p} \\
  \vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
  \epsilon_{n1} &amp; \epsilon_{n2} &amp; \cdots &amp; \epsilon_{np}
  \end{bmatrix}
  }
\end{align*}
\]</span></p>
<p>The structure of the model matrix <span class="math inline">\(\mathbf{X}\)</span> is exactly the same as the univariate linear model, and may therefore contain,</p>
<ul>
<li>
<strong>quantitative</strong> predictors, such as <code>age</code>, <code>income</code>, years of <code>education</code>
</li>
<li>
<strong>transformed predictors</strong> like <span class="math inline">\(\sqrt{\text{age}}\)</span> or <span class="math inline">\(\log{(\text{income})}\)</span>
</li>
<li>
<strong>polynomial terms</strong>: <span class="math inline">\(\text{age}^2\)</span>, <span class="math inline">\(\text{age}^3, \dots\)</span> (using <code>poly(age, k)</code> in R)</li>
<li>
<strong>categorical predictors</strong> (“factors”), such as treatment (Control, Drug A, drug B), or sex; internally a factor with <code>k</code> levels is transformed to <code>k-1</code> dummy (0, 1) variables, representing comparisons with a reference level, typically the first.</li>
<li>
<strong>interaction terms</strong>, involving either quantitative or categorical predictors, e.g., <code>age * sex</code>, <code>treatment * sex</code>.</li>
</ul>
<section id="assumptions" class="level3" data-number="10.1.1"><h3 data-number="10.1.1" class="anchored" data-anchor-id="assumptions">
<span class="header-section-number">10.1.1</span> Assumptions</h3>
<p>Just as in univariate models, the assumptions of the multivariate linear model almost entirely concern the behavior of the errors (residuals). Let <span class="math inline">\(\mathbf{\epsilon}_{i}^{\prime}\)</span> represent the <span class="math inline">\(i\)</span>th row of <span class="math inline">\(\boldsymbol{\Large\varepsilon}\)</span>. Then it is assumed that:</p>
<ul>
<li>
<strong>Normality</strong>: The residuals, <span class="math inline">\(\mathbf{\epsilon}_{i}^{\prime}\)</span> are distributed as multivariate normal, <span class="math inline">\(\mathcal{N}_{p}(\mathbf{0},\boldsymbol{\Sigma})\)</span>, where <span class="math inline">\(\mathbf{\Sigma}\)</span> is a non-singular error-covariance matrix. Statistical tests of multivariate normality of the residuals include the Shapiro-Wilk <span class="citation" data-cites="ShapiroWilk1965">(<a href="95-references.html#ref-ShapiroWilk1965" role="doc-biblioref">Shapiro &amp; Wilk, 1965</a>)</span> and Mardia <span class="citation" data-cites="Mardia:1970:MMS">(<a href="95-references.html#ref-Mardia:1970:MMS" role="doc-biblioref">Mardia, 1970</a>)</span> tests (in the <strong>MVN</strong> package); <!-- mshapiro.test( )[in the mvnormtest package] can be used to perform the Shapiro-Wilk test for multivariate normality --> however this is often better assessed visually using a <span class="math inline">\(\chi^2\)</span> QQ plot of Mahalanobis squared distance against their corresponding <span class="math inline">\(\chi^2_p\)</span> values for <span class="math inline">\(p\)</span> degrees of freedom using <code><a href="https://friendly.github.io/heplots/reference/cqplot.html">heplots::cqplot()</a></code>.</li>
<li>
<strong>Homoscedasticity</strong>: The error-covariance matrix <span class="math inline">\(\mathbf{\Sigma}\)</span> is constant across all observations and grouping factors. Graphical methods to show if this assumption is met are described in <a href="12-eqcov.html" class="quarto-xref"><span>Chapter 12</span></a>.</li>
<li>
<strong>Independence</strong>: <span class="math inline">\(\mathbf{\epsilon}_{i}^{\prime}\)</span> and <span class="math inline">\(\mathbf{\epsilon}_{j}^{\prime}\)</span> are independent for <span class="math inline">\(i\neq j\)</span>, so knowing the data for case <span class="math inline">\(i\)</span> gives no information about case <span class="math inline">\(j\)</span> (as would be true if the data consisted of pairs of husbands and wives);</li>
<li>The predictors, <span class="math inline">\(\mathbf{X}\)</span>, are fixed and measured without error or at least they are independent of the errors, <span class="math inline">\(\boldsymbol{\Large\varepsilon}\)</span>.</li>
</ul>
<p>These statements are simply the multivariate analogs of the assumptions of normality, constant variance and independence of the errors in univariate models. Note that it is unnecessary to assume that the predictors (regressors, columns of <span class="math inline">\(\mathbf{X}\)</span>) are normally distributed.</p>
<p>Implicit in the above is perhaps the most important assumption—that the model has been correctly specified. This means:</p>
<ul>
<li><p><strong>Linearity</strong>: The form of the relations between each <span class="math inline">\(\mathbf{y}\)</span> and the <span class="math inline">\(\mathbf{x}\)</span>s is correct. Typically this means that the relations are <em>linear</em>, but if not, we have specified a correct transformation of <span class="math inline">\(\mathbf{y}\)</span> and/or <span class="math inline">\(\mathbf{x}\)</span>.</p></li>
<li><p><strong>Completeness</strong>: No relevant predictors have been omitted from the model.</p></li>
<li><p><strong>Additive effects</strong>: The combined effect of different predictors is the sum of their individual effects.</p></li>
</ul></section></section><section id="fitting-the-model" class="level2" data-number="10.2"><h2 data-number="10.2" class="anchored" data-anchor-id="fitting-the-model">
<span class="header-section-number">10.2</span> Fitting the model</h2>
<p>The least squares (and also maximum likelihood) solution for the coefficients <span class="math inline">\(\mathbf{B}\)</span> is given by</p>
<!-- $$ -->
<!-- \widehat{\mathbf{B}} = (\mathbf{X}\trans \mathbf{X})^{-1} \mathbf{X}\trans \mathbf{Y} \period -->
<!-- $$ -->
<p><span class="math display">\[
\widehat{\mathbf{B}} = (\mathbf{X}^\mathsf{T} \mathbf{X})^{-1} \mathbf{X}^\mathsf{T} \mathbf{Y} \:\: .
\]</span></p>
<p>This is precisely the same as fitting the separate responses <span class="math inline">\(\mathbf{y}_1 , \mathbf{y}_2 , \dots , \mathbf{y}_p\)</span>, and placing the estimated coefficients <span class="math inline">\(\widehat{\mathbf{b}}_i\)</span> as columns in <span class="math inline">\(\widehat{\mathbf{B}}\)</span></p>
<p><span class="math display">\[
\widehat{\mathbf{B}} = [ \widehat{\mathbf{b}}_1, \widehat{\mathbf{b}}_2, \dots , \widehat{\mathbf{b}}_p] \:\: .
\]</span> In R, we fit the multivariate linear model with <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> simply by giving a collection of response variables <code>y1, y2, ...</code> on the left-hand side of the model formula, wrapped in <code><a href="https://rdrr.io/r/base/cbind.html">cbind()</a></code> which combines them to form a matrix response.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb2" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">y1</span>, <span class="va">y2</span>, <span class="va">y3</span><span class="op">)</span> <span class="op">~</span> <span class="va">x1</span> <span class="op">+</span> <span class="va">x2</span> <span class="op">+</span> <span class="va">...</span>, data<span class="op">=</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In the presence of possible outliers, robust methods are available for univariate linear models (e.g., <code><a href="https://rdrr.io/pkg/MASS/man/rlm.html">MASS::rlm()</a></code>). So too, <code><a href="https://friendly.github.io/heplots/reference/robmlm.html">heplots::robmlm()</a></code> provides robust estimation in the multivariate case.</p>
<section id="example-dog-food-data" class="level3" data-number="10.2.1"><h3 data-number="10.2.1" class="anchored" data-anchor-id="example-dog-food-data">
<span class="header-section-number">10.2.1</span> Example: Dog Food Data</h3>
<p>As a toy example to make these ideas concrete, consider the dataset <code><a href="https://friendly.github.io/heplots/reference/dogfood.html">heplots::dogfood</a></code>. Here, a dogfood manufacturer wanted to study preference for different dogfood formulas, two of their own (“Old”, “New”) and two from other manufacturers (“Major”, “Alps”). In a between-dog design, each of <span class="math inline">\(n=4\)</span> dogs were presented with a bowl of <em>one</em> formula and the time to <code>start</code> eating and <code>amount</code> eaten were recorded. Greater preference would be seen in a shorter delay to start eating and a greater amount, so these responses are expected to be negatively correlated.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb3" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="va">dogfood</span>, package <span class="op">=</span> <span class="st">"heplots"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">dogfood</span><span class="op">)</span></span>
<span><span class="co">#&gt; spc_tbl_ [16 × 3] (S3: spec_tbl_df/tbl_df/tbl/data.frame)</span></span>
<span><span class="co">#&gt;  $ formula: Factor w/ 4 levels "Old","New","Major",..: 1 1 1 1 2 2 2 2 3 3 ...</span></span>
<span><span class="co">#&gt;   ..- attr(*, "contrasts")= num [1:4, 1:3] 1 1 -1 -1 0 0 1 -1 1 -1 ...</span></span>
<span><span class="co">#&gt;   .. ..- attr(*, "dimnames")=List of 2</span></span>
<span><span class="co">#&gt;   .. .. ..$ : chr [1:4] "Old" "New" "Major" "Alps"</span></span>
<span><span class="co">#&gt;   .. .. ..$ : NULL</span></span>
<span><span class="co">#&gt;  $ start  : num [1:16] 0 1 1 0 0 1 2 3 1 5 ...</span></span>
<span><span class="co">#&gt;  $ amount : num [1:16] 100 97 88 92 95 85 82 89 77 84 ...</span></span>
<span><span class="co">#&gt;  - attr(*, "spec")=List of 3</span></span>
<span><span class="co">#&gt;   ..$ cols   :List of 3</span></span>
<span><span class="co">#&gt;   .. ..$ formula: list()</span></span>
<span><span class="co">#&gt;   .. .. ..- attr(*, "class")= chr [1:2] "collector_character" "collector"</span></span>
<span><span class="co">#&gt;   .. ..$ start  : list()</span></span>
<span><span class="co">#&gt;   .. .. ..- attr(*, "class")= chr [1:2] "collector_double" "collector"</span></span>
<span><span class="co">#&gt;   .. ..$ amount : list()</span></span>
<span><span class="co">#&gt;   .. .. ..- attr(*, "class")= chr [1:2] "collector_double" "collector"</span></span>
<span><span class="co">#&gt;   ..$ default: list()</span></span>
<span><span class="co">#&gt;   .. ..- attr(*, "class")= chr [1:2] "collector_guess" "collector"</span></span>
<span><span class="co">#&gt;   ..$ skip   : int 1</span></span>
<span><span class="co">#&gt;   ..- attr(*, "class")= chr "col_spec"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For this data, boxplots for the two responses provide an initial look, shown in <a href="#fig-dogfood-boxplot" class="quarto-xref">Figure&nbsp;<span>10.1</span></a>. Putting these side-by-side makes it easy to see the inverse relation between the medians on the two response variables.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb4" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dog_long</span> <span class="op">&lt;-</span> <span class="va">dogfood</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">start</span>, <span class="va">amount</span><span class="op">)</span>,</span>
<span>               names_to <span class="op">=</span> <span class="st">"variable"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">dog_long</span>, </span>
<span>       <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">formula</span>, y <span class="op">=</span> <span class="va">value</span>, fill <span class="op">=</span> <span class="va">formula</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.2</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">2.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span><span class="op">(</span><span class="op">~</span> <span class="va">variable</span>, scales <span class="op">=</span> <span class="st">"free"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span>base_size <span class="op">=</span> <span class="fl">14</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>legend.position<span class="op">=</span><span class="st">"none"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div id="fig-dogfood-boxplot" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-dogfood-boxplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/ch10/fig-dogfood-boxplot-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="2100">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dogfood-boxplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.1: Boxplots for time to start eating and amount eaten by dogs given one of four dogfood formulas.
</figcaption></figure>
</div>
</div>
</div>
<p>As suggested above, the multivariate model for testing mean differences due to the dogfood <code>formula</code> is fit using <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> on the matrix <span class="math inline">\(\mathbf{Y}\)</span> constructed with <code>cbind(start, amount)</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb5" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dogfood.mod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">start</span>, <span class="va">amount</span><span class="op">)</span> <span class="op">~</span> <span class="va">formula</span>, </span>
<span>                  data<span class="op">=</span><span class="va">dogfood</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; lm(formula = cbind(start, amount) ~ formula, data = dogfood)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients:</span></span>
<span><span class="co">#&gt;              start   amount</span></span>
<span><span class="co">#&gt; (Intercept)   1.688  85.562</span></span>
<span><span class="co">#&gt; formula1     -0.688   5.438</span></span>
<span><span class="co">#&gt; formula2      0.125   1.875</span></span>
<span><span class="co">#&gt; formula3     -0.500   3.250</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>By default, the factor <code>formula</code> is represented by three columns in the <span class="math inline">\(\mathbf{X}\)</span> matrix that correspond to treatment contrasts, which are comparisons of the Old formula (a baseline level) with each of the others. The coefficients, for example <code>formulaNEW</code>, are the difference in means from those for Old.</p>
<p>Then, the overall multivariate test that means on both variables do not differ is carried out using <code><a href="https://rdrr.io/pkg/car/man/Anova.html">car::Anova()</a></code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb6" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dogfood.aov</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/car/man/Anova.html">Anova</a></span><span class="op">(</span><span class="va">dogfood.mod</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Type II MANOVA Tests: Pillai test statistic</span></span>
<span><span class="co">#&gt;         Df test stat approx F num Df den Df Pr(&gt;F)  </span></span>
<span><span class="co">#&gt; formula  3     0.702     2.16      6     24  0.083 .</span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The details of these analysis steps are explained below.</p>
</section><section id="sums-of-squares" class="level3" data-number="10.2.2"><h3 data-number="10.2.2" class="anchored" data-anchor-id="sums-of-squares">
<span class="header-section-number">10.2.2</span> Sums of squares</h3>
<p>In univariate response models, statistical tests and model summaries (like <span class="math inline">\(R^2\)</span>) are based on the familiar decomposition of the total sum of squares <span class="math inline">\(SS_T\)</span> into regression or hypothesis (<span class="math inline">\(SS_H\)</span>) and error (<span class="math inline">\(SS_E\)</span>) sums of squares. In the multivariate linear model each of these becomes a <span class="math inline">\(p \times p\)</span> matrix <span class="math inline">\(SSP\)</span> containing sums of squares for the <span class="math inline">\(p\)</span> responses on the diagonal and sums of cross products in the off-diagonal. elements. For the MLM this is expressed as:</p>
<p><span id="eq-SSP"><span class="math display">\[\begin{aligned}
\underset{(p\times p)}{\mathbf{SSP}_{T}}
&amp; =  \mathbf{Y}^{\top} \mathbf{Y} - n \overline{\mathbf{y}}\,\overline{\mathbf{y}}^{\top} \\
&amp; =  \left(\widehat {\mathbf{Y}}^{\top}\widehat{\mathbf{Y}} - n\overline{\mathbf{y}}\,\overline{\mathbf{y}}^{\top} \right) + \widehat{\boldsymbol{\Large\varepsilon}}^{\top}\widehat{\boldsymbol{\Large\varepsilon}} \\
&amp; =   \mathbf{SSP}_{H} + \mathbf{SSP}_{E} \\
&amp; \equiv  \mathbf{H} + \mathbf{E} \:\: ,
\end{aligned} \tag{10.2}\]</span></span></p>
<p>where,</p>
<ul>
<li>
<span class="math inline">\(\overline{\mathbf{y}}\)</span> is the <span class="math inline">\((p\times 1)\)</span> vector of means for the response variables;</li>
<li>
<span class="math inline">\(\widehat{\mathbf{Y}} = \mathbf{X}\widehat{\mathbf{B}}\)</span> is the matrix of fitted values; and</li>
<li>
<span class="math inline">\(\widehat{\boldsymbol{\Large\varepsilon}} = \mathbf{Y} -\widehat{\mathbf{Y}}\)</span> is the matrix of residuals.</li>
</ul>
<p>We can visualize this decomposition in the simple case of a two-group design (for the <code>mathscore</code> data in <a href="09-hotelling.html#sec-t2-properties" class="quarto-xref"><span>Section 9.2</span></a>) as shown in <a href="#fig-visualizing-SSP" class="quarto-xref">Figure&nbsp;<span>10.2</span></a>. Let <span class="math inline">\(\mathbf{y}_{ij}\)</span> be the vector of <span class="math inline">\(p\)</span> responses for subject <span class="math inline">\(j\)</span> in group <span class="math inline">\(i, i=1,\dots g\)</span> for <span class="math inline">\(j = 1, \dots n_i\)</span>. Then, using <span class="math inline">\(.\)</span> to represent a subscript averaged over, <a href="#eq-SSP" class="quarto-xref">Equation&nbsp;<span>10.2</span></a> comes from the identity</p>
<p><span id="eq-THE-dev"><span class="math display">\[
\underbrace{(\mathbf{y}_{ij} - \mathbf{y}_{\cdot \cdot})}_T =
\underbrace{(\overline{\mathbf{y}}_{i \cdot} - \mathbf{y}_{\cdot \cdot})}_H +
\underbrace{(\mathbf{y}_{ij} - \overline{\mathbf{y}}_{i \cdot})}_E
\tag{10.3}\]</span></span></p>
<p>where each side of <a href="#eq-THE-dev" class="quarto-xref">Equation&nbsp;<span>10.3</span></a> is squared and summed over observations to give <a href="#eq-SSP" class="quarto-xref">Equation&nbsp;<span>10.2</span></a>. In <a href="#fig-visualizing-SSP" class="quarto-xref">Figure&nbsp;<span>10.2</span></a>,</p>
<ul>
<li><p>The total variance <span class="math inline">\(\mathbf{SSP}_T\)</span> reflects the deviations of the observations <span class="math inline">\(\mathbf{y}_{ij}\)</span> from the grand mean <span class="math inline">\(\overline{\mathbf{y}}_{. .}\)</span> and has the data ellipse shown in gray.</p></li>
<li><p>In the middle panel, all the observations are represented at their group means, <span class="math inline">\(\overline{\mathbf{y}}_{i .}\)</span>, the fitted values. Their variance and covariance is then reflected by deviations of the group means (weighted for the number of observations per group) around the grand mean.</p></li>
<li><p>The right panel then shows the residual variance, which is the variation of the observations <span class="math inline">\(\mathbf{y}_{ij}\)</span> around their group means, <span class="math inline">\(\overline{\mathbf{y}}_{i .}\)</span>. Centering the two data ellipses at the centroid <span class="math inline">\(\overline{\mathbf{y}}_{. .}\)</span> then gives the ellipse for the <span class="math inline">\(\mathbf{SSP}_E\)</span>, also called the pooled within-group covariance matrix.</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-visualizing-SSP" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-visualizing-SSP-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/VisualizingSSP.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-visualizing-SSP-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.2: Breakdown of the total <span class="math inline">\(\mathbf{SSP}_{T}\)</span> into sums of squares and products for between-group hypothesis variance (<span class="math inline">\(\mathbf{SSP}_{H}\)</span>) and within-group, error variance (<span class="math inline">\(\mathbf{SSP}_{E}\)</span>).
</figcaption></figure>
</div>
</div>
</div>
<p>The formulas for these sum of squares and products matrices can be shown explicitly as follows, where the notation <span class="math inline">\(\mathbf{z} \mathbf{z}^\top\)</span> generates the <span class="math inline">\(p \times p\)</span> outer product of a vector <span class="math inline">\(\mathbf{z}\)</span>, giving <span class="math inline">\(z_k \times z_\ell\)</span> for all pairs of elements. <span class="math display">\[
\mathbf{SSP}_T =
\sum_{i=1}^{g} \sum_{j=1}^{n_{i}}\left(\mathbf{y}_{ij}-\overline{\mathbf{y}}_{\cdot \cdot}\right)\left(\mathbf{y}_{ij}-\overline{\mathbf{y}}_{\cdot \cdot}\right)^{\top}
\]</span></p>
<p><span class="math display">\[
\mathbf{SSP}_H =
\sum_{i=1}^{g} \mathbf{n}_{i}\left(\overline{\mathbf{y}}_{i \cdot}-\overline{\mathbf{y}}_{\cdot \cdot}\right)\left(\overline{\mathbf{y}}_{i \cdot}-\overline{\mathbf{y}}_{\cdot \cdot}\right)^{\top}
\]</span></p>
<p><span class="math display">\[
\mathbf{SSP}_E =
\sum_{i=1}^{g} \sum_{j=1}^{n_{i}} \left(\mathbf{y}_{ij}-\overline{\mathbf{y}}_{i \cdot}\right) \left(\mathbf{y}_{ij}-\overline{\mathbf{y}}_{i \cdot}\right)^{\top}
\]</span></p>
<p>This is the decomposition that we visualize in HE plots, where the size and direction of <span class="math inline">\(\mathbf{H}\)</span> and <span class="math inline">\(\mathbf{E}\)</span> can be represented as ellipsoids.</p>
<p>But first, let’s find these results for the example. The easy way is to get them from the result returned by <code><a href="https://rdrr.io/pkg/car/man/Anova.html">car::Anova()</a></code>, where the hypothesis <span class="math inline">\(\mathbf{SSP}_{H}\)</span> for each term in the model is returned as an element in a named list <code>SSP</code> and the error <span class="math inline">\(\mathbf{SSP}_{E}\)</span> is returned as the matrix <code>SSPE</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb7" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">SSP_H</span> <span class="op">&lt;-</span> <span class="va">dogfood.aov</span><span class="op">$</span><span class="va">SSP</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; $formula</span></span>
<span><span class="co">#&gt;         start amount</span></span>
<span><span class="co">#&gt; start    9.69  -70.9</span></span>
<span><span class="co">#&gt; amount -70.94  585.7</span></span>
<span><span class="va">SSP_E</span> <span class="op">&lt;-</span> <span class="va">dogfood.aov</span><span class="op">$</span><span class="va">SSPE</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt;        start amount</span></span>
<span><span class="co">#&gt; start   25.8   11.7</span></span>
<span><span class="co">#&gt; amount  11.7  390.3</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can calculate these directly as shown below. <code><a href="https://rdrr.io/r/base/sweep.html">sweep()</a></code> is used to subtract the <code><a href="https://rdrr.io/r/base/colSums.html">colMeans()</a></code> from <span class="math inline">\(\mathbf{Y}\)</span> and <span class="math inline">\(\widehat{\mathbf{Y}}\)</span> and <code><a href="https://rdrr.io/r/base/crossprod.html">crossprod()</a></code> premultiplies a matrix by its’ transpose.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb8" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">Y</span> <span class="op">&lt;-</span> <span class="va">dogfood</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"start"</span>, <span class="st">"amount"</span><span class="op">)</span><span class="op">]</span></span>
<span><span class="va">Ydev</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sweep.html">sweep</a></span><span class="op">(</span><span class="va">Y</span>, <span class="fl">2</span>, <span class="fu"><a href="https://rdrr.io/r/base/colSums.html">colMeans</a></span><span class="op">(</span><span class="va">Y</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">as.matrix</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">SSP_T</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/crossprod.html">crossprod</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">as.matrix</a></span><span class="op">(</span><span class="va">Ydev</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt;        start amount</span></span>
<span><span class="co">#&gt; start   35.4  -59.2</span></span>
<span><span class="co">#&gt; amount -59.2  975.9</span></span>
<span></span>
<span><span class="va">fitted</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">dogfood.mod</span><span class="op">)</span></span>
<span><span class="va">Yfit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sweep.html">sweep</a></span><span class="op">(</span><span class="va">fitted</span>, <span class="fl">2</span>, <span class="fu"><a href="https://rdrr.io/r/base/colSums.html">colMeans</a></span><span class="op">(</span><span class="va">fitted</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">as.matrix</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">SSP_H</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/crossprod.html">crossprod</a></span><span class="op">(</span><span class="va">Yfit</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt;         start amount</span></span>
<span><span class="co">#&gt; start    9.69  -70.9</span></span>
<span><span class="co">#&gt; amount -70.94  585.7</span></span>
<span></span>
<span><span class="va">residuals</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span><span class="va">dogfood.mod</span><span class="op">)</span></span>
<span><span class="va">SSP_E</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/crossprod.html">crossprod</a></span><span class="op">(</span><span class="va">residuals</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt;        start amount</span></span>
<span><span class="co">#&gt; start   25.8   11.7</span></span>
<span><span class="co">#&gt; amount  11.7  390.3</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The decomposition of the total sum of squares and products in <a href="#eq-SSP" class="quarto-xref">Equation&nbsp;<span>10.2</span></a> can be shown as:</p>
<p><span class="math display">\[
\overset{\mathbf{SSP}_T}
  {\begin{pmatrix}
   35.4 &amp; -59.2 \\
  -59.2 &amp; 975.9 \\
  \end{pmatrix}}
=
\overset{\mathbf{SSP}_H}
  {\begin{pmatrix}
    9.69 &amp; -70.94 \\
  -70.94 &amp; 585.69 \\
  \end{pmatrix}}
+
\overset{\mathbf{SSP}_E}
  {\begin{pmatrix}
   25.8 &amp;  11.8 \\
   11.8 &amp; 390.3 \\
  \end{pmatrix}}
\]</span></p>
</section><section id="how-big-is-ss_h-compared-to-ss_e" class="level3" data-number="10.2.3"><h3 data-number="10.2.3" class="anchored" data-anchor-id="how-big-is-ss_h-compared-to-ss_e">
<span class="header-section-number">10.2.3</span> How big is <span class="math inline">\(SS_H\)</span> compared to <span class="math inline">\(SS_E\)</span>?</h3>
<p>In a univariate response model, <span class="math inline">\(SS_H\)</span> and <span class="math inline">\(SS_E\)</span> are both scalar numbers and the univariate <span class="math inline">\(F\)</span> test statistic, <span class="math display">\[F = \frac{\text{SS}_H/\text{df}_h}{\text{SS}_E/\text{df}_e} = \frac{\mathsf{Var}(H)}{\mathsf{Var}(E)} \:\: ,
\]</span> assesses “how big” <span class="math inline">\(\text{SS}_H\)</span> is, relative to <span class="math inline">\(\text{SS}_E\)</span>, the variance accounted for by a hypothesized model or model terms relative to error variance. The measure <span class="math inline">\(R^2 = SS_H / (SS_H + SS_E) = SS_H / SS_T\)</span> gives the proportion of total variance accounted for by the model terms.</p>
<p>In the multivariate analog <span class="math inline">\(\mathbf{H}\)</span> and <span class="math inline">\(\mathbf{E}\)</span> are both <span class="math inline">\(p \times p\)</span> matrices, and <span class="math inline">\(\mathbf{H}\)</span> “divided by” <span class="math inline">\(\mathbf{E}\)</span> becomes <span class="math inline">\(\mathbf{H}\mathbf{E}^{-1}\)</span>. The answer, “how big” <span class="math inline">\(\text{SS}_H\)</span> is compared to <span class="math inline">\(\text{SS}_E\)</span> is expressed in terms of the <span class="math inline">\(p\)</span> eigenvalues <span class="math inline">\(\lambda_i, i = 1, 2, \dots p\)</span> of <span class="math inline">\(\mathbf{H}\mathbf{E}^{-1}\)</span>. These are the <span class="math inline">\(p\)</span> values <span class="math inline">\(\lambda\)</span> which solve the determinant equation <span class="math display">\[
\mathrm{det}(\mathbf{H}\mathbf{E}^{-1} - \lambda \mathbf{I}) = 0 \:\: .
\]</span> The solution also gives the <span class="math inline">\(\lambda_i\)</span> as the eigenvalues, with vectors <span class="math inline">\(\mathbf{v}_i\)</span> as the corresponding eigenvectors, <span id="eq-he-eigen"><span class="math display">\[
\mathbf{H}\mathbf{E}^{-1} \; \lambda_i = \lambda_i \mathbf{v}_i \:\: .
\tag{10.4}\]</span></span></p>
<p>This can also be expressed in terms of the size of <span class="math inline">\(\mathbf{H}\)</span> relative to total variation <span class="math inline">\((\mathbf{H}+ \mathbf{E})\)</span> as</p>
<p><span id="eq-he-eigen2"><span class="math display">\[
\mathbf{H}(\mathbf{H}+\mathbf{E}+)^{-1} \; \rho_i = \rho_i \mathbf{v}_i \:\: ,
\tag{10.5}\]</span></span></p>
<p>which has the same eigenvectors as <a href="#eq-he-eigen" class="quarto-xref">Equation&nbsp;<span>10.4</span></a> and the eigenvalues are <span class="math inline">\(\rho_i = \lambda_i / (1 + \lambda_i)\)</span>.</p>
<p>However, when the hypothesized model terms have <span class="math inline">\(\text{df}_h\)</span> degrees of freedom (columns of the <span class="math inline">\(\mathbf{X}\)</span> matrix for that term), <span class="math inline">\(\mathbf{H}\)</span> is of rank <span class="math inline">\(\text{df}_h\)</span>, so only <span class="math inline">\(s=\min(p, \text{df}_h)\)</span> eigenvalues can be non-zero. For example, a test for a hypothesis about a single quantitative predictor <span class="math inline">\(\mathbf{x}\)</span>, has <span class="math inline">\(\text{df}_h = 1\)</span> degree of freedom and <span class="math inline">\(\mathrm{rank} (\mathbf{H}) = 1\)</span>; for a factor with <span class="math inline">\(g\)</span> groups, <span class="math inline">\(\text{df}_h = \mathrm{rank} (\mathbf{H}) = g-1\)</span>.</p>
<p>For the <code>dogfood</code> data, we get the following results:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb9" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">HEinv</span> <span class="op">&lt;-</span> <span class="va">SSP_H</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/solve.html">solve</a></span><span class="op">(</span><span class="va">SSP_E</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt;         start amount</span></span>
<span><span class="co">#&gt; start   0.466 -0.196</span></span>
<span><span class="co">#&gt; amount -3.488  1.606</span></span>
<span><span class="va">eig</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/eigen.html">eigen</a></span><span class="op">(</span><span class="va">HEinv</span><span class="op">)</span></span>
<span><span class="va">eig</span><span class="op">$</span><span class="va">values</span></span>
<span><span class="co">#&gt; [1] 2.0396 0.0317</span></span>
<span></span>
<span><span class="co"># as proportions</span></span>
<span><span class="va">eig</span><span class="op">$</span><span class="va">values</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">eig</span><span class="op">$</span><span class="va">values</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 0.9847 0.0153</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The factor <code>formula</code> has four levels and therefore <span class="math inline">\(\text{df}_h = 3\)</span> degrees of freedom. But there are only <span class="math inline">\(p = 2\)</span> responses, so there are <span class="math inline">\(s=\min(p, \text{df}_h) = 2\)</span> eigenvalues (and corresponding eigenvectors). The eigenvalues tell us that 98.5% of the hypothesis variance due to <code>formula</code> can be accounted for by a single dimension.</p>
<!-- This -->
<!-- has a direct multivariate analog in terms of -->
<!-- the $s=\min(p, df_h)$ non-zero latent roots (eigenvalues), $\lambda_i$, of $\mat{H}\mat{E}^{-1}$ -->
<!-- ($\mathbf{H}$ "divided by" $\mathbf{E}$); that is, the values $\lambda_i$ that solve -->
<!-- $$ -->
<!--  \det{ ( \mathbf{H}\mathbf{E}^{-1} - \lambda \mathbf{I} )} = 0 \Longrightarrow  -->
<!--  \mathbf{H}\mathbf{E}^{-1} \lambda_i = \lambda_i \mathbf{v}_i \period -->
<!-- $$ -->
<p>The overall multivariate test for the model in <a href="#eq-mlm" class="quarto-xref">Equation&nbsp;<span>10.1</span></a> is essentially a test of the hypothesis <span class="math inline">\(\mathcal{H}_0: \mathbf{B} = 0\)</span> (excluding the row for the intercept). Equivalently, this is a test based on the <em>incremental</em> <span class="math inline">\(\mathbf{SSP}_{H}\)</span> for the hypothesized terms in the model—that is, the difference between the <span class="math inline">\(\mathbf{SSP}_{H}\)</span> for the full model and the null, intercept-only model. The same idea can be applied to test the difference between any pair of <em>nested</em> models—the added contribution of terms in a larger model relative to a smaller model containing a subset of terms.</p>
<p>The eigenvectors <span class="math inline">\(\mathbf{v}_i\)</span> in <a href="#eq-he-eigen" class="quarto-xref">Equation&nbsp;<span>10.4</span></a> are also important. These are the weights for the variables in a linear combination <span class="math inline">\(v_{i1} \mathbf{y}_1 + v_{i2} \mathbf{y}_2 + \cdots + v_{ip} \mathbf{y}_p\)</span> which produces the largest univariate <span class="math inline">\(F\)</span> statistic for the <span class="math inline">\(i\)</span>-th dimension. We exploit this in canonical discriminant analysis and the corresponding canonical HE plots (<a href="11-mlm-viz.html#sec-candisc" class="quarto-xref"><span>Section 11.2</span></a>).</p>
<p>The eigenvectors of <span class="math inline">\(\mathbf{H}\mathbf{E}^{-1}\)</span> for the dogfood model are shown below:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb10" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">eig</span><span class="op">$</span><span class="va">vectors</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">HEinv</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">eig</span><span class="op">$</span><span class="va">vectors</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">"Dim"</span>, <span class="fl">1</span><span class="op">:</span><span class="fl">2</span><span class="op">)</span></span>
<span><span class="va">eig</span><span class="op">$</span><span class="va">vectors</span></span>
<span><span class="co">#&gt;         Dim 1  Dim 2</span></span>
<span><span class="co">#&gt; start   0.123 -0.411</span></span>
<span><span class="co">#&gt; amount -0.992 -0.911</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The first column corresponds to the weighted sum <span class="math inline">\(0.12 \times\text{start} - 0.99 \times \text{amount}\)</span>, which as we saw above accounts for 95.5% of the differences in the group means.</p>
</section></section><section id="multivariate-test-statistics" class="level2" data-number="10.3"><h2 data-number="10.3" class="anchored" data-anchor-id="multivariate-test-statistics">
<span class="header-section-number">10.3</span> Multivariate test statistics</h2>
<p>In the univariate case, the overall <span class="math inline">\(F\)</span>-test of <span class="math inline">\(\mathcal{H}_0: \boldsymbol{\beta} = \mathbf{0}\)</span> is the uniformly most powerful invariant test when the assumptions are met. There is nothing better. This is not the case in the MLM.</p>
<p>The reason is that when there are <span class="math inline">\(p &gt; 1\)</span> response variables, and we are testing a hypothesis comprising <span class="math inline">\(\text{df}_h &gt;1\)</span> coefficients or degrees of freedom, there are <span class="math inline">\(s &gt; 1\)</span> possible dimensions in which <span class="math inline">\(\mathbf{H}\)</span> can be large relative to <span class="math inline">\(\mathbf{E}\)</span>, each measured by the eigenvalue <span class="math inline">\(\lambda_i\)</span>. There are several test statistics that combine these into a single measure, shown in <a href="#tbl-mstats" class="quarto-xref">Table&nbsp;<span>10.1</span></a>.</p>
<!-- $$ -->
<!-- \begin{align*} -->
<!-- \text{Wilks's Lambda} \quad & \Lambda = \prod^s_i \frac{1}{1+\lambda_i} \quad\quad  && \eta^2 = 1-\Lambda^{1/s} \\ -->
<!-- \text{Pillai trace} \quad &   V = \sum^s_i \frac{\lambda_i}{1+\lambda_i} \quad  && \eta^2 = \frac{V}{s}     \\ -->
<!-- \text{Hotelling-Lawley trace} \quad &  H = \sum^s_i \lambda_i \quad\quad   && \eta^2 = \frac{H}{H+s}   \\ -->
<!-- \text{Roy's maximum root} \quad &  R = \lambda_1   \quad\quad         &&  \eta^2 = \frac{\lambda_1}{1+\lambda_1}  \\ -->
<!-- \end{align*} -->
<!-- $$ -->
<div id="tbl-mstats" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mstats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10.1: Test statistics for multivariate tests combine the size of dimensions of <span class="math inline">\(\mathbf{H}\mathbf{E}^{-1}\)</span> into a single measure.
</figcaption><div aria-describedby="tbl-mstats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="center">
<table class="table">
<thead><tr class="header">
<th style="text-align: left;">Criterion</th>
<th style="text-align: left;">Formula</th>
<th style="text-align: left;">Partial <span class="math inline">\(\eta^2\)</span>
</th>
<th style="text-align: left;"></th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Wilks’s <span class="math inline">\(\Lambda\)</span>
</td>
<td style="text-align: left;"><span class="math inline">\(\Lambda = \prod^s_i \frac{1}{1+\lambda_i}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\eta^2 = 1-\Lambda^{1/s}\)</span></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Pillai trace</td>
<td style="text-align: left;"><span class="math inline">\(V = \sum^s_i \frac{\lambda_i}{1+\lambda_i}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\eta^2 = \frac{V}{s}\)</span></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hotelling-Lawley trace</td>
<td style="text-align: left;"><span class="math inline">\(H = \sum^s_i \lambda_i\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\eta^2 = \frac{H}{H+s}\)</span></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Roy maximum root</td>
<td style="text-align: left;"><span class="math inline">\(R = \lambda_1\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\eta^2 = \frac{\lambda_1}{1+\lambda_1}\)</span></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
<p>These correspond to different kinds of “means” of the <span class="math inline">\(\lambda_i\)</span>: geometric (Wilks), arithmetic (Pillai), harmonic (Hotelling-Lawley) and supremum (Roy). See <span class="citation" data-cites="Friendly-etal:ellipses:2013">Friendly et al. (<a href="95-references.html#ref-Friendly-etal:ellipses:2013" role="doc-biblioref">2013</a>)</span> for the geometry behind these measures.</p>
<p>Each of these statistics have different sampling distributions under the null hypothesis, but they can all be converted to <span class="math inline">\(F\)</span> statistics. These are exact when <span class="math inline">\(s \le 2\)</span>, and approximations otherwise. As well, each has an analog of the <span class="math inline">\(R^2\)</span>-like partial <span class="math inline">\(\eta^2\)</span> measure, giving the partial association accounted for by each term in the MLM.</p>
<section id="testing-contrasts-and-linear-hypotheses" class="level3" data-number="10.3.1"><h3 data-number="10.3.1" class="anchored" data-anchor-id="testing-contrasts-and-linear-hypotheses">
<span class="header-section-number">10.3.1</span> Testing contrasts and linear hypotheses</h3>
<p>Even more generally, these multivariate tests apply to <em>every</em> linear hypothesis concerning the coefficients in <span class="math inline">\(\mathbf{B}\)</span>. Suppose we want to test the hypothesis that a subset of rows (predictors) and/or columns (responses) simultaneously have null effects. This can be expressed in the general linear test, <span class="math display">\[
\mathcal{H}_0 : \mathbf{C}_{h \times q} \, \mathbf{B}_{q \times p} = \mathbf{0}_{h \times p} \:\: ,
\]</span> where <span class="math inline">\(\mathbf{C}\)</span> is a full rank <span class="math inline">\(h \le q\)</span> hypothesis matrix of constants, that selects subsets or linear combinations (contrasts) of the coefficients in <span class="math inline">\(\mathbf{B}\)</span> to be tested in a <span class="math inline">\(h\)</span> degree-of-freedom hypothesis.</p>
<p>In this case, the SSP matrix for the hypothesis has the form <span id="eq-hmat"><span class="math display">\[
\mathbf{H}  =
(\mathbf{C} \widehat{\mathbf{B}})^\mathsf{T}\,
[\mathbf{C} (\mathbf{X}^\mathsf{T}\mathbf{X} )^{-1} \mathbf{C}^\mathsf{T}]^{-1} \,
(\mathbf{C} \widehat{\mathbf{B}}) \:\: ,
\tag{10.6}\]</span></span></p>
<p>where there are <span class="math inline">\(s = \min(h, p)\)</span> non-zero eigenvalues of <span class="math inline">\(\mathbf{H}\mathbf{E}^{-1}\)</span>. In <a href="#eq-hmat" class="quarto-xref">Equation&nbsp;<span>10.6</span></a>, <span class="math inline">\(\mathbf{H}\)</span> measures the (Mahalanobis) squared distances (and cross products) among the linear combinations <span class="math inline">\(\mathbf{C} \widehat{\mathbf{B}}\)</span> from the origin under the null hypothesis. <!-- An animated display of these ideas and the relations between data ellipses and HE plots can be seen at --> <!-- [https://www.datavis.ca/gallery/animation/manova/](https://www.datavis.ca/gallery/animation/manova/). --></p>
<p>For example, with three responses <span class="math inline">\(y_1, y_2, y_3\)</span> and three predictors <span class="math inline">\(x_1, x_2, x_3\)</span>, we can test the hypothesis that neither <span class="math inline">\(x_2\)</span> nor <span class="math inline">\(x_3\)</span> contribute at all to predicting the <span class="math inline">\(y\)</span>s in terms of the hypothesis that the coefficients for the corresponding rows of <span class="math inline">\(\mathbf{B}\)</span> are zero using a 1-row <span class="math inline">\(\mathbf{C}\)</span> matrix that simply selects those rows:</p>
<!-- $$ -->
<!-- \mathcal{H}_0 : \mathbf{C} \mathbf{B} =  -->
<!-- \begin{bmatrix} -->
<!-- 0 & 1 & 1 & 0 -->
<!-- \end{bmatrix} -->
<!-- \begin{pmatrix} -->
<!--  \beta_{0,y_1} & \beta_{0,y_2} & \beta_{0,y_3} \\  -->
<!--  \beta_{1,y_1} & \beta_{1,y_2} & \beta_{1,y_3} \\  -->
<!--  \beta_{2,y_1} & \beta_{2,y_2} & \beta_{2,y_3} \\  -->
<!--  \beta_{3,y_1} & \beta_{3,y_2} & \beta_{3,y_3}  -->
<!-- \end{pmatrix} -->
<!-- = -->
<!-- \begin{bmatrix} -->
<!--  \beta_{1,y_1} & \beta_{1,y_2} & \beta_{1,y_3} \\  -->
<!--  \beta_{2,y_1} & \beta_{2,y_2} & \beta_{2,y_3} \\  -->
<!-- \end{bmatrix} -->
<!-- =  -->
<!-- \mathbf{0}_{(2 \times 3)} -->
<!-- $$ -->
<p><span class="math display">\[\begin{aligned}
\mathcal{H}_0 : \mathbf{C} \mathbf{B} &amp; =
\begin{bmatrix}
0 &amp; 1 &amp; 1 &amp; 0
\end{bmatrix}
\begin{pmatrix}
  \beta_{0,y_1} &amp; \beta_{0,y_2} &amp; \beta_{0,y_3} \\
  \beta_{1,y_1} &amp; \beta_{1,y_2} &amp; \beta_{1,y_3} \\
  \beta_{2,y_1} &amp; \beta_{2,y_2} &amp; \beta_{2,y_3} \\
  \beta_{3,y_1} &amp; \beta_{3,y_2} &amp; \beta_{3,y_3}
\end{pmatrix} \\ \\
&amp; =
\begin{bmatrix}
  \beta_{1,y_1} &amp; \beta_{1,y_2} &amp; \beta_{1,y_3} \\
  \beta_{2,y_1} &amp; \beta_{2,y_2} &amp; \beta_{2,y_3} \\
\end{bmatrix}
=
\mathbf{0}_{(2 \times 3)}
\end{aligned}\]</span></p>
<p>In MANOVA designs, it is often desirable to follow up a significant effect for a factor with subsequent tests to determine which groups differ. While you can simply test for all pairwise differences among groups (using Bonferonni or other corrections for multiplicity), a more substantively-driven approach uses planned comparisons or <em>contrasts</em> among the factor levels.</p>
<p>For a factor with <span class="math inline">\(g\)</span> groups, a contrast is simply a comparison of the mean of one subset of groups against the mean of another subset. This is specified as a weighted sum, <span class="math inline">\(L\)</span> of the means with weights <span class="math inline">\(\mathbf{c}\)</span> that sum to zero,</p>
<p><span class="math display">\[
L = \mathbf{c}^\mathsf{T} \boldsymbol{\mu} = \sum_i c_i \mu_i \quad\text{such that}\quad \Sigma c_i = 0
\]</span> Two contrasts, <span class="math inline">\(\mathbf{c}_1\)</span> and <span class="math inline">\(\mathbf{c}_2\)</span> are <em>orthogonal</em> if the sum of products of their weights is zero, i.e., <span class="math inline">\(\mathbf{c}_1^\mathsf{T} \mathbf{c}_2 = \Sigma c_{1i} \times c_{2i} = 0\)</span>. When contrasts are placed as columns of a matrix <span class="math inline">\(\mathbf{C}\)</span>, they are all <em>mutually orthogonal</em> if each pair is orthogonal, which means <span class="math inline">\(\mathbf{C}^\top \mathbf{C}\)</span> is a diagonal matrix. Orthogonal contrasts correspond to statistically independent tests. This is nice because they reflect separate, non-overlapping research questions.</p>
<!-- For example, with $g=4$ groups representing the combinations of two drugs, A and B -->
<!-- given at low and high doses, we might want to compare -->
<!-- (a) the average of the drug A groups vs. the average of drug B; -->
<!-- (b) low vs. high for drug A; -->
<!-- (c) low vs. high for drug B. The contrasts that do this are: -->
<!-- \begin{align*} -->
<!-- L_1 & = (\mu_1 + \mu_2) - (\mu_1 + \mu_2) & \rightarrow\: & \mathbf{c}_1 =  -->
<!--     \begin{pmatrix}  -->
<!--      1 &  1 & -1 & -1  -->
<!--     \end{pmatrix} \\ -->
<!-- L_2 & = \mu_1 - \mu_2                     & \rightarrow\: & \mathbf{c}_2 =  -->
<!--     \begin{pmatrix}  -->
<!--      1 &  -1 & 0 & 0  -->
<!--     \end{pmatrix} \\ -->
<!-- L_3 & = \mu_3 - \mu_4                     & \rightarrow\: & \mathbf{c}_3 =  -->
<!--     \begin{pmatrix}  -->
<!--      0 &  0 & 1 & -1  -->
<!--     \end{pmatrix} -->
<!-- \end{align*} -->
<!-- **TODO**: Should use $\frac12$ here so contrast L_1 is mean diff -->
<p>For example, with the <span class="math inline">\(g=4\)</span> groups for the <code>dogfood</code> data, the company might want to test the following comparisons among the formulas Old, New, Major and Alps: (a) Ours vs.&nbsp;Theirs: The average of (Old, New) compared to (Major, Alps); (b) Old vs.&nbsp;New; (c) Major vs.&nbsp;Alps. The contrasts that do this are:</p>
<p><span class="math display">\[\begin{aligned}
L_1 &amp; = \textstyle{\frac12} (\mu_O + \mu_N) -
        \textstyle{\frac12} (\mu_M + \mu_A) &amp; \rightarrow\: &amp; \mathbf{c}_1 =
\textstyle{\frac12}
     \begin{pmatrix}
      1 &amp;  1 &amp; -1 &amp; -1
     \end{pmatrix} \\
L_2 &amp; = \mu_O - \mu_N                     &amp; \rightarrow\: &amp; \mathbf{c}_2 =
    \begin{pmatrix}
     1 &amp;  -1 &amp; 0 &amp; 0
    \end{pmatrix} \\
L_3 &amp; = \mu_M - \mu_A                     &amp; \rightarrow\: &amp; \mathbf{c}_3 =
    \begin{pmatrix}
     0 &amp;  0 &amp; 1 &amp; -1
    \end{pmatrix}
\end{aligned}\]</span></p>
<p>Note that these correspond to <em>nested dichotomies</em> among the four groups: first we compare groups (Old and New) against groups (Major and Alps), then subsequently within each of these sets. Nested dicontomy contrasts are always <em>orthogonal</em>, and therefore correspond to statistically independent tests. We are effectively taking a three degree-of-freedom question, “do the means differ?” and breaking it down into three separate 1 df tests that answer specific parts of that overall question.</p>
<p>In R, contrasts for a factor are specified as columns of matrix, each of which sums to zero. For this example, we can set this up by creating each as a vector and joining them as columns using <code><a href="https://rdrr.io/r/base/cbind.html">cbind()</a></code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb11" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">c1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,  <span class="fl">1</span>, <span class="op">-</span><span class="fl">1</span>, <span class="op">-</span><span class="fl">1</span><span class="op">)</span><span class="op">/</span><span class="fl">2</span>    <span class="co"># Old,New vs. Major,Alps</span></span>
<span><span class="va">c2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="op">-</span><span class="fl">1</span>,  <span class="fl">0</span>,  <span class="fl">0</span><span class="op">)</span>      <span class="co"># Old vs. New</span></span>
<span><span class="va">c3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,  <span class="fl">0</span>,  <span class="fl">1</span>, <span class="op">-</span><span class="fl">1</span><span class="op">)</span>      <span class="co"># Major vs. Alps</span></span>
<span><span class="va">C</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">c1</span>,<span class="va">c2</span>,<span class="va">c3</span><span class="op">)</span> </span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">C</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">dogfood</span><span class="op">$</span><span class="va">formula</span><span class="op">)</span></span>
<span></span>
<span><span class="va">C</span></span>
<span><span class="co">#&gt;         c1 c2 c3</span></span>
<span><span class="co">#&gt; Old    0.5  1  0</span></span>
<span><span class="co">#&gt; New    0.5 -1  0</span></span>
<span><span class="co">#&gt; Major -0.5  0  1</span></span>
<span><span class="co">#&gt; Alps  -0.5  0 -1</span></span>
<span></span>
<span><span class="co"># show they are mutually orthogonal</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="va">C</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="va">C</span></span>
<span><span class="co">#&gt;    c1 c2 c3</span></span>
<span><span class="co">#&gt; c1  1  0  0</span></span>
<span><span class="co">#&gt; c2  0  2  0</span></span>
<span><span class="co">#&gt; c3  0  0  2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For the <code>dogfood</code> data, with <code>formula</code> as the group factor, you can set up the analyses to use these contrasts by assigning the matrix <code>C</code> to <code><a href="https://rdrr.io/r/stats/contrasts.html">contrasts()</a></code> for that factor in the dataset itself. When the contrasts are changed, it is necessary to refit the model. The estimated coefficients then become the estimated mean differences for the contrasts.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb12" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/contrasts.html">contrasts</a></span><span class="op">(</span><span class="va">dogfood</span><span class="op">$</span><span class="va">formula</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="va">C</span></span>
<span><span class="va">dogfood.mod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">start</span>, <span class="va">amount</span><span class="op">)</span> <span class="op">~</span> <span class="va">formula</span>, </span>
<span>                  data<span class="op">=</span><span class="va">dogfood</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">dogfood.mod</span><span class="op">)</span></span>
<span><span class="co">#&gt;              start amount</span></span>
<span><span class="co">#&gt; (Intercept)  1.688  85.56</span></span>
<span><span class="co">#&gt; formulac1   -1.375  10.88</span></span>
<span><span class="co">#&gt; formulac2   -0.500   3.25</span></span>
<span><span class="co">#&gt; formulac3    0.125   1.88</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For example, Ours vs.&nbsp;Theirs estimated by <code>formulac1</code> takes 0.69 less time to start eating and eats 5.44 more on average.</p>
<p>For multivariate tests, when all contrasts are pairwise orthogonal, the overall test of a factor with <span class="math inline">\(\text{df}_h = g-1\)</span> degrees of freedom can be broken down into <span class="math inline">\(g-1\)</span> separate 1 df tests. This gives rise to a set of <span class="math inline">\(\text{df}_h\)</span> rank 1 <span class="math inline">\(\mathbf{H}\)</span> matrices that additively decompose the overall hypothesis SSCP matrix,</p>
<p><span id="eq-H-contrasts"><span class="math display">\[
\mathbf{H} = \mathbf{H}_1 + \mathbf{H}_2 + \cdots + \mathbf{H}_{\text{df}_h} \:\: ,
\tag{10.7}\]</span></span></p>
<p>exactly as the univariate <span class="math inline">\(\text{SS}_H\)</span> can be decomposed using orthogonal contrasts in an ANOVA.</p>
<p>You can test such contrasts or any other hypotheses involving linear combinations of the coefficients using <code><a href="https://rdrr.io/pkg/car/man/linearHypothesis.html">car::linearHypothesis</a></code>. Here, <code>"formulac1"</code> refers to the contrast <code>c1</code> for the difference between Ours and Theirs. Note that because this is a 1 df test, all four test statistics yield the same <span class="math inline">\(F\)</span> values.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb13" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">hyp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">dogfood.mod</span><span class="op">)</span><span class="op">)</span><span class="op">[</span><span class="op">-</span><span class="fl">1</span><span class="op">]</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] "formulac1" "formulac2" "formulac3"</span></span>
<span><span class="va">H1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/car/man/linearHypothesis.html">linearHypothesis</a></span><span class="op">(</span><span class="va">dogfood.mod</span>, <span class="va">hyp</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, title<span class="op">=</span><span class="st">"Ours vs. Theirs"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Sum of squares and products for the hypothesis:</span></span>
<span><span class="co">#&gt;         start amount</span></span>
<span><span class="co">#&gt; start    7.56  -59.8</span></span>
<span><span class="co">#&gt; amount -59.81  473.1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Sum of squares and products for error:</span></span>
<span><span class="co">#&gt;        start amount</span></span>
<span><span class="co">#&gt; start   25.8   11.7</span></span>
<span><span class="co">#&gt; amount  11.7  390.3</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Multivariate Tests: Ours vs. Theirs</span></span>
<span><span class="co">#&gt;                  Df test stat approx F num Df den Df Pr(&gt;F)   </span></span>
<span><span class="co">#&gt; Pillai            1     0.625     9.18      2     11 0.0045 **</span></span>
<span><span class="co">#&gt; Wilks             1     0.375     9.18      2     11 0.0045 **</span></span>
<span><span class="co">#&gt; Hotelling-Lawley  1     1.669     9.18      2     11 0.0045 **</span></span>
<span><span class="co">#&gt; Roy               1     1.669     9.18      2     11 0.0045 **</span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Similarly we can test the other two contrasts within these each of these two subsets, but I don’t print the results</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb14" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">H2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/car/man/linearHypothesis.html">linearHypothesis</a></span><span class="op">(</span><span class="va">dogfood.mod</span>, <span class="va">hyp</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>, </span>
<span>                       title<span class="op">=</span><span class="st">"Old vs. New"</span><span class="op">)</span></span>
<span><span class="va">H3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/car/man/linearHypothesis.html">linearHypothesis</a></span><span class="op">(</span><span class="va">dogfood.mod</span>, <span class="va">hyp</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span>, </span>
<span>                       title<span class="op">=</span><span class="st">"Alps vs. Major"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then, we can illustrate <a href="#eq-H-contrasts" class="quarto-xref">Equation&nbsp;<span>10.7</span></a> by extracting the 1 df <span class="math inline">\(\mathbf{H}\)</span> matrices (<code>SSPH</code>) from the results of <code>linearHypothesis</code>.</p>
<!-- this doesn't work -->
<p><span class="math display">\[
\overset{\mathbf{H}}
{\begin{pmatrix}
  9.7 &amp; -70.9 \\
-70.9 &amp; 585.7 \\
\end{pmatrix}}
=
\overset{\mathbf{H}_1}
{\begin{pmatrix}
  7.6 &amp; -59.8 \\
-59.8 &amp; 473.1 \\
\end{pmatrix}}
+
\overset{\mathbf{H}_2}
{\begin{pmatrix}
0.13 &amp;  1.88 \\
1.88 &amp; 28.12 \\
\end{pmatrix}}
+
\overset{\mathbf{H}_3}
{\begin{pmatrix}
  2 &amp; -13 \\
-13 &amp;  84 \\
\end{pmatrix}}
\]</span></p>
</section></section><section id="anova-rightarrow-manova" class="level2" data-number="10.4"><h2 data-number="10.4" class="anchored" data-anchor-id="anova-rightarrow-manova">
<span class="header-section-number">10.4</span> ANOVA <span class="math inline">\(\rightarrow\)</span> MANOVA</h2>
<p>Multivariate analysis of variance (MANOVA) generalizes the familiar ANOVA model to situations where there are two or more response variables. Unlike ANOVA, which focuses on discerning statistical differences in one continuous dependent variable influenced by an independent variable (or grouping variable), MANOVA considers several dependent variables at once. It integrates these variables into a single, composite variable through a weighted linear combination, allowing for a comprehensive analysis of how these dependent variables collectively vary with respect to the levels of the independent variable. Essentially, MANOVA investigates whether the grouping variable explains significant variations in the combined dependent variables.</p>
<p>The situation is illustrated in <a href="#fig-manova-diagram" class="quarto-xref">Figure&nbsp;<span>10.3</span></a> where there are two response measures, <span class="math inline">\(Y_1\)</span> and <span class="math inline">\(Y_2\)</span> with data collected for three groups. For concreteness, <span class="math inline">\(Y_1\)</span> might be a score on a math test and <span class="math inline">\(Y_2\)</span> might be a reading score. Let’s also say that group 1 has been studying Shakespeare, while group 2 has concentrated on physics, but group 3 has done nothing beyond the normal curriculum.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-manova-diagram" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-manova-diagram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/manova-diagram-anno.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-manova-diagram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.3: Data from simple MANOVA design involving three groups and two response measures, <span class="math inline">\(Y_1\)</span> and <span class="math inline">\(Y_2\)</span>, summarized by their data ellipses.
</figcaption></figure>
</div>
</div>
</div>
<p>As shown in the figure, the centroids, <span class="math inline">\((\mu_{1g}, \mu_{2g})\)</span>, clearly differ—the data ellipses barely overlap. A multivariate analysis would show a highly difference among groups. From a rough visual inspection, it seems that means differ on the math test <span class="math inline">\(Y_1\)</span>, with the physics group out-performing the other two. On the reading test <span class="math inline">\(Y_2\)</span> however it might turn out that the three group means don’t differ significantly in an ANOVA, but the Shakespeare and physics groups appear to outperform the normal curriculum group. Doing separate ANOVAs on these variables would miss what is so obvious from <a href="#fig-manova-diagram" class="quarto-xref">Figure&nbsp;<span>10.3</span></a>: there is wide separation among the groups in the two tests considered <em>jointly</em>.</p>
<p><a href="#fig-manova-response-dimensions" class="quarto-xref">Figure&nbsp;<span>10.4</span></a> illustrates a second important advantage of performing a multivariate analysis over separate ANOVAS: that of determining the number of dimensions or aspects along which groups differ. In the panel on the left, the means of the three groups increase nearly linearly on the combination of <span class="math inline">\(Y_1\)</span> and <span class="math inline">\(Y_2\)</span>, so their differences can be ascribed to a single dimension, which simplifies the interpretation.</p>
<p>For example, the groups here might be patients diagnosed as normal, mild schizophrenia and profound schizophrenia, and the measures could be tests of memory and attention. The obvious multivariate interpretation from the figure is that of increasing impairment of cognitive functioning across the groups, comprised by memory and attention. Note also the positive association <em>within</em> each group: those who perform better on the memory task also do better on attention.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-manova-response-dimensions" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-manova-response-dimensions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/manova-response-dimensions-anno.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-manova-response-dimensions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.4: A simple MANOVA design involving three groups and two response measures, <span class="math inline">\(Y_1\)</span> and <span class="math inline">\(Y_2\)</span>, but with different patterns of the differences among the group means. The red arrows suggest interpretations in terms of dimensions or aspects of the response variables.
</figcaption></figure>
</div>
</div>
</div>
<p>In contrast, the right panel of <a href="#fig-manova-response-dimensions" class="quarto-xref">Figure&nbsp;<span>10.4</span></a> shows a situation where the group means have a low correlation. Data like this might arise in a study of parental competency, where there are are measures of both the degree of caring (<span class="math inline">\(Y_1\)</span>) and time spent in play (<span class="math inline">\(Y_2\)</span>) by fathers and groups consisting of fathers of children with no disability, or a physical disability or a mental ability.</p>
<p>As can be seen in <a href="#fig-manova-response-dimensions" class="quarto-xref">Figure&nbsp;<span>10.4</span></a> fathers of the disabled children differ from those of the not disabled group in two different directions corresponding to being higher on either <span class="math inline">\(Y_1\)</span> or <span class="math inline">\(Y_2\)</span>. The <span style="color: red;">red</span> arrows suggest that the differences among groups could be interpreted in terms of two uncorrelated dimensions, perhaps labeled overall competency and emphasis on physical activity. (The pattern in <a href="#fig-manova-response-dimensions" class="quarto-xref">Figure&nbsp;<span>10.4</span></a> (right) is contrived for the sake of illustration; it does not reflect the data analyzed in the example below.)</p>
<section id="example-father-parenting-data" class="level3" data-number="10.4.1"><h3 data-number="10.4.1" class="anchored" data-anchor-id="example-father-parenting-data">
<span class="header-section-number">10.4.1</span> Example: Father parenting data</h3>
<p>I use a simple example of a three-group multivariate design to illustrate the basic ideas of fitting MLMs in R and testing hypotheses. Visualization methods using HE plots are discussed in <a href="11-mlm-viz.html" class="quarto-xref"><span>Chapter 11</span></a>.</p>
<p>The dataset <code><a href="https://friendly.github.io/heplots/reference/Parenting.html">heplots::Parenting</a></code> come from an exercise (10B) in <span class="citation" data-cites="Meyers-etal:2006">Meyers et al. (<a href="95-references.html#ref-Meyers-etal:2006" role="doc-biblioref">2006</a>)</span> and are probably contrived, but are modeled on a real study in which fathers were assessed on three subscales of a <em>Perceived Parenting Competence Scale</em>,</p>
<ul>
<li>
<code>caring</code>, caretaking responsibilities;</li>
<li>
<code>emotion</code>, emotional support provided to the child; and</li>
<li>
<code>play</code>, recreational time spent with the child.</li>
</ul>
<p>The dataset <code>Parenting</code> comprises 60 fathers selected from three <code>group</code>s of <span class="math inline">\(n = 20\)</span> each: (a) fathers of a child with <em>no disabilities</em> (<code>"Normal"</code>); (b) fathers with a <em>physically</em> disabled child; (c) fathers with a <em>mentally</em> disabled child. The design is thus a three-group MANOVA, with three response variables.</p>
<!-- NOTE: Use **typical** rather than "normal" -->
<p>The main questions concern whether the group means differ on these scales, and the nature of these differences. That is, do the means differ significantly on all three measures? Is there a consistent order of groups across these three aspects of parenting?</p>
<p>More specific questions are: (a) Do the fathers of typical children differ from the other two groups on average? (b) Do the physical and mental groups differ? These questions can be tested using contrasts, and are specified by assigning a matrix to <code>contrasts(Parenting$group)</code>; each column is a contrast whose values sum to zero. They are given labels <code>"group1"</code> (normal vs.&nbsp;other) and <code>"group2"</code> (physical vs.&nbsp;mental) in some output.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb15" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="va">Parenting</span>, package<span class="op">=</span><span class="st">"heplots"</span><span class="op">)</span></span>
<span><span class="va">C</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="op">-</span><span class="fl">.5</span>, <span class="op">-</span><span class="fl">.5</span>,</span>
<span>              <span class="fl">0</span>,  <span class="fl">1</span>,  <span class="op">-</span><span class="fl">1</span><span class="op">)</span>, </span>
<span>            nrow <span class="op">=</span> <span class="fl">3</span>, ncol <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt;      [,1] [,2]</span></span>
<span><span class="co">#&gt; [1,]  1.0    0</span></span>
<span><span class="co">#&gt; [2,] -0.5    1</span></span>
<span><span class="co">#&gt; [3,] -0.5   -1</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/contrasts.html">contrasts</a></span><span class="op">(</span><span class="va">Parenting</span><span class="op">$</span><span class="va">group</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="va">C</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="exploratory-plots" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="exploratory-plots">Exploratory plots</h4>
<p>Before setting up a model and testing, it is well-advised to examine the data graphically. The simplest plots are side-by-side boxplots (or violin plots) for the three responses. With <code>ggplot2</code>, this is easily done by reshaping the data to long format and using faceting. In <a href="#fig-parenting-boxpl" class="quarto-xref">Figure&nbsp;<span>10.5</span></a>, I’ve also plotted the group means with white dots.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>See the ggplot code</summary><div class="sourceCode" id="cb16" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">parenting_long</span> <span class="op">&lt;-</span> <span class="va">Parenting</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">tidyr</span><span class="fu">::</span><span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer</a></span><span class="op">(</span>cols<span class="op">=</span><span class="va">caring</span><span class="op">:</span><span class="va">play</span>, </span>
<span>                      names_to <span class="op">=</span> <span class="st">"variable"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">parenting_long</span>, </span>
<span>       <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">group</span>, y<span class="op">=</span><span class="va">value</span>, fill<span class="op">=</span><span class="va">group</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span>outlier.size<span class="op">=</span><span class="fl">2.5</span>, </span>
<span>               alpha<span class="op">=</span><span class="fl">.5</span>, </span>
<span>               outlier.alpha <span class="op">=</span> <span class="fl">0.9</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/stat_summary.html">stat_summary</a></span><span class="op">(</span>fun<span class="op">=</span><span class="va">mean</span>, </span>
<span>               color<span class="op">=</span><span class="st">"white"</span>, </span>
<span>               geom<span class="op">=</span><span class="st">"point"</span>, </span>
<span>               size<span class="op">=</span><span class="fl">2</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_hue.html">scale_fill_hue</a></span><span class="op">(</span>direction <span class="op">=</span> <span class="op">-</span><span class="fl">1</span><span class="op">)</span> <span class="op">+</span>     <span class="co"># reverse default colors</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>y <span class="op">=</span> <span class="st">"Scale value"</span>, x <span class="op">=</span> <span class="st">"Group"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span><span class="op">(</span><span class="op">~</span> <span class="va">variable</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span>base_size <span class="op">=</span> <span class="fl">14</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>legend.position<span class="op">=</span><span class="st">"top"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.text.x <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>angle <span class="op">=</span> <span class="fl">15</span>,</span>
<span>                                   hjust <span class="op">=</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div id="fig-parenting-boxpl" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-parenting-boxpl-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/ch10/fig-parenting-boxpl-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-parenting-boxpl-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.5: Faceted boxplots of scores on the three parenting scales, showing also the mean for each.
</figcaption></figure>
</div>
</div>
</div>
<p>In this figure, differences among the groups on <code>play</code> are most apparent, with fathers of non-disabled children scoring highest. Differences among the groups on <code>emotion</code> are very small, but one high outlier for the fathers of mentally disabled children is apparent. On <code>caring</code>, fathers of children with a physical disability stand out as highest.</p>
<p>For exploratory purposes, you might also make a scatterplot matrix. Here, because the MLM assumes homogeneity of the variances and covariance matrices <span class="math inline">\(\mathbf{S}_i\)</span>, I show only the data ellipses in scatterplot matrix format, using <code>heplots:covEllipses()</code> (with 50% coverage, for clarity):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb17" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">colors</span> <span class="op">&lt;-</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/pal_hue.html">hue_pal</a></span><span class="op">(</span><span class="op">)</span><span class="op">(</span><span class="fl">3</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/rev.html">rev</a></span><span class="op">(</span><span class="op">)</span>  <span class="co"># match color use in ggplot</span></span>
<span><span class="fu"><a href="https://friendly.github.io/heplots/reference/covEllipses.html">covEllipses</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">caring</span>, <span class="va">play</span>, <span class="va">emotion</span><span class="op">)</span> <span class="op">~</span> <span class="va">group</span>, data<span class="op">=</span><span class="va">Parenting</span>,</span>
<span>  variables <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fl">3</span>,</span>
<span>  fill <span class="op">=</span> <span class="cn">TRUE</span>, fill.alpha <span class="op">=</span> <span class="fl">0.2</span>,</span>
<span>  pooled <span class="op">=</span> <span class="cn">FALSE</span>,</span>
<span>  level <span class="op">=</span> <span class="fl">0.50</span>, </span>
<span>  col <span class="op">=</span> <span class="va">colors</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-parenting-covEllipses" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-parenting-covEllipses-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/ch10/fig-parenting-covEllipses-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-parenting-covEllipses-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.6: Bivariate data ellipses for pairs of the three responses, showing the means, correlations and variances for the three groups.
</figcaption></figure>
</div>
</div>
</div>
<p>If the covariance matrices were all the same, the data ellipses would have roughly the same size and orientation, but that is not the case in <a href="#fig-parenting-covEllipses" class="quarto-xref">Figure&nbsp;<span>10.6</span></a>. The normal group shows greater variability overall and the correlations among the measures differ somewhat from group to group. We’ll assess later whether this makes a difference in the conclusions that can be drawn (<a href="12-eqcov.html" class="quarto-xref"><span>Chapter 12</span></a>). The group centroids also differ, but the pattern is not particularly clear. We’ll see an easier to understand view in HE plots and their canonical discriminant cousins.</p>
</section><section id="testing-the-model" class="level4 nunumbered" data-number="10.4.1.1"><h4 class="nunumbered anchored" data-number="10.4.1.1" data-anchor-id="testing-the-model">
<span class="header-section-number">10.4.1.1</span> Testing the model</h4>
<p>Let’s proceed to fit the multivariate model predicting all three scales from the <code>group</code> factor. <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> for a multivariate response returns an object of class <code>"mlm"</code>, for which there are many methods (use <code>methods(class="mlm")</code> to find them).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb18" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">parenting.mlm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">caring</span>, <span class="va">play</span>, <span class="va">emotion</span><span class="op">)</span> <span class="op">~</span> <span class="va">group</span>, </span>
<span>                    data<span class="op">=</span><span class="va">Parenting</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; lm(formula = cbind(caring, play, emotion) ~ group, data = Parenting)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients:</span></span>
<span><span class="co">#&gt;              caring   play     emotion</span></span>
<span><span class="co">#&gt; (Intercept)   5.8833   4.6333   5.9167</span></span>
<span><span class="co">#&gt; group1       -0.3833   2.4167  -0.0667</span></span>
<span><span class="co">#&gt; group2        1.7750  -0.2250  -0.6000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The coefficients in this model are the values of the contrasts set up above. <code>group1</code> is the mean of the typical group minus the average of the other two, which is negative on <code>caring</code> and <code>emotion</code> but positive for <code>play</code>. <code>group2</code> is the difference in means for the physical vs.&nbsp;mental groups.</p>
<p>Before doing multivariate tests, it is useful to see what would happen if we ran univariate ANOVAs on each of the responses. These can be extracted from an MLM using <code><a href="https://rdrr.io/r/stats/summary.aov.html">stats::summary.aov()</a></code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb19" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/summary.aov.html">summary.aov</a></span><span class="op">(</span><span class="va">parenting.mlm</span><span class="op">)</span></span>
<span><span class="co">#&gt;  Response caring :</span></span>
<span><span class="co">#&gt;             Df Sum Sq Mean Sq F value Pr(&gt;F)    </span></span>
<span><span class="co">#&gt; group        2    130    65.2    18.6  6e-07 ***</span></span>
<span><span class="co">#&gt; Residuals   57    200     3.5                   </span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  Response play :</span></span>
<span><span class="co">#&gt;             Df Sum Sq Mean Sq F value Pr(&gt;F)    </span></span>
<span><span class="co">#&gt; group        2    177    88.6    27.6  4e-09 ***</span></span>
<span><span class="co">#&gt; Residuals   57    183     3.2                   </span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  Response emotion :</span></span>
<span><span class="co">#&gt;             Df Sum Sq Mean Sq F value Pr(&gt;F)</span></span>
<span><span class="co">#&gt; group        2     15    7.27    1.02   0.37</span></span>
<span><span class="co">#&gt; Residuals   57    408    7.16</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If you like, you can also extract the univariate model fit statistics from the <code>"mlm" using the</code>broom::glance()` method for a multivariate model object.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb20" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://generics.r-lib.org/reference/glance.html">glance</a></span><span class="op">(</span><span class="va">parenting.mlm</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">response</span>, <span class="va">r.squared</span>, <span class="va">fstatistic</span>, <span class="va">p.value</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 3 × 4</span></span>
<span><span class="co">#&gt;   response r.squared fstatistic       p.value</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;        &lt;dbl&gt;      &lt;dbl&gt;         &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 caring      0.395       18.6  0.000000602  </span></span>
<span><span class="co">#&gt; 2 play        0.492       27.6  0.00000000405</span></span>
<span><span class="co">#&gt; 3 emotion     0.0344       1.02 0.369</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>From this, one might conclude that there are differences only in <code>caring</code> and <code>play</code> and therefore ignore <code>emotion</code>, but this would be short-sighted. <code><a href="https://rdrr.io/pkg/car/man/Anova.html">car::Anova()</a></code>, shown below, gives the overall multivariate test <span class="math inline">\(\mathcal{H}_0: \mathbf{B} = 0\)</span> of the <code>group</code> effect, that the groups don’t differ on <em>any</em> of the response variables. Note that this has a much smaller <span class="math inline">\(p\)</span>-value than any of the univariate <span class="math inline">\(F\)</span> tests.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb21" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/car/man/Anova.html">Anova</a></span><span class="op">(</span><span class="va">parenting.mlm</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Type II MANOVA Tests: Pillai test statistic</span></span>
<span><span class="co">#&gt;       Df test stat approx F num Df den Df Pr(&gt;F)    </span></span>
<span><span class="co">#&gt; group  2     0.948     16.8      6    112  9e-14 ***</span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code><a href="https://rdrr.io/pkg/car/man/Anova.html">Anova()</a></code> returns an object of class <code>"Anova.mlm"</code> which has various methods. The <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> method for this gives more details, including all four test statistics. With <span class="math inline">\(p=3\)</span> responses, these tests have <span class="math inline">\(s = \min(p, \text{df}_h) = \min(3,2) = 2\)</span> dimensions and the <span class="math inline">\(F\)</span> approximations are <em>not</em> equivalent here. All four tests are highly significant, with Roy’s test giving the largest <span class="math inline">\(F\)</span> statistic.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb22" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">parenting.summary</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/car/man/Anova.html">Anova</a></span><span class="op">(</span><span class="va">parenting.mlm</span><span class="op">)</span> <span class="op">|&gt;</span>  <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="op">)</span> </span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">parenting.summary</span>, SSP<span class="op">=</span><span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Type II MANOVA Tests:</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; ------------------------------------------</span></span>
<span><span class="co">#&gt;  </span></span>
<span><span class="co">#&gt; Term: group </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Multivariate Tests: group</span></span>
<span><span class="co">#&gt;                  Df test stat approx F num Df den Df  Pr(&gt;F)    </span></span>
<span><span class="co">#&gt; Pillai            2     0.948     16.8      6    112 9.0e-14 ***</span></span>
<span><span class="co">#&gt; Wilks             2     0.274     16.7      6    110 1.3e-13 ***</span></span>
<span><span class="co">#&gt; Hotelling-Lawley  2     1.840     16.6      6    108 1.8e-13 ***</span></span>
<span><span class="co">#&gt; Roy               2     1.108     20.7      3     56 3.8e-09 ***</span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> method by default prints the SSH = <span class="math inline">\(\mathbf{H}\)</span> and SSE = <span class="math inline">\(\mathbf{E}\)</span> matrices, but I suppressed them above. The data structure returned contains nested elements which can be extracted more easily from the object using <code><a href="https://purrr.tidyverse.org/reference/pluck.html">purrr::pluck()</a></code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb23" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">H</span> <span class="op">&lt;-</span> <span class="va">parenting.summary</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">purrr</span><span class="fu">::</span><span class="fu"><a href="https://purrr.tidyverse.org/reference/pluck.html">pluck</a></span><span class="op">(</span><span class="st">"multivariate.tests"</span>, <span class="st">"group"</span>, <span class="st">"SSPH"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt;         caring    play emotion</span></span>
<span><span class="co">#&gt; caring   130.4 -43.767 -41.833</span></span>
<span><span class="co">#&gt; play     -43.8 177.233   0.567</span></span>
<span><span class="co">#&gt; emotion  -41.8   0.567  14.533</span></span>
<span><span class="va">E</span> <span class="op">&lt;-</span> <span class="va">parenting.summary</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">purrr</span><span class="fu">::</span><span class="fu"><a href="https://purrr.tidyverse.org/reference/pluck.html">pluck</a></span><span class="op">(</span><span class="st">"multivariate.tests"</span>, <span class="st">"group"</span>, <span class="st">"SSPE"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt;         caring  play emotion</span></span>
<span><span class="co">#&gt; caring   199.8 -45.8    35.2</span></span>
<span><span class="co">#&gt; play     -45.8 182.7    80.6</span></span>
<span><span class="co">#&gt; emotion   35.2  80.6   408.0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="linear-hypotheses-contrasts" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="linear-hypotheses-contrasts">Linear hypotheses &amp; contrasts</h4>
<p>With three or more groups or with a more complex MANOVA design, contrasts provide a way of testing questions of substantive interest regarding differences among group means.</p>
<p>The test of the contrast comparing the typical group to the average of the others is the test using the contrast <span class="math inline">\(c_1 = (1, -\frac12, -\frac12)\)</span> which produces the coefficients labeled <code>"group1"</code>. The function <code><a href="https://rdrr.io/pkg/car/man/linearHypothesis.html">car::linearHypothesis()</a></code> carries out the multivariate test that this difference is zero. This is a 1 df test, so all four test statistics produce the same <span class="math inline">\(F\)</span> and <span class="math inline">\(p\)</span>-values.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb24" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">parenting.mlm</span><span class="op">)</span><span class="op">[</span><span class="st">"group1"</span>,<span class="op">]</span></span>
<span><span class="co">#&gt;  caring    play emotion </span></span>
<span><span class="co">#&gt; -0.3833  2.4167 -0.0667</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/car/man/linearHypothesis.html">linearHypothesis</a></span><span class="op">(</span><span class="va">parenting.mlm</span>, <span class="st">"group1"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span>SSP<span class="op">=</span><span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Multivariate Tests: </span></span>
<span><span class="co">#&gt;                  Df test stat approx F num Df den Df  Pr(&gt;F)    </span></span>
<span><span class="co">#&gt; Pillai            1     0.521     19.9      3     55 7.1e-09 ***</span></span>
<span><span class="co">#&gt; Wilks             1     0.479     19.9      3     55 7.1e-09 ***</span></span>
<span><span class="co">#&gt; Hotelling-Lawley  1     1.088     19.9      3     55 7.1e-09 ***</span></span>
<span><span class="co">#&gt; Roy               1     1.088     19.9      3     55 7.1e-09 ***</span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Similarly, the difference between the physical and mental groups uses the contrast <span class="math inline">\(c_2 = (0, 1, -1)\)</span> and the test that these means are equal is given by <code><a href="https://rdrr.io/pkg/car/man/linearHypothesis.html">linearHypothesis()</a></code> applied to <code>group2</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb25" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">parenting.mlm</span><span class="op">)</span><span class="op">[</span><span class="st">"group2"</span>,<span class="op">]</span></span>
<span><span class="co">#&gt;  caring    play emotion </span></span>
<span><span class="co">#&gt;   1.775  -0.225  -0.600</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/car/man/linearHypothesis.html">linearHypothesis</a></span><span class="op">(</span><span class="va">parenting.mlm</span>, <span class="st">"group2"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span>SSP<span class="op">=</span><span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Multivariate Tests: </span></span>
<span><span class="co">#&gt;                  Df test stat approx F num Df den Df Pr(&gt;F)    </span></span>
<span><span class="co">#&gt; Pillai            1     0.429     13.8      3     55  8e-07 ***</span></span>
<span><span class="co">#&gt; Wilks             1     0.571     13.8      3     55  8e-07 ***</span></span>
<span><span class="co">#&gt; Hotelling-Lawley  1     0.752     13.8      3     55  8e-07 ***</span></span>
<span><span class="co">#&gt; Roy               1     0.752     13.8      3     55  8e-07 ***</span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code><a href="https://rdrr.io/pkg/car/man/linearHypothesis.html">linearHypothesis()</a></code> is very general. The second argument (<code>hypothesis.matrix</code>) corresponds to <span class="math inline">\(\mathbf{C}\)</span>, and can be specified as numeric matrix giving the linear combinations of coefficients by rows to be tested, or a character vector giving the hypothesis in symbolic form; <code>"group1"</code> is equivalent to <code>"group1 = 0"</code>.</p>
<p>Because the two contrasts used here are orthogonal, they add together to give the overall test of <span class="math inline">\(\mathbf{B} = \mathbf{0}\)</span>, which implies that the means of the three groups are all equal. The test below gives the same results as <code>Anova(parenting.mlm)</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb26" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/car/man/linearHypothesis.html">linearHypothesis</a></span><span class="op">(</span><span class="va">parenting.mlm</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"group1"</span>, <span class="st">"group2"</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span>SSP<span class="op">=</span><span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Multivariate Tests: </span></span>
<span><span class="co">#&gt;                  Df test stat approx F num Df den Df  Pr(&gt;F)    </span></span>
<span><span class="co">#&gt; Pillai            2     0.948     16.8      6    112 9.0e-14 ***</span></span>
<span><span class="co">#&gt; Wilks             2     0.274     16.7      6    110 1.3e-13 ***</span></span>
<span><span class="co">#&gt; Hotelling-Lawley  2     1.840     16.6      6    108 1.8e-13 ***</span></span>
<span><span class="co">#&gt; Roy               2     1.108     20.7      3     56 3.8e-09 ***</span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section></section><section id="ordered-factors" class="level3" data-number="10.4.2"><h3 data-number="10.4.2" class="anchored" data-anchor-id="ordered-factors">
<span class="header-section-number">10.4.2</span> Ordered factors</h3>
<p>When groups are defined by an ordered factor, such as level of physical fitness (rated 1–5) or grade in school, it is tempting to treat that as a numeric variable and use a multivariate regression model. This would assume that the effect of that factor is linear and if not, we might consider adding polynomial terms. A different strategy, often preferable, is to make the group variable an <em>ordered factor</em>, for which R assigns <em>polynomial contrasts</em>. This gives separate tests of the linear, quadratic, cubic, … trends of the response, without the need to specify them separately in the model</p>
</section><section id="example-adolescent-mental-health" class="level3" data-number="10.4.3"><h3 data-number="10.4.3" class="anchored" data-anchor-id="example-adolescent-mental-health">
<span class="header-section-number">10.4.3</span> Example: Adolescent mental health</h3>
<p>The dataset <code><a href="https://friendly.github.io/heplots/reference/AddHealth.html">heplots::AddHealth</a></code> contains a large cross-sectional sample of participants from grades 7–12 from the National Longitudinal Study of Adolescent Health, described by <span class="citation" data-cites="Warne2014">Warne (<a href="95-references.html#ref-Warne2014" role="doc-biblioref">2014</a>)</span>. It contains responses to two Likert-scale (1–5) items, <code>anxiety</code> and <code>depression</code>. <code>grade</code> is an <em>ordered</em> factor, which means that the default contrasts are taken as orthogonal polynomials with linear (<code>grade.L</code>), quadratic (<code>grade.Q</code>), up to 5th degree (<code>grade^5</code>) trends, which decompose the total effect of grade.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb27" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="va">AddHealth</span>, package<span class="op">=</span><span class="st">"heplots"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">AddHealth</span><span class="op">)</span></span>
<span><span class="co">#&gt; 'data.frame':  4344 obs. of  3 variables:</span></span>
<span><span class="co">#&gt;  $ grade     : Ord.factor w/ 6 levels "7"&lt;"8"&lt;"9"&lt;"10"&lt;..: 5 4 6 1 2 2 2 3 3 3 ...</span></span>
<span><span class="co">#&gt;  $ depression: int  0 0 0 0 0 0 0 0 1 2 ...</span></span>
<span><span class="co">#&gt;  $ anxiety   : int  0 0 0 1 1 0 0 1 1 0 ...</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The research questions are:</p>
<ul>
<li>How do the means for anxiety and depression vary separately with grade? Is there evidence for linear and nonlinear trends?</li>
<li>How do anxiety and depression vary <em>jointly</em> with grade?</li>
<li>How does the <em>association</em> of anxiety and depression vary with age?</li>
</ul>
<p>The first question can be answered by fitting separate linear models for each response (e.g., <code>lm(anxiety ~ grade))</code>). However the second question is more interesting because it considers the two responses together and takes their correlation into account. This would be fit as the MLM:</p>
<p><span id="eq-AH-mod"><span class="math display">\[
\mathbf{y} = \boldsymbol{\beta}_0 + \boldsymbol{\beta}_1 x + \boldsymbol{\beta}_2 x^2 + \cdots \boldsymbol{\beta}_5 x^5
\tag{10.8}\]</span></span></p>
<p>or, expressed in terms of the variables,</p>
<p><span id="eq-AH-mod2"><span class="math display">\[\begin{aligned}
\begin{bmatrix} y_{\text{anx}} \\y_{\text{dep}} \end{bmatrix} &amp; = &amp;
\begin{bmatrix} \beta_{0,\text{anx}} \\ \beta_{0,\text{dep}} \end{bmatrix} +
\begin{bmatrix} \beta_{1,\text{anx}} \\ \beta_{1,\text{dep}} \end{bmatrix} \text{grade} +
\begin{bmatrix} \beta_{2,\text{anx}} \\ \beta_{2,\text{dep}} \end{bmatrix} \text{grade}^2 \\
&amp; + \cdots
\begin{bmatrix} \beta_{5,\text{anx}} \\ \beta_{5,\text{dep}} \end{bmatrix} \text{grade}^5
\end{aligned} \tag{10.9}\]</span></span></p>
<p>With<code>grade</code> represented as an ordered factor, the values of <span class="math inline">\(x\)</span> in <a href="#eq-AH-mod" class="quarto-xref">Equation&nbsp;<span>10.8</span></a> are those of the orthogonal polynomials given by <code>poly(grade,5)</code>.</p>
<section id="exploratory-plots-1" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="exploratory-plots-1">Exploratory plots</h4>
<p>Some exploratory analysis is useful before fitting and visualizing models. As a first step, we find the means, standard deviations, and standard errors of the means.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Show the code</summary><div class="sourceCode" id="cb28" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">means</span> <span class="op">&lt;-</span> <span class="va">AddHealth</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">grade</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span></span>
<span>    n <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>    dep_sd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">depression</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>    anx_sd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">anxiety</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>    dep_se <span class="op">=</span> <span class="va">dep_sd</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span>,</span>
<span>    anx_se <span class="op">=</span> <span class="va">anx_sd</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span>,</span>
<span>    depression <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">depression</span><span class="op">)</span>,</span>
<span>    anxiety <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">anxiety</span><span class="op">)</span> <span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/relocate.html">relocate</a></span><span class="op">(</span><span class="va">depression</span>, <span class="va">anxiety</span>, .after <span class="op">=</span> <span class="va">grade</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 6 × 8</span></span>
<span><span class="co">#&gt;   grade depression anxiety     n dep_sd anx_sd dep_se anx_se</span></span>
<span><span class="co">#&gt;   &lt;ord&gt;      &lt;dbl&gt;   &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 7          0.881   0.751   622   1.11   1.05 0.0447 0.0420</span></span>
<span><span class="co">#&gt; 2 8          1.08    0.804   664   1.19   1.06 0.0461 0.0411</span></span>
<span><span class="co">#&gt; 3 9          1.17    0.934   778   1.19   1.08 0.0426 0.0387</span></span>
<span><span class="co">#&gt; 4 10         1.27    0.956   817   1.23   1.11 0.0431 0.0388</span></span>
<span><span class="co">#&gt; 5 11         1.37    1.12    790   1.20   1.16 0.0428 0.0411</span></span>
<span><span class="co">#&gt; 6 12         1.34    1.10    673   1.14   1.11 0.0439 0.0426</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Now, plot the means with <span class="math inline">\(\pm 1\)</span> error bars. It appears that average level of both depression and anxiety increase steadily with grade, except for grades 11 and 12 which don’t differ much. Alternatively, we could describe this as relationships that seem largely linear, with a hint of curvature at the upper end.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb29" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">p1</span> <span class="op">&lt;-</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">means</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">grade</span>, y <span class="op">=</span> <span class="va">anxiety</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">4</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>group <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>, linewidth <span class="op">=</span> <span class="fl">1.2</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_errorbar</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>ymin <span class="op">=</span> <span class="va">anxiety</span> <span class="op">-</span> <span class="va">anx_se</span>, </span>
<span>                   ymax <span class="op">=</span> <span class="va">anxiety</span> <span class="op">+</span> <span class="va">anx_se</span><span class="op">)</span>,</span>
<span>                width <span class="op">=</span> <span class="fl">.2</span><span class="op">)</span> </span>
<span></span>
<span><span class="va">p2</span> <span class="op">&lt;-</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">means</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">grade</span>, y <span class="op">=</span> <span class="va">depression</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">4</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>group <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>, linewidth <span class="op">=</span> <span class="fl">1.2</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_errorbar</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>ymin <span class="op">=</span> <span class="va">depression</span> <span class="op">-</span> <span class="va">dep_se</span>, </span>
<span>                    ymax <span class="op">=</span> <span class="va">depression</span> <span class="op">+</span> <span class="va">dep_se</span><span class="op">)</span>,</span>
<span>                width <span class="op">=</span> <span class="fl">.2</span><span class="op">)</span> </span>
<span></span>
<span><span class="va">p1</span> <span class="op">+</span> <span class="va">p2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-addhealth-means-each" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-addhealth-means-each-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/ch10/fig-addhealth-means-each-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-addhealth-means-each-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.7: Means of anxiety and depression by grade, with <span class="math inline">\(\pm 1\)</span> standard error bars.
</figcaption></figure>
</div>
</div>
</div>
<p>It is also useful to within-group correlations using <code><a href="https://friendly.github.io/heplots/reference/covEllipses.html">covEllipses()</a></code>, as shown in <a href="#fig-addhealth-covellipse" class="quarto-xref">Figure&nbsp;<span>10.8</span></a>. This also plots the bivariate means showing the form of the association , treating anxiety and depression as multivariate outcomes. (Because the variability of the scores within groups is so large compared to the range of the means, I show the data ellipses with coverage of only 10%.)</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb30" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://friendly.github.io/heplots/reference/covEllipses.html">covEllipses</a></span><span class="op">(</span><span class="va">AddHealth</span><span class="op">[</span>, <span class="fl">3</span><span class="op">:</span><span class="fl">2</span><span class="op">]</span>, group <span class="op">=</span> <span class="va">AddHealth</span><span class="op">$</span><span class="va">grade</span>,</span>
<span>            pooled <span class="op">=</span> <span class="cn">FALSE</span>, level <span class="op">=</span> <span class="fl">0.1</span>,</span>
<span>            center.cex <span class="op">=</span> <span class="fl">2.5</span>, cex <span class="op">=</span> <span class="fl">1.5</span>, cex.lab <span class="op">=</span> <span class="fl">1.5</span>,</span>
<span>            fill <span class="op">=</span> <span class="cn">TRUE</span>, fill.alpha <span class="op">=</span> <span class="fl">0.05</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-addhealth-covellipse" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-addhealth-covellipse-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/ch10/fig-addhealth-covellipse-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-addhealth-covellipse-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.8: Within-group covariance ellipses for the <code>grade</code> groups.
</figcaption></figure>
</div>
</div>
</div>
</section><section id="fit-the-mlm" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="fit-the-mlm">Fit the MLM</h4>
<p>Now, let’s fit the MLM for both responses jointly in relation to <code>grade</code>. The null hypothesis is that the means for anxiety and depression are the same at all six grades, <span class="math display">\[
\mathcal{H}_0: \mathbf{\mu}_7 = \mathbf{\mu}_8 = \cdots = \mathbf{\mu}_{12} \; ,
\]</span> or equivalently, that all coefficients except the intercept in the model @ref(eq:AH-mod) are zero, <span class="math display">\[
\mathcal{H}_0: \boldsymbol{\beta}_1 =  \boldsymbol{\beta}_2  = \cdots =  \boldsymbol{\beta}_5 = \boldsymbol{0} \; .
\]</span> We fit the MANOVA model, and test the grade effect using <code><a href="https://rdrr.io/pkg/car/man/Anova.html">car::Anova()</a></code>. The effect of <code>grade</code> is highly significant, as we could tell from <a href="#fig-addhealth-means-each" class="quarto-xref">Figure&nbsp;<span>10.7</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb31" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">AH.mlm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">anxiety</span>, <span class="va">depression</span><span class="op">)</span> <span class="op">~</span> <span class="va">grade</span>, data <span class="op">=</span> <span class="va">AddHealth</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># overall test of `grade`</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/car/man/Anova.html">Anova</a></span><span class="op">(</span><span class="va">AH.mlm</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Type II MANOVA Tests: Pillai test statistic</span></span>
<span><span class="co">#&gt;       Df test stat approx F num Df den Df Pr(&gt;F)    </span></span>
<span><span class="co">#&gt; grade  5    0.0224     9.83     10   8676 &lt;2e-16 ***</span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>However, the overall test, with 5 degrees of freedom is diffuse, in that it can be rejected if any pair of means differ. Given that <code>grade</code> is an ordered factor, it makes sense to examine narrower hypotheses of linear and nonlinear trends, <code><a href="https://rdrr.io/pkg/car/man/linearHypothesis.html">car::linearHypothesis()</a></code> on the coefficients of model <code>AH.mlm</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb32" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">AH.mlm</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; NULL</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The joint test of the linear coefficients <span class="math inline">\(\boldsymbol{\beta}_1 = (\beta_{1,\text{anx}},  \beta_{1,\text{dep}})^\mathsf{T}\)</span> for anxiety and depression, <span class="math inline">\(\mathcal{H}_0 : \boldsymbol{\beta}_1 = \boldsymbol{0}\)</span> is highly significant,</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb33" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## linear effect</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/car/man/linearHypothesis.html">linearHypothesis</a></span><span class="op">(</span><span class="va">AH.mlm</span>, <span class="st">"grade.L"</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span>SSP <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Multivariate Tests: </span></span>
<span><span class="co">#&gt;                  Df test stat approx F num Df den Df Pr(&gt;F)    </span></span>
<span><span class="co">#&gt; Pillai            1     0.019     42.5      2   4337 &lt;2e-16 ***</span></span>
<span><span class="co">#&gt; Wilks             1     0.981     42.5      2   4337 &lt;2e-16 ***</span></span>
<span><span class="co">#&gt; Hotelling-Lawley  1     0.020     42.5      2   4337 &lt;2e-16 ***</span></span>
<span><span class="co">#&gt; Roy               1     0.020     42.5      2   4337 &lt;2e-16 ***</span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The test of the quadratic coefficients <span class="math inline">\(\mathcal{H}_0 : \boldsymbol{\beta}_2 = \boldsymbol{0}\)</span> indicates significant curvature in trends across grade, as we saw in the plots of their means in <a href="#fig-addhealth-means-each" class="quarto-xref">Figure&nbsp;<span>10.7</span></a>. One interpretation might be that depression and anxiety after increasing steadily up to grade eleven could level off thereafter.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb34" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## quadratic effect</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/car/man/linearHypothesis.html">linearHypothesis</a></span><span class="op">(</span><span class="va">AH.mlm</span>, <span class="st">"grade.Q"</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span>SSP <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Multivariate Tests: </span></span>
<span><span class="co">#&gt;                  Df test stat approx F num Df den Df Pr(&gt;F)  </span></span>
<span><span class="co">#&gt; Pillai            1     0.002     4.24      2   4337  0.014 *</span></span>
<span><span class="co">#&gt; Wilks             1     0.998     4.24      2   4337  0.014 *</span></span>
<span><span class="co">#&gt; Hotelling-Lawley  1     0.002     4.24      2   4337  0.014 *</span></span>
<span><span class="co">#&gt; Roy               1     0.002     4.24      2   4337  0.014 *</span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>An advantage of linear hypotheses is that we can test several terms <em>jointly</em>. Of interest here is the hypothesis that all higher order terms beyond the quadratic are zero, <span class="math inline">\(\mathcal{H}_0 : \boldsymbol{\beta}_3 =  \boldsymbol{\beta}_4 =  \boldsymbol{\beta}_5 = \boldsymbol{0}\)</span>. Using <code>linearHypothesis</code> you can supply a vector of coefficient names to be tested for their joint effect when dropped from the model.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb35" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">AH.mlm</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] "(Intercept)" "grade.L"     "grade.Q"     "grade.C"    </span></span>
<span><span class="co">#&gt; [5] "grade^4"     "grade^5"</span></span>
<span><span class="co">## joint test of all higher terms</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/car/man/linearHypothesis.html">linearHypothesis</a></span><span class="op">(</span><span class="va">AH.mlm</span>, <span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">AH.mlm</span><span class="op">)</span><span class="op">)</span><span class="op">[</span><span class="fl">3</span><span class="op">:</span><span class="fl">5</span><span class="op">]</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span>SSP <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Multivariate Tests: </span></span>
<span><span class="co">#&gt;                  Df test stat approx F num Df den Df Pr(&gt;F)  </span></span>
<span><span class="co">#&gt; Pillai            3     0.002     1.70      6   8676   0.12  </span></span>
<span><span class="co">#&gt; Wilks             3     0.998     1.70      6   8674   0.12  </span></span>
<span><span class="co">#&gt; Hotelling-Lawley  3     0.002     1.70      6   8672   0.12  </span></span>
<span><span class="co">#&gt; Roy               3     0.002     2.98      3   4338   0.03 *</span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section></section><section id="factorial-manova" class="level3" data-number="10.4.4"><h3 data-number="10.4.4" class="anchored" data-anchor-id="factorial-manova">
<span class="header-section-number">10.4.4</span> Factorial MANOVA</h3>
<p>When there are two or more categorical factors, the general linear model provides a way to investigate the effects (differences in means) of each simultaneously. More importantly, this allows you to determine if factors <em>interact</em>, so the effect of one factor varies with the levels of another factor …</p>
<section id="example-penguins-data" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="example-penguins-data">Example: Penguins data</h4>
<p>In <a href="03-multivariate_plots.html" class="quarto-xref"><span>Chapter 3</span></a> we examined the Palmer penguins data graphically, using a mosaic plot (<a href="03-multivariate_plots.html#fig-peng-mosaic" class="quarto-xref">Figure&nbsp;<span>3.30</span></a>) of the frequencies of the three factors, <code>species</code>, <code>island</code> and <code>sex</code> and then <code>ggpairs()</code> scatterplot matrix (<a href="03-multivariate_plots.html#fig-peng-ggpairs1" class="quarto-xref">Figure&nbsp;<span>3.31</span></a>).</p>
</section></section></section><section id="mra-rightarrow-mmra" class="level2" data-number="10.5"><h2 data-number="10.5" class="anchored" data-anchor-id="mra-rightarrow-mmra">
<span class="header-section-number">10.5</span> MRA <span class="math inline">\(\rightarrow\)</span> MMRA</h2>
</section><section id="ancova-rightarrow-mancova" class="level2" data-number="10.6"><h2 data-number="10.6" class="anchored" data-anchor-id="ancova-rightarrow-mancova">
<span class="header-section-number">10.6</span> ANCOVA <span class="math inline">\(\rightarrow\)</span> MANCOVA</h2>
</section><section id="repeated-measures-designs" class="level2" data-number="10.7"><h2 data-number="10.7" class="anchored" data-anchor-id="repeated-measures-designs">
<span class="header-section-number">10.7</span> Repeated measures designs</h2>
<p><strong>Package summary</strong></p>
<div class="cell" data-layout-align="center">
<p><strong>Packages used here</strong>:</p>
<p>10 packages used here: broom, car, carData, dplyr, ggplot2, heplots, knitr, matlib, patchwork, tidyr</p>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-Friendly-etal:ellipses:2013" class="csl-entry" role="listitem">
Friendly, M., Monette, G., &amp; Fox, J. (2013). Elliptical insights: Understanding statistical methods through elliptical geometry. <em>Statistical Science</em>, <em>28</em>(1), 1–39. <a href="https://doi.org/10.1214/12-STS402">https://doi.org/10.1214/12-STS402</a>
</div>
<div id="ref-Mardia:1970:MMS" class="csl-entry" role="listitem">
Mardia, K. V. (1970). Measures of multivariate skewness and kurtosis with applications. <em>Biometrika</em>, <em>57</em>(3), 519–530. https://doi.org/<a href="http://dx.doi.org/10.2307/2334770">http://dx.doi.org/10.2307/2334770</a>
</div>
<div id="ref-Meyers-etal:2006" class="csl-entry" role="listitem">
Meyers, L. S., Gamst, G., &amp; Guarino, A. J. (2006). <em>Applied multivariate research: Design and interpretation</em>. SAGE Publications.
</div>
<div id="ref-ShapiroWilk1965" class="csl-entry" role="listitem">
Shapiro, S. S., &amp; Wilk, M. B. (1965). An analysis of variance test for normality (complete samples). <em>Biometrika</em>, <em>52</em>(3–4), 591–611. <a href="https://doi.org/10.1093/biomet/52.3-4.591">https://doi.org/10.1093/biomet/52.3-4.591</a>
</div>
<div id="ref-Warne2014" class="csl-entry" role="listitem">
Warne, F. T. (2014). A primer on multivariate analysis of variance(MANOVA) for behavioral scientists. <em>Practical Assessment, Research &amp; Evaluation</em>, <em>19</em>(1). <a href="https://scholarworks.umass.edu/pare/vol19/iss1/17/">https://scholarworks.umass.edu/pare/vol19/iss1/17/</a>
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./09-hotelling.html" class="pagination-link" aria-label="Hotelling's $T^2$">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Hotelling’s <span class="math inline">\(T^2\)</span></span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./11-mlm-viz.html" class="pagination-link" aria-label="Visualizing Multivariate Models">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Visualizing Multivariate Models</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/friendly/vis-MLM-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div></div></footer><script src="site_libs/quarto-contrib/line-highlight-1.0.0/line-highlight.js" defer="true"></script>
</body></html>